// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.BindAcct in login.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class BindAcct extends Message<BindAcct, BindAcct.Builder> {
  public static final ProtoAdapter<BindAcct> ADAPTER = new ProtoAdapter_BindAcct();

  private static final long serialVersionUID = 0L;

  /**
   * 账户类型, 如果是谷歌，accout中填写谷歌邮箱，如果是邮箱，accout填写邮箱
   */
  public int accType;

  /**
   * 账户，硬件Id, MAC地址，或者是手机设备Id, 手机号int32  		 accType = 3;
   */
  public String account;

  public String title;

  public String icon;

  /**
   * 待绑状态，1已绑， 2未绑
   */
  public int bindStatus;

  public BindAcct(int accType, String account, String title, String icon, int bindStatus) {
    this(accType, account, title, icon, bindStatus, ByteString.EMPTY);
  }

  public BindAcct(int accType, String account, String title, String icon, int bindStatus,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.accType = accType;
    if (account == null) {
      throw new IllegalArgumentException("account == null");
    }
    this.account = account;
    if (title == null) {
      throw new IllegalArgumentException("title == null");
    }
    this.title = title;
    if (icon == null) {
      throw new IllegalArgumentException("icon == null");
    }
    this.icon = icon;
    this.bindStatus = bindStatus;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.accType = accType;
    builder.account = account;
    builder.title = title;
    builder.icon = icon;
    builder.bindStatus = bindStatus;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", accType=").append(accType);
    if (account != null) builder.append(", account=").append(Internal.sanitize(account));
    if (title != null) builder.append(", title=").append(Internal.sanitize(title));
    if (icon != null) builder.append(", icon=").append(Internal.sanitize(icon));
    builder.append(", bindStatus=").append(bindStatus);
    return builder.replace(0, 2, "BindAcct{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<BindAcct, Builder> {
    public int accType;

    public String account;

    public String title;

    public String icon;

    public int bindStatus;

    public Builder() {
      accType = 0;
      account = "";
      title = "";
      icon = "";
      bindStatus = 0;
    }

    /**
     * 账户类型, 如果是谷歌，accout中填写谷歌邮箱，如果是邮箱，accout填写邮箱
     */
    public Builder accType(int accType) {
      this.accType = accType;
      return this;
    }

    /**
     * 账户，硬件Id, MAC地址，或者是手机设备Id, 手机号int32  		 accType = 3;
     */
    public Builder account(String account) {
      this.account = account;
      return this;
    }

    public Builder title(String title) {
      this.title = title;
      return this;
    }

    public Builder icon(String icon) {
      this.icon = icon;
      return this;
    }

    /**
     * 待绑状态，1已绑， 2未绑
     */
    public Builder bindStatus(int bindStatus) {
      this.bindStatus = bindStatus;
      return this;
    }

    @Override
    public BindAcct build() {
      return new BindAcct(accType, account, title, icon, bindStatus, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_BindAcct extends ProtoAdapter<BindAcct> {
    public ProtoAdapter_BindAcct() {
      super(FieldEncoding.LENGTH_DELIMITED, BindAcct.class, "type.googleapis.com/haiyaa.BindAcct", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(BindAcct value) {
      int result = 0;
      if (!Objects.equals(value.accType, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(1, value.accType);
      }
      if (!Objects.equals(value.account, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.account);
      }
      if (!Objects.equals(value.title, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.title);
      }
      if (!Objects.equals(value.icon, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(4, value.icon);
      }
      if (!Objects.equals(value.bindStatus, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(5, value.bindStatus);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, BindAcct value) throws IOException {
      if (!Objects.equals(value.accType, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.accType);
      if (!Objects.equals(value.account, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.account);
      if (!Objects.equals(value.title, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.title);
      if (!Objects.equals(value.icon, "")) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.icon);
      if (!Objects.equals(value.bindStatus, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 5, value.bindStatus);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public BindAcct decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.accType(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.account(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.title(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.icon(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.bindStatus(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public BindAcct redact(BindAcct value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
