// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.C2CInfo in user.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 动态信息
 */
public final class C2CInfo extends Message<C2CInfo, C2CInfo.Builder> {
  public static final ProtoAdapter<C2CInfo> ADAPTER = new ProtoAdapter_C2CInfo();

  private static final long serialVersionUID = 0L;

  /**
   * C2CInfo
   * 今日是否已点过爱心
   */
  public boolean todaylove;

  /**
   * 用户关系 1 已关注我 2 我已关注 3 已互关，如果是互关好友，会有一定的爱心值
   */
  public int relation;

  /**
   * 关系值=亲密度，互关好友才有
   */
  public long relationVal;

  /**
   * 缔结关系时间
   */
  public long relationTime;

  public C2CInfo(boolean todaylove, int relation, long relationVal, long relationTime) {
    this(todaylove, relation, relationVal, relationTime, ByteString.EMPTY);
  }

  public C2CInfo(boolean todaylove, int relation, long relationVal, long relationTime,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.todaylove = todaylove;
    this.relation = relation;
    this.relationVal = relationVal;
    this.relationTime = relationTime;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.todaylove = todaylove;
    builder.relation = relation;
    builder.relationVal = relationVal;
    builder.relationTime = relationTime;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", todaylove=").append(todaylove);
    builder.append(", relation=").append(relation);
    builder.append(", relationVal=").append(relationVal);
    builder.append(", relationTime=").append(relationTime);
    return builder.replace(0, 2, "C2CInfo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<C2CInfo, Builder> {
    public boolean todaylove;

    public int relation;

    public long relationVal;

    public long relationTime;

    public Builder() {
      todaylove = false;
      relation = 0;
      relationVal = 0L;
      relationTime = 0L;
    }

    /**
     * C2CInfo
     * 今日是否已点过爱心
     */
    public Builder todaylove(boolean todaylove) {
      this.todaylove = todaylove;
      return this;
    }

    /**
     * 用户关系 1 已关注我 2 我已关注 3 已互关，如果是互关好友，会有一定的爱心值
     */
    public Builder relation(int relation) {
      this.relation = relation;
      return this;
    }

    /**
     * 关系值=亲密度，互关好友才有
     */
    public Builder relationVal(long relationVal) {
      this.relationVal = relationVal;
      return this;
    }

    /**
     * 缔结关系时间
     */
    public Builder relationTime(long relationTime) {
      this.relationTime = relationTime;
      return this;
    }

    @Override
    public C2CInfo build() {
      return new C2CInfo(todaylove, relation, relationVal, relationTime, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_C2CInfo extends ProtoAdapter<C2CInfo> {
    public ProtoAdapter_C2CInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, C2CInfo.class, "type.googleapis.com/haiyaa.C2CInfo", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(C2CInfo value) {
      int result = 0;
      if (!Objects.equals(value.todaylove, false)) {
        result += ProtoAdapter.BOOL.encodedSizeWithTag(1, value.todaylove);
      }
      if (!Objects.equals(value.relation, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.relation);
      }
      if (!Objects.equals(value.relationVal, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(3, value.relationVal);
      }
      if (!Objects.equals(value.relationTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(4, value.relationTime);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, C2CInfo value) throws IOException {
      if (!Objects.equals(value.todaylove, false)) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.todaylove);
      if (!Objects.equals(value.relation, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.relation);
      if (!Objects.equals(value.relationVal, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 3, value.relationVal);
      if (!Objects.equals(value.relationTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 4, value.relationTime);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public C2CInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.todaylove(ProtoAdapter.BOOL.decode(reader)); break;
          case 2: builder.relation(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.relationVal(ProtoAdapter.INT64.decode(reader)); break;
          case 4: builder.relationTime(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public C2CInfo redact(C2CInfo value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
