// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.CheckSignCodeReq in haiyaa.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 验证码校验登录
 */
public final class CheckSignCodeReq extends Message<CheckSignCodeReq, CheckSignCodeReq.Builder> {
  public static final ProtoAdapter<CheckSignCodeReq> ADAPTER = new ProtoAdapter_CheckSignCodeReq();

  private static final long serialVersionUID = 0L;

  /**
   * 账户类型, 手机=1 邮箱=3 谷歌=9 enum LoginType{
   */
  public int accType;

  /**
   * 账户，手机 或 邮箱 或 谷歌账号
   */
  public String account;

  /**
   * 验证码
   */
  public String signCode;

  public CheckSignCodeReq(int accType, String account, String signCode) {
    this(accType, account, signCode, ByteString.EMPTY);
  }

  public CheckSignCodeReq(int accType, String account, String signCode, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.accType = accType;
    if (account == null) {
      throw new IllegalArgumentException("account == null");
    }
    this.account = account;
    if (signCode == null) {
      throw new IllegalArgumentException("signCode == null");
    }
    this.signCode = signCode;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.accType = accType;
    builder.account = account;
    builder.signCode = signCode;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", accType=").append(accType);
    if (account != null) builder.append(", account=").append(Internal.sanitize(account));
    if (signCode != null) builder.append(", signCode=").append(Internal.sanitize(signCode));
    return builder.replace(0, 2, "CheckSignCodeReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CheckSignCodeReq, Builder> {
    public int accType;

    public String account;

    public String signCode;

    public Builder() {
      accType = 0;
      account = "";
      signCode = "";
    }

    /**
     * 账户类型, 手机=1 邮箱=3 谷歌=9 enum LoginType{
     */
    public Builder accType(int accType) {
      this.accType = accType;
      return this;
    }

    /**
     * 账户，手机 或 邮箱 或 谷歌账号
     */
    public Builder account(String account) {
      this.account = account;
      return this;
    }

    /**
     * 验证码
     */
    public Builder signCode(String signCode) {
      this.signCode = signCode;
      return this;
    }

    @Override
    public CheckSignCodeReq build() {
      return new CheckSignCodeReq(accType, account, signCode, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CheckSignCodeReq extends ProtoAdapter<CheckSignCodeReq> {
    public ProtoAdapter_CheckSignCodeReq() {
      super(FieldEncoding.LENGTH_DELIMITED, CheckSignCodeReq.class, "type.googleapis.com/haiyaa.CheckSignCodeReq", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(CheckSignCodeReq value) {
      int result = 0;
      if (!Objects.equals(value.accType, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(1, value.accType);
      }
      if (!Objects.equals(value.account, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.account);
      }
      if (!Objects.equals(value.signCode, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.signCode);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, CheckSignCodeReq value) throws IOException {
      if (!Objects.equals(value.accType, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.accType);
      if (!Objects.equals(value.account, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.account);
      if (!Objects.equals(value.signCode, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.signCode);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CheckSignCodeReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.accType(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.account(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.signCode(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public CheckSignCodeReq redact(CheckSignCodeReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
