// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.CheckVerifyCode in login.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 请求或校验 邮箱或手机 校验码
 */
public final class CheckVerifyCode extends Message<CheckVerifyCode, CheckVerifyCode.Builder> {
  public static final ProtoAdapter<CheckVerifyCode> ADAPTER = new ProtoAdapter_CheckVerifyCode();

  private static final long serialVersionUID = 0L;

  /**
   * 校验码类型，校验用途
   */
  public int vcType;

  /**
   * 密码
   */
  public String vcCode;

  /**
   * 账户,这里是手机号或邮箱，邮箱也可以发送验证码
   */
  public String account;

  /**
   * 账户类型，这里是手机号或邮箱，邮箱也可以发送验证码
   */
  public int accType;

  public CheckVerifyCode(int vcType, String vcCode, String account, int accType) {
    this(vcType, vcCode, account, accType, ByteString.EMPTY);
  }

  public CheckVerifyCode(int vcType, String vcCode, String account, int accType,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.vcType = vcType;
    if (vcCode == null) {
      throw new IllegalArgumentException("vcCode == null");
    }
    this.vcCode = vcCode;
    if (account == null) {
      throw new IllegalArgumentException("account == null");
    }
    this.account = account;
    this.accType = accType;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.vcType = vcType;
    builder.vcCode = vcCode;
    builder.account = account;
    builder.accType = accType;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", vcType=").append(vcType);
    if (vcCode != null) builder.append(", vcCode=").append(Internal.sanitize(vcCode));
    if (account != null) builder.append(", account=").append(Internal.sanitize(account));
    builder.append(", accType=").append(accType);
    return builder.replace(0, 2, "CheckVerifyCode{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CheckVerifyCode, Builder> {
    public int vcType;

    public String vcCode;

    public String account;

    public int accType;

    public Builder() {
      vcType = 0;
      vcCode = "";
      account = "";
      accType = 0;
    }

    /**
     * 校验码类型，校验用途
     */
    public Builder vcType(int vcType) {
      this.vcType = vcType;
      return this;
    }

    /**
     * 密码
     */
    public Builder vcCode(String vcCode) {
      this.vcCode = vcCode;
      return this;
    }

    /**
     * 账户,这里是手机号或邮箱，邮箱也可以发送验证码
     */
    public Builder account(String account) {
      this.account = account;
      return this;
    }

    /**
     * 账户类型，这里是手机号或邮箱，邮箱也可以发送验证码
     */
    public Builder accType(int accType) {
      this.accType = accType;
      return this;
    }

    @Override
    public CheckVerifyCode build() {
      return new CheckVerifyCode(vcType, vcCode, account, accType, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CheckVerifyCode extends ProtoAdapter<CheckVerifyCode> {
    public ProtoAdapter_CheckVerifyCode() {
      super(FieldEncoding.LENGTH_DELIMITED, CheckVerifyCode.class, "type.googleapis.com/haiyaa.CheckVerifyCode", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(CheckVerifyCode value) {
      int result = 0;
      if (!Objects.equals(value.vcType, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(1, value.vcType);
      }
      if (!Objects.equals(value.vcCode, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.vcCode);
      }
      if (!Objects.equals(value.account, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.account);
      }
      if (!Objects.equals(value.accType, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(4, value.accType);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, CheckVerifyCode value) throws IOException {
      if (!Objects.equals(value.vcType, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.vcType);
      if (!Objects.equals(value.vcCode, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.vcCode);
      if (!Objects.equals(value.account, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.account);
      if (!Objects.equals(value.accType, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.accType);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CheckVerifyCode decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.vcType(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.vcCode(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.account(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.accType(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public CheckVerifyCode redact(CheckVerifyCode value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
