// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.CheckBindAcct in login.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 1-PC登录专用;url="/login/prelogin/";
 */
public final class CheckBindAcct extends Message<CheckBindAcct, CheckBindAcct.Builder> {
  public static final ProtoAdapter<CheckBindAcct> ADAPTER = new ProtoAdapter_CheckBindAcct();

  private static final long serialVersionUID = 0L;

  /**
   * 1 绑定， 2解绑
   */
  public int action;

  /**
   * 账户类型, 如果是谷歌，accout中填写谷歌邮箱，如果是邮箱，accout填写邮箱
   */
  public int accType;

  /**
   * 账户，硬件Id, MAC地址，或者是手机设备Id, 手机号
   */
  public String account;

  /**
   * 校验码
   */
  public String vcCode;

  public CheckBindAcct(int action, int accType, String account, String vcCode) {
    this(action, accType, account, vcCode, ByteString.EMPTY);
  }

  public CheckBindAcct(int action, int accType, String account, String vcCode,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.action = action;
    this.accType = accType;
    if (account == null) {
      throw new IllegalArgumentException("account == null");
    }
    this.account = account;
    if (vcCode == null) {
      throw new IllegalArgumentException("vcCode == null");
    }
    this.vcCode = vcCode;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.action = action;
    builder.accType = accType;
    builder.account = account;
    builder.vcCode = vcCode;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", action=").append(action);
    builder.append(", accType=").append(accType);
    if (account != null) builder.append(", account=").append(Internal.sanitize(account));
    if (vcCode != null) builder.append(", vcCode=").append(Internal.sanitize(vcCode));
    return builder.replace(0, 2, "CheckBindAcct{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CheckBindAcct, Builder> {
    public int action;

    public int accType;

    public String account;

    public String vcCode;

    public Builder() {
      action = 0;
      accType = 0;
      account = "";
      vcCode = "";
    }

    /**
     * 1 绑定， 2解绑
     */
    public Builder action(int action) {
      this.action = action;
      return this;
    }

    /**
     * 账户类型, 如果是谷歌，accout中填写谷歌邮箱，如果是邮箱，accout填写邮箱
     */
    public Builder accType(int accType) {
      this.accType = accType;
      return this;
    }

    /**
     * 账户，硬件Id, MAC地址，或者是手机设备Id, 手机号
     */
    public Builder account(String account) {
      this.account = account;
      return this;
    }

    /**
     * 校验码
     */
    public Builder vcCode(String vcCode) {
      this.vcCode = vcCode;
      return this;
    }

    @Override
    public CheckBindAcct build() {
      return new CheckBindAcct(action, accType, account, vcCode, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CheckBindAcct extends ProtoAdapter<CheckBindAcct> {
    public ProtoAdapter_CheckBindAcct() {
      super(FieldEncoding.LENGTH_DELIMITED, CheckBindAcct.class, "type.googleapis.com/haiyaa.CheckBindAcct", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(CheckBindAcct value) {
      int result = 0;
      if (!Objects.equals(value.action, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(1, value.action);
      }
      if (!Objects.equals(value.accType, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.accType);
      }
      if (!Objects.equals(value.account, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.account);
      }
      if (!Objects.equals(value.vcCode, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(4, value.vcCode);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, CheckBindAcct value) throws IOException {
      if (!Objects.equals(value.action, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.action);
      if (!Objects.equals(value.accType, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.accType);
      if (!Objects.equals(value.account, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.account);
      if (!Objects.equals(value.vcCode, "")) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.vcCode);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CheckBindAcct decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.action(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.accType(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.account(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.vcCode(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public CheckBindAcct redact(CheckBindAcct value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
