// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.CheckAccount in login.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 1-预登陆;url="/login/prelogin/";
 */
public final class CheckAccount extends Message<CheckAccount, CheckAccount.Builder> {
  public static final ProtoAdapter<CheckAccount> ADAPTER = new ProtoAdapter_CheckAccount();

  private static final long serialVersionUID = 0L;

  /**
   * 账户，硬件Id, MAC地址，或者是手机设备Id
   */
  public String account;

  /**
   * 账户类型
   */
  public int accType;

  /**
   * 密码
   */
  public String accPwd;

  /**
   * 密码类型
   */
  public int pwdType;

  public CheckAccount(String account, int accType, String accPwd, int pwdType) {
    this(account, accType, accPwd, pwdType, ByteString.EMPTY);
  }

  public CheckAccount(String account, int accType, String accPwd, int pwdType,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (account == null) {
      throw new IllegalArgumentException("account == null");
    }
    this.account = account;
    this.accType = accType;
    if (accPwd == null) {
      throw new IllegalArgumentException("accPwd == null");
    }
    this.accPwd = accPwd;
    this.pwdType = pwdType;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.account = account;
    builder.accType = accType;
    builder.accPwd = accPwd;
    builder.pwdType = pwdType;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (account != null) builder.append(", account=").append(Internal.sanitize(account));
    builder.append(", accType=").append(accType);
    if (accPwd != null) builder.append(", accPwd=").append(Internal.sanitize(accPwd));
    builder.append(", pwdType=").append(pwdType);
    return builder.replace(0, 2, "CheckAccount{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CheckAccount, Builder> {
    public String account;

    public int accType;

    public String accPwd;

    public int pwdType;

    public Builder() {
      account = "";
      accType = 0;
      accPwd = "";
      pwdType = 0;
    }

    /**
     * 账户，硬件Id, MAC地址，或者是手机设备Id
     */
    public Builder account(String account) {
      this.account = account;
      return this;
    }

    /**
     * 账户类型
     */
    public Builder accType(int accType) {
      this.accType = accType;
      return this;
    }

    /**
     * 密码
     */
    public Builder accPwd(String accPwd) {
      this.accPwd = accPwd;
      return this;
    }

    /**
     * 密码类型
     */
    public Builder pwdType(int pwdType) {
      this.pwdType = pwdType;
      return this;
    }

    @Override
    public CheckAccount build() {
      return new CheckAccount(account, accType, accPwd, pwdType, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CheckAccount extends ProtoAdapter<CheckAccount> {
    public ProtoAdapter_CheckAccount() {
      super(FieldEncoding.LENGTH_DELIMITED, CheckAccount.class, "type.googleapis.com/haiyaa.CheckAccount", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(CheckAccount value) {
      int result = 0;
      if (!Objects.equals(value.account, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.account);
      }
      if (!Objects.equals(value.accType, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.accType);
      }
      if (!Objects.equals(value.accPwd, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.accPwd);
      }
      if (!Objects.equals(value.pwdType, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(4, value.pwdType);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, CheckAccount value) throws IOException {
      if (!Objects.equals(value.account, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.account);
      if (!Objects.equals(value.accType, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.accType);
      if (!Objects.equals(value.accPwd, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.accPwd);
      if (!Objects.equals(value.pwdType, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.pwdType);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CheckAccount decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.account(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.accType(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.accPwd(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.pwdType(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public CheckAccount redact(CheckAccount value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
