// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.CommentInfo in moment.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class CommentInfo extends Message<CommentInfo, CommentInfo.Builder> {
  public static final ProtoAdapter<CommentInfo> ADAPTER = new ProtoAdapter_CommentInfo();

  private static final long serialVersionUID = 0L;

  /**
   * 必填。 瞬间Id
   */
  public long MomentId;

  /**
   * 不填  【注意：客户端不用传！！！！！】
   */
  public long CommentId;

  /**
   * 选填  【如果是回复给哪条评论，要填。】 0，表示瞬间，非0，表示回复的回复
   */
  public long ToCommentId;

  /**
   * 必填  发布者Id
   */
  public long UserId;

  /**
   * 不填  回复给Id   【可以不用传】
   */
  public long ToUserId;

  /**
   * 不填  回复
   */
  public long RpyUserId;

  /**
   * 必填  内容文本
   */
  public String Content;

  /**
   * 不填  评论数量
   */
  public int ComNum;

  /**
   * 不填  点赞数量
   */
  public int LikeNum;

  /**
   * 不填  创建时间
   */
  public long CtTime;

  /**
   * 不填  更新时间
   */
  public long UpTime;

  /**
   * 不填  发布者信息
   */
  public UserBase Publisher;

  /**
   * 不填  被回复者信息
   */
  public UserBase RpyUser;

  public CommentInfo(long MomentId, long CommentId, long ToCommentId, long UserId, long ToUserId,
      long RpyUserId, String Content, int ComNum, int LikeNum, long CtTime, long UpTime,
      UserBase Publisher, UserBase RpyUser) {
    this(MomentId, CommentId, ToCommentId, UserId, ToUserId, RpyUserId, Content, ComNum, LikeNum, CtTime, UpTime, Publisher, RpyUser, ByteString.EMPTY);
  }

  public CommentInfo(long MomentId, long CommentId, long ToCommentId, long UserId, long ToUserId,
      long RpyUserId, String Content, int ComNum, int LikeNum, long CtTime, long UpTime,
      UserBase Publisher, UserBase RpyUser, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.MomentId = MomentId;
    this.CommentId = CommentId;
    this.ToCommentId = ToCommentId;
    this.UserId = UserId;
    this.ToUserId = ToUserId;
    this.RpyUserId = RpyUserId;
    if (Content == null) {
      throw new IllegalArgumentException("Content == null");
    }
    this.Content = Content;
    this.ComNum = ComNum;
    this.LikeNum = LikeNum;
    this.CtTime = CtTime;
    this.UpTime = UpTime;
    this.Publisher = Publisher;
    this.RpyUser = RpyUser;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.MomentId = MomentId;
    builder.CommentId = CommentId;
    builder.ToCommentId = ToCommentId;
    builder.UserId = UserId;
    builder.ToUserId = ToUserId;
    builder.RpyUserId = RpyUserId;
    builder.Content = Content;
    builder.ComNum = ComNum;
    builder.LikeNum = LikeNum;
    builder.CtTime = CtTime;
    builder.UpTime = UpTime;
    builder.Publisher = Publisher;
    builder.RpyUser = RpyUser;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", MomentId=").append(MomentId);
    builder.append(", CommentId=").append(CommentId);
    builder.append(", ToCommentId=").append(ToCommentId);
    builder.append(", UserId=").append(UserId);
    builder.append(", ToUserId=").append(ToUserId);
    builder.append(", RpyUserId=").append(RpyUserId);
    if (Content != null) builder.append(", Content=").append(Internal.sanitize(Content));
    builder.append(", ComNum=").append(ComNum);
    builder.append(", LikeNum=").append(LikeNum);
    builder.append(", CtTime=").append(CtTime);
    builder.append(", UpTime=").append(UpTime);
    if (Publisher != null) builder.append(", Publisher=").append(Publisher);
    if (RpyUser != null) builder.append(", RpyUser=").append(RpyUser);
    return builder.replace(0, 2, "CommentInfo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CommentInfo, Builder> {
    public long MomentId;

    public long CommentId;

    public long ToCommentId;

    public long UserId;

    public long ToUserId;

    public long RpyUserId;

    public String Content;

    public int ComNum;

    public int LikeNum;

    public long CtTime;

    public long UpTime;

    public UserBase Publisher;

    public UserBase RpyUser;

    public Builder() {
      MomentId = 0L;
      CommentId = 0L;
      ToCommentId = 0L;
      UserId = 0L;
      ToUserId = 0L;
      RpyUserId = 0L;
      Content = "";
      ComNum = 0;
      LikeNum = 0;
      CtTime = 0L;
      UpTime = 0L;
    }

    /**
     * 必填。 瞬间Id
     */
    public Builder MomentId(long MomentId) {
      this.MomentId = MomentId;
      return this;
    }

    /**
     * 不填  【注意：客户端不用传！！！！！】
     */
    public Builder CommentId(long CommentId) {
      this.CommentId = CommentId;
      return this;
    }

    /**
     * 选填  【如果是回复给哪条评论，要填。】 0，表示瞬间，非0，表示回复的回复
     */
    public Builder ToCommentId(long ToCommentId) {
      this.ToCommentId = ToCommentId;
      return this;
    }

    /**
     * 必填  发布者Id
     */
    public Builder UserId(long UserId) {
      this.UserId = UserId;
      return this;
    }

    /**
     * 不填  回复给Id   【可以不用传】
     */
    public Builder ToUserId(long ToUserId) {
      this.ToUserId = ToUserId;
      return this;
    }

    /**
     * 不填  回复
     */
    public Builder RpyUserId(long RpyUserId) {
      this.RpyUserId = RpyUserId;
      return this;
    }

    /**
     * 必填  内容文本
     */
    public Builder Content(String Content) {
      this.Content = Content;
      return this;
    }

    /**
     * 不填  评论数量
     */
    public Builder ComNum(int ComNum) {
      this.ComNum = ComNum;
      return this;
    }

    /**
     * 不填  点赞数量
     */
    public Builder LikeNum(int LikeNum) {
      this.LikeNum = LikeNum;
      return this;
    }

    /**
     * 不填  创建时间
     */
    public Builder CtTime(long CtTime) {
      this.CtTime = CtTime;
      return this;
    }

    /**
     * 不填  更新时间
     */
    public Builder UpTime(long UpTime) {
      this.UpTime = UpTime;
      return this;
    }

    /**
     * 不填  发布者信息
     */
    public Builder Publisher(UserBase Publisher) {
      this.Publisher = Publisher;
      return this;
    }

    /**
     * 不填  被回复者信息
     */
    public Builder RpyUser(UserBase RpyUser) {
      this.RpyUser = RpyUser;
      return this;
    }

    @Override
    public CommentInfo build() {
      return new CommentInfo(MomentId, CommentId, ToCommentId, UserId, ToUserId, RpyUserId, Content, ComNum, LikeNum, CtTime, UpTime, Publisher, RpyUser, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CommentInfo extends ProtoAdapter<CommentInfo> {
    public ProtoAdapter_CommentInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, CommentInfo.class, "type.googleapis.com/haiyaa.CommentInfo", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(CommentInfo value) {
      int result = 0;
      if (!Objects.equals(value.MomentId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.MomentId);
      }
      if (!Objects.equals(value.CommentId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(2, value.CommentId);
      }
      if (!Objects.equals(value.ToCommentId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(3, value.ToCommentId);
      }
      if (!Objects.equals(value.UserId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(4, value.UserId);
      }
      if (!Objects.equals(value.ToUserId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(5, value.ToUserId);
      }
      if (!Objects.equals(value.RpyUserId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(7, value.RpyUserId);
      }
      if (!Objects.equals(value.Content, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(6, value.Content);
      }
      if (!Objects.equals(value.ComNum, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(8, value.ComNum);
      }
      if (!Objects.equals(value.LikeNum, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(9, value.LikeNum);
      }
      if (!Objects.equals(value.CtTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(15, value.CtTime);
      }
      if (!Objects.equals(value.UpTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(16, value.UpTime);
      }
      if (!Objects.equals(value.Publisher, null)) {
        result += UserBase.ADAPTER.encodedSizeWithTag(21, value.Publisher);
      }
      if (!Objects.equals(value.RpyUser, null)) {
        result += UserBase.ADAPTER.encodedSizeWithTag(22, value.RpyUser);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, CommentInfo value) throws IOException {
      if (!Objects.equals(value.MomentId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.MomentId);
      if (!Objects.equals(value.CommentId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.CommentId);
      if (!Objects.equals(value.ToCommentId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 3, value.ToCommentId);
      if (!Objects.equals(value.UserId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 4, value.UserId);
      if (!Objects.equals(value.ToUserId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 5, value.ToUserId);
      if (!Objects.equals(value.RpyUserId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 7, value.RpyUserId);
      if (!Objects.equals(value.Content, "")) ProtoAdapter.STRING.encodeWithTag(writer, 6, value.Content);
      if (!Objects.equals(value.ComNum, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 8, value.ComNum);
      if (!Objects.equals(value.LikeNum, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 9, value.LikeNum);
      if (!Objects.equals(value.CtTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 15, value.CtTime);
      if (!Objects.equals(value.UpTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 16, value.UpTime);
      if (!Objects.equals(value.Publisher, null)) UserBase.ADAPTER.encodeWithTag(writer, 21, value.Publisher);
      if (!Objects.equals(value.RpyUser, null)) UserBase.ADAPTER.encodeWithTag(writer, 22, value.RpyUser);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CommentInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.MomentId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.CommentId(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.ToCommentId(ProtoAdapter.UINT64.decode(reader)); break;
          case 4: builder.UserId(ProtoAdapter.UINT64.decode(reader)); break;
          case 5: builder.ToUserId(ProtoAdapter.UINT64.decode(reader)); break;
          case 6: builder.Content(ProtoAdapter.STRING.decode(reader)); break;
          case 7: builder.RpyUserId(ProtoAdapter.UINT64.decode(reader)); break;
          case 8: builder.ComNum(ProtoAdapter.INT32.decode(reader)); break;
          case 9: builder.LikeNum(ProtoAdapter.INT32.decode(reader)); break;
          case 15: builder.CtTime(ProtoAdapter.INT64.decode(reader)); break;
          case 16: builder.UpTime(ProtoAdapter.INT64.decode(reader)); break;
          case 21: builder.Publisher(UserBase.ADAPTER.decode(reader)); break;
          case 22: builder.RpyUser(UserBase.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public CommentInfo redact(CommentInfo value) {
      Builder builder = value.newBuilder();
      if (builder.Publisher != null) builder.Publisher = UserBase.ADAPTER.redact(builder.Publisher);
      if (builder.RpyUser != null) builder.RpyUser = UserBase.ADAPTER.redact(builder.RpyUser);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
