// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.CountryS in public.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Objects;
import okio.ByteString;

public final class CountryS extends Message<CountryS, CountryS.Builder> {
  public static final ProtoAdapter<CountryS> ADAPTER = new ProtoAdapter_CountryS();

  private static final long serialVersionUID = 0L;

  public List<Country> countrys;

  public String locateAt;

  public CountryS(List<Country> countrys, String locateAt) {
    this(countrys, locateAt, ByteString.EMPTY);
  }

  public CountryS(List<Country> countrys, String locateAt, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.countrys = Internal.immutableCopyOf("countrys", countrys);
    if (locateAt == null) {
      throw new IllegalArgumentException("locateAt == null");
    }
    this.locateAt = locateAt;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.countrys = Internal.copyOf(countrys);
    builder.locateAt = locateAt;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!countrys.isEmpty()) builder.append(", countrys=").append(countrys);
    if (locateAt != null) builder.append(", locateAt=").append(Internal.sanitize(locateAt));
    return builder.replace(0, 2, "CountryS{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CountryS, Builder> {
    public List<Country> countrys;

    public String locateAt;

    public Builder() {
      countrys = Internal.newMutableList();
      locateAt = "";
    }

    public Builder countrys(List<Country> countrys) {
      Internal.checkElementsNotNull(countrys);
      this.countrys = countrys;
      return this;
    }

    public Builder locateAt(String locateAt) {
      this.locateAt = locateAt;
      return this;
    }

    @Override
    public CountryS build() {
      return new CountryS(countrys, locateAt, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CountryS extends ProtoAdapter<CountryS> {
    public ProtoAdapter_CountryS() {
      super(FieldEncoding.LENGTH_DELIMITED, CountryS.class, "type.googleapis.com/haiyaa.CountryS", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(CountryS value) {
      int result = 0;
      result += Country.ADAPTER.asRepeated().encodedSizeWithTag(1, value.countrys);
      if (!Objects.equals(value.locateAt, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.locateAt);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, CountryS value) throws IOException {
      Country.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.countrys);
      if (!Objects.equals(value.locateAt, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.locateAt);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CountryS decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.countrys.add(Country.ADAPTER.decode(reader)); break;
          case 2: builder.locateAt(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public CountryS redact(CountryS value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.countrys, Country.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
