// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.DecoInfo in public.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 用户勋章
 */
public final class DecoInfo extends Message<DecoInfo, DecoInfo.Builder> {
  public static final ProtoAdapter<DecoInfo> ADAPTER = new ProtoAdapter_DecoInfo();

  private static final long serialVersionUID = 0L;

  /**
   * 装饰类型 1、等级挂件 2、头像挂件 3、公屏气泡、4、进房动效、5、房间背景
   */
  public int decoType;

  /**
   * 装扮Id
   */
  public int decoId;

  /**
   * 特效名字
   */
  public String decoName;

  /**
   * 是否在用，0, 1在用，2、下架
   */
  public int status;

  /**
   * 特效类型, 0, 1普通，2、SVG
   */
  public int showType;

  /**
   * 特效地址
   */
  public String showUrl;

  /**
   * 获得时间
   */
  public long stTime;

  /**
   * 下架时间
   */
  public long edTime;

  public DecoInfo(int decoType, int decoId, String decoName, int status, int showType,
      String showUrl, long stTime, long edTime) {
    this(decoType, decoId, decoName, status, showType, showUrl, stTime, edTime, ByteString.EMPTY);
  }

  public DecoInfo(int decoType, int decoId, String decoName, int status, int showType,
      String showUrl, long stTime, long edTime, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.decoType = decoType;
    this.decoId = decoId;
    if (decoName == null) {
      throw new IllegalArgumentException("decoName == null");
    }
    this.decoName = decoName;
    this.status = status;
    this.showType = showType;
    if (showUrl == null) {
      throw new IllegalArgumentException("showUrl == null");
    }
    this.showUrl = showUrl;
    this.stTime = stTime;
    this.edTime = edTime;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.decoType = decoType;
    builder.decoId = decoId;
    builder.decoName = decoName;
    builder.status = status;
    builder.showType = showType;
    builder.showUrl = showUrl;
    builder.stTime = stTime;
    builder.edTime = edTime;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", decoType=").append(decoType);
    builder.append(", decoId=").append(decoId);
    if (decoName != null) builder.append(", decoName=").append(Internal.sanitize(decoName));
    builder.append(", status=").append(status);
    builder.append(", showType=").append(showType);
    if (showUrl != null) builder.append(", showUrl=").append(Internal.sanitize(showUrl));
    builder.append(", stTime=").append(stTime);
    builder.append(", edTime=").append(edTime);
    return builder.replace(0, 2, "DecoInfo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<DecoInfo, Builder> {
    public int decoType;

    public int decoId;

    public String decoName;

    public int status;

    public int showType;

    public String showUrl;

    public long stTime;

    public long edTime;

    public Builder() {
      decoType = 0;
      decoId = 0;
      decoName = "";
      status = 0;
      showType = 0;
      showUrl = "";
      stTime = 0L;
      edTime = 0L;
    }

    /**
     * 装饰类型 1、等级挂件 2、头像挂件 3、公屏气泡、4、进房动效、5、房间背景
     */
    public Builder decoType(int decoType) {
      this.decoType = decoType;
      return this;
    }

    /**
     * 装扮Id
     */
    public Builder decoId(int decoId) {
      this.decoId = decoId;
      return this;
    }

    /**
     * 特效名字
     */
    public Builder decoName(String decoName) {
      this.decoName = decoName;
      return this;
    }

    /**
     * 是否在用，0, 1在用，2、下架
     */
    public Builder status(int status) {
      this.status = status;
      return this;
    }

    /**
     * 特效类型, 0, 1普通，2、SVG
     */
    public Builder showType(int showType) {
      this.showType = showType;
      return this;
    }

    /**
     * 特效地址
     */
    public Builder showUrl(String showUrl) {
      this.showUrl = showUrl;
      return this;
    }

    /**
     * 获得时间
     */
    public Builder stTime(long stTime) {
      this.stTime = stTime;
      return this;
    }

    /**
     * 下架时间
     */
    public Builder edTime(long edTime) {
      this.edTime = edTime;
      return this;
    }

    @Override
    public DecoInfo build() {
      return new DecoInfo(decoType, decoId, decoName, status, showType, showUrl, stTime, edTime, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_DecoInfo extends ProtoAdapter<DecoInfo> {
    public ProtoAdapter_DecoInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, DecoInfo.class, "type.googleapis.com/haiyaa.DecoInfo", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(DecoInfo value) {
      int result = 0;
      if (!Objects.equals(value.decoType, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(1, value.decoType);
      }
      if (!Objects.equals(value.decoId, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.decoId);
      }
      if (!Objects.equals(value.decoName, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(4, value.decoName);
      }
      if (!Objects.equals(value.status, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(3, value.status);
      }
      if (!Objects.equals(value.showType, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(6, value.showType);
      }
      if (!Objects.equals(value.showUrl, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(7, value.showUrl);
      }
      if (!Objects.equals(value.stTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(11, value.stTime);
      }
      if (!Objects.equals(value.edTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(12, value.edTime);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, DecoInfo value) throws IOException {
      if (!Objects.equals(value.decoType, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.decoType);
      if (!Objects.equals(value.decoId, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.decoId);
      if (!Objects.equals(value.decoName, "")) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.decoName);
      if (!Objects.equals(value.status, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.status);
      if (!Objects.equals(value.showType, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 6, value.showType);
      if (!Objects.equals(value.showUrl, "")) ProtoAdapter.STRING.encodeWithTag(writer, 7, value.showUrl);
      if (!Objects.equals(value.stTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 11, value.stTime);
      if (!Objects.equals(value.edTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 12, value.edTime);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public DecoInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.decoType(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.decoId(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.status(ProtoAdapter.INT32.decode(reader)); break;
          case 4: builder.decoName(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.showType(ProtoAdapter.INT32.decode(reader)); break;
          case 7: builder.showUrl(ProtoAdapter.STRING.decode(reader)); break;
          case 11: builder.stTime(ProtoAdapter.INT64.decode(reader)); break;
          case 12: builder.edTime(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public DecoInfo redact(DecoInfo value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
