// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.DouStatS in login.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class DouStatS extends Message<DouStatS, DouStatS.Builder> {
  public static final ProtoAdapter<DouStatS> ADAPTER = new ProtoAdapter_DouStatS();

  private static final long serialVersionUID = 0L;

  /**
   * 当前在线多少人
   */
  public int OnlineUser;

  /**
   * 当前在线多少人
   */
  public int OnlineRoom;

  /**
   * 当前房间人数
   */
  public int haiyaa_RoomUser;

  public DouStatS(int OnlineUser, int OnlineRoom, int haiyaa_RoomUser) {
    this(OnlineUser, OnlineRoom, haiyaa_RoomUser, ByteString.EMPTY);
  }

  public DouStatS(int OnlineUser, int OnlineRoom, int haiyaa_RoomUser, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.OnlineUser = OnlineUser;
    this.OnlineRoom = OnlineRoom;
    this.haiyaa_RoomUser = haiyaa_RoomUser;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.OnlineUser = OnlineUser;
    builder.OnlineRoom = OnlineRoom;
    builder.haiyaa_RoomUser = haiyaa_RoomUser;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", OnlineUser=").append(OnlineUser);
    builder.append(", OnlineRoom=").append(OnlineRoom);
    builder.append(", RoomUser=").append(haiyaa_RoomUser);
    return builder.replace(0, 2, "DouStatS{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<DouStatS, Builder> {
    public int OnlineUser;

    public int OnlineRoom;

    public int haiyaa_RoomUser;

    public Builder() {
      OnlineUser = 0;
      OnlineRoom = 0;
      haiyaa_RoomUser = 0;
    }

    /**
     * 当前在线多少人
     */
    public Builder OnlineUser(int OnlineUser) {
      this.OnlineUser = OnlineUser;
      return this;
    }

    /**
     * 当前在线多少人
     */
    public Builder OnlineRoom(int OnlineRoom) {
      this.OnlineRoom = OnlineRoom;
      return this;
    }

    /**
     * 当前房间人数
     */
    public Builder haiyaa_RoomUser(int haiyaa_RoomUser) {
      this.haiyaa_RoomUser = haiyaa_RoomUser;
      return this;
    }

    @Override
    public DouStatS build() {
      return new DouStatS(OnlineUser, OnlineRoom, haiyaa_RoomUser, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_DouStatS extends ProtoAdapter<DouStatS> {
    public ProtoAdapter_DouStatS() {
      super(FieldEncoding.LENGTH_DELIMITED, DouStatS.class, "type.googleapis.com/haiyaa.DouStatS", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(DouStatS value) {
      int result = 0;
      if (!Objects.equals(value.OnlineUser, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(1, value.OnlineUser);
      }
      if (!Objects.equals(value.OnlineRoom, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.OnlineRoom);
      }
      if (!Objects.equals(value.haiyaa_RoomUser, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(3, value.haiyaa_RoomUser);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, DouStatS value) throws IOException {
      if (!Objects.equals(value.OnlineUser, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.OnlineUser);
      if (!Objects.equals(value.OnlineRoom, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.OnlineRoom);
      if (!Objects.equals(value.haiyaa_RoomUser, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.haiyaa_RoomUser);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public DouStatS decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.OnlineUser(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.OnlineRoom(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.haiyaa_RoomUser(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public DouStatS redact(DouStatS value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
