// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.DrawStatus in pay.proto
package com.hao.proto;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * 提现状态
 */
public enum DrawStatus implements WireEnum {
  DS_Zero(0),

  /**
   * 已发起提现
   */
  DS_CREATE(1),

  /**
   * 提现审核中
   */
  DS_VERIFY(2),

  /**
   * 用户取消
   */
  DS_CANCEL(3),

  /**
   * 审核拒绝
   */
  DS_DENYED(4),

  /**
   * 系统失败
   */
  DS_FAIURE(5),

  /**
   * 已支付，已转账，账单已完成
   */
  DS_TRANSED(100);

  public static final ProtoAdapter<DrawStatus> ADAPTER = new ProtoAdapter_DrawStatus();

  private final int value;

  DrawStatus(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static DrawStatus fromValue(int value) {
    switch (value) {
      case 0: return DS_Zero;
      case 1: return DS_CREATE;
      case 2: return DS_VERIFY;
      case 3: return DS_CANCEL;
      case 4: return DS_DENYED;
      case 5: return DS_FAIURE;
      case 100: return DS_TRANSED;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_DrawStatus extends EnumAdapter<DrawStatus> {
    ProtoAdapter_DrawStatus() {
      super(DrawStatus.class, Syntax.PROTO_3, DrawStatus.DS_Zero);
    }

    @Override
    protected DrawStatus fromValue(int value) {
      return DrawStatus.fromValue(value);
    }
  }
}
