// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.DrawOrder in pay.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 提现商品订单
 */
public final class DrawOrder extends Message<DrawOrder, DrawOrder.Builder> {
  public static final ProtoAdapter<DrawOrder> ADAPTER = new ProtoAdapter_DrawOrder();

  private static final long serialVersionUID = 0L;

  /**
   * 商品Id
   */
  public long userId;

  /**
   * 订单号
   */
  public String orderId;

  /**
   * 商品Id
   */
  public int goodId;

  /**
   * 订单描述
   */
  public String goodDesc;

  /**
   * 商品价格
   */
  public double price;

  /**
   * 商品对应的黑钻
   */
  public double bcoin;

  /**
   * 订单状态
   */
  public int status;

  /**
   * 订单备注
   */
  public String note;

  /**
   * 创建时间，订单创建时间
   */
  public long ctTime;

  /**
   * 更新时间，订单更新时间
   */
  public long upTime;

  public DrawOrder(long userId, String orderId, int goodId, String goodDesc, double price,
      double bcoin, int status, String note, long ctTime, long upTime) {
    this(userId, orderId, goodId, goodDesc, price, bcoin, status, note, ctTime, upTime, ByteString.EMPTY);
  }

  public DrawOrder(long userId, String orderId, int goodId, String goodDesc, double price,
      double bcoin, int status, String note, long ctTime, long upTime, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.userId = userId;
    if (orderId == null) {
      throw new IllegalArgumentException("orderId == null");
    }
    this.orderId = orderId;
    this.goodId = goodId;
    if (goodDesc == null) {
      throw new IllegalArgumentException("goodDesc == null");
    }
    this.goodDesc = goodDesc;
    this.price = price;
    this.bcoin = bcoin;
    this.status = status;
    if (note == null) {
      throw new IllegalArgumentException("note == null");
    }
    this.note = note;
    this.ctTime = ctTime;
    this.upTime = upTime;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.userId = userId;
    builder.orderId = orderId;
    builder.goodId = goodId;
    builder.goodDesc = goodDesc;
    builder.price = price;
    builder.bcoin = bcoin;
    builder.status = status;
    builder.note = note;
    builder.ctTime = ctTime;
    builder.upTime = upTime;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", userId=").append(userId);
    if (orderId != null) builder.append(", orderId=").append(Internal.sanitize(orderId));
    builder.append(", goodId=").append(goodId);
    if (goodDesc != null) builder.append(", goodDesc=").append(Internal.sanitize(goodDesc));
    builder.append(", price=").append(price);
    builder.append(", bcoin=").append(bcoin);
    builder.append(", status=").append(status);
    if (note != null) builder.append(", note=").append(Internal.sanitize(note));
    builder.append(", ctTime=").append(ctTime);
    builder.append(", upTime=").append(upTime);
    return builder.replace(0, 2, "DrawOrder{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<DrawOrder, Builder> {
    public long userId;

    public String orderId;

    public int goodId;

    public String goodDesc;

    public double price;

    public double bcoin;

    public int status;

    public String note;

    public long ctTime;

    public long upTime;

    public Builder() {
      userId = 0L;
      orderId = "";
      goodId = 0;
      goodDesc = "";
      price = 0.0;
      bcoin = 0.0;
      status = 0;
      note = "";
      ctTime = 0L;
      upTime = 0L;
    }

    /**
     * 商品Id
     */
    public Builder userId(long userId) {
      this.userId = userId;
      return this;
    }

    /**
     * 订单号
     */
    public Builder orderId(String orderId) {
      this.orderId = orderId;
      return this;
    }

    /**
     * 商品Id
     */
    public Builder goodId(int goodId) {
      this.goodId = goodId;
      return this;
    }

    /**
     * 订单描述
     */
    public Builder goodDesc(String goodDesc) {
      this.goodDesc = goodDesc;
      return this;
    }

    /**
     * 商品价格
     */
    public Builder price(double price) {
      this.price = price;
      return this;
    }

    /**
     * 商品对应的黑钻
     */
    public Builder bcoin(double bcoin) {
      this.bcoin = bcoin;
      return this;
    }

    /**
     * 订单状态
     */
    public Builder status(int status) {
      this.status = status;
      return this;
    }

    /**
     * 订单备注
     */
    public Builder note(String note) {
      this.note = note;
      return this;
    }

    /**
     * 创建时间，订单创建时间
     */
    public Builder ctTime(long ctTime) {
      this.ctTime = ctTime;
      return this;
    }

    /**
     * 更新时间，订单更新时间
     */
    public Builder upTime(long upTime) {
      this.upTime = upTime;
      return this;
    }

    @Override
    public DrawOrder build() {
      return new DrawOrder(userId, orderId, goodId, goodDesc, price, bcoin, status, note, ctTime, upTime, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_DrawOrder extends ProtoAdapter<DrawOrder> {
    public ProtoAdapter_DrawOrder() {
      super(FieldEncoding.LENGTH_DELIMITED, DrawOrder.class, "type.googleapis.com/haiyaa.DrawOrder", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(DrawOrder value) {
      int result = 0;
      if (!Objects.equals(value.userId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.userId);
      }
      if (!Objects.equals(value.orderId, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.orderId);
      }
      if (!Objects.equals(value.goodId, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(3, value.goodId);
      }
      if (!Objects.equals(value.goodDesc, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(4, value.goodDesc);
      }
      if (!Objects.equals(value.price, 0.0)) {
        result += ProtoAdapter.DOUBLE.encodedSizeWithTag(6, value.price);
      }
      if (!Objects.equals(value.bcoin, 0.0)) {
        result += ProtoAdapter.DOUBLE.encodedSizeWithTag(7, value.bcoin);
      }
      if (!Objects.equals(value.status, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(8, value.status);
      }
      if (!Objects.equals(value.note, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(9, value.note);
      }
      if (!Objects.equals(value.ctTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(13, value.ctTime);
      }
      if (!Objects.equals(value.upTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(14, value.upTime);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, DrawOrder value) throws IOException {
      if (!Objects.equals(value.userId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.userId);
      if (!Objects.equals(value.orderId, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.orderId);
      if (!Objects.equals(value.goodId, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.goodId);
      if (!Objects.equals(value.goodDesc, "")) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.goodDesc);
      if (!Objects.equals(value.price, 0.0)) ProtoAdapter.DOUBLE.encodeWithTag(writer, 6, value.price);
      if (!Objects.equals(value.bcoin, 0.0)) ProtoAdapter.DOUBLE.encodeWithTag(writer, 7, value.bcoin);
      if (!Objects.equals(value.status, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 8, value.status);
      if (!Objects.equals(value.note, "")) ProtoAdapter.STRING.encodeWithTag(writer, 9, value.note);
      if (!Objects.equals(value.ctTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 13, value.ctTime);
      if (!Objects.equals(value.upTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 14, value.upTime);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public DrawOrder decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.userId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.orderId(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.goodId(ProtoAdapter.INT32.decode(reader)); break;
          case 4: builder.goodDesc(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.price(ProtoAdapter.DOUBLE.decode(reader)); break;
          case 7: builder.bcoin(ProtoAdapter.DOUBLE.decode(reader)); break;
          case 8: builder.status(ProtoAdapter.INT32.decode(reader)); break;
          case 9: builder.note(ProtoAdapter.STRING.decode(reader)); break;
          case 13: builder.ctTime(ProtoAdapter.INT64.decode(reader)); break;
          case 14: builder.upTime(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public DrawOrder redact(DrawOrder value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
