// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.EventInfoS in event.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class EventInfoS extends Message<EventInfoS, EventInfoS.Builder> {
  public static final ProtoAdapter<EventInfoS> ADAPTER = new ProtoAdapter_EventInfoS();

  private static final long serialVersionUID = 0L;

  public List<EventInfo> events;

  public EventInfoS(List<EventInfo> events) {
    this(events, ByteString.EMPTY);
  }

  public EventInfoS(List<EventInfo> events, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.events = Internal.immutableCopyOf("events", events);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.events = Internal.copyOf(events);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!events.isEmpty()) builder.append(", events=").append(events);
    return builder.replace(0, 2, "EventInfoS{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<EventInfoS, Builder> {
    public List<EventInfo> events;

    public Builder() {
      events = Internal.newMutableList();
    }

    public Builder events(List<EventInfo> events) {
      Internal.checkElementsNotNull(events);
      this.events = events;
      return this;
    }

    @Override
    public EventInfoS build() {
      return new EventInfoS(events, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_EventInfoS extends ProtoAdapter<EventInfoS> {
    public ProtoAdapter_EventInfoS() {
      super(FieldEncoding.LENGTH_DELIMITED, EventInfoS.class, "type.googleapis.com/haiyaa.EventInfoS", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(EventInfoS value) {
      int result = 0;
      result += EventInfo.ADAPTER.asRepeated().encodedSizeWithTag(1, value.events);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, EventInfoS value) throws IOException {
      EventInfo.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.events);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public EventInfoS decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.events.add(EventInfo.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public EventInfoS redact(EventInfoS value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.events, EventInfo.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
