// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.FaceVerifyReq in pay.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 身份核验
 */
public final class FaceVerifyReq extends Message<FaceVerifyReq, FaceVerifyReq.Builder> {
  public static final ProtoAdapter<FaceVerifyReq> ADAPTER = new ProtoAdapter_FaceVerifyReq();

  private static final long serialVersionUID = 0L;

  /**
   * 人员
   */
  public long userId;

  /**
   * 真实姓名, 必填
   */
  public String realName;

  /**
   * 身份证编号，必填
   */
  public String idCard;

  public FaceVerifyReq(long userId, String realName, String idCard) {
    this(userId, realName, idCard, ByteString.EMPTY);
  }

  public FaceVerifyReq(long userId, String realName, String idCard, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.userId = userId;
    if (realName == null) {
      throw new IllegalArgumentException("realName == null");
    }
    this.realName = realName;
    if (idCard == null) {
      throw new IllegalArgumentException("idCard == null");
    }
    this.idCard = idCard;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.userId = userId;
    builder.realName = realName;
    builder.idCard = idCard;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", userId=").append(userId);
    if (realName != null) builder.append(", realName=").append(Internal.sanitize(realName));
    if (idCard != null) builder.append(", idCard=").append(Internal.sanitize(idCard));
    return builder.replace(0, 2, "FaceVerifyReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<FaceVerifyReq, Builder> {
    public long userId;

    public String realName;

    public String idCard;

    public Builder() {
      userId = 0L;
      realName = "";
      idCard = "";
    }

    /**
     * 人员
     */
    public Builder userId(long userId) {
      this.userId = userId;
      return this;
    }

    /**
     * 真实姓名, 必填
     */
    public Builder realName(String realName) {
      this.realName = realName;
      return this;
    }

    /**
     * 身份证编号，必填
     */
    public Builder idCard(String idCard) {
      this.idCard = idCard;
      return this;
    }

    @Override
    public FaceVerifyReq build() {
      return new FaceVerifyReq(userId, realName, idCard, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_FaceVerifyReq extends ProtoAdapter<FaceVerifyReq> {
    public ProtoAdapter_FaceVerifyReq() {
      super(FieldEncoding.LENGTH_DELIMITED, FaceVerifyReq.class, "type.googleapis.com/haiyaa.FaceVerifyReq", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(FaceVerifyReq value) {
      int result = 0;
      if (!Objects.equals(value.userId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.userId);
      }
      if (!Objects.equals(value.realName, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.realName);
      }
      if (!Objects.equals(value.idCard, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.idCard);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, FaceVerifyReq value) throws IOException {
      if (!Objects.equals(value.userId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.userId);
      if (!Objects.equals(value.realName, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.realName);
      if (!Objects.equals(value.idCard, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.idCard);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public FaceVerifyReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.userId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.realName(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.idCard(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public FaceVerifyReq redact(FaceVerifyReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
