// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.FamilyInfo in family.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Objects;
import okio.ByteString;

public final class FamilyInfo extends Message<FamilyInfo, FamilyInfo.Builder> {
  public static final ProtoAdapter<FamilyInfo> ADAPTER = new ProtoAdapter_FamilyInfo();

  private static final long serialVersionUID = 0L;

  /**
   * 家族Id
   */
  public long FamilyId;

  /**
   * 家族Id
   */
  public long ShowId;

  /**
   * 家族类型
   */
  public int Kind;

  /**
   * 家族房间
   */
  public long RoomId;

  /**
   * 家族名称
   */
  public String Name;

  /**
   * 家族图标
   */
  public String Icon;

  /**
   * 成员数量
   */
  public int Member;

  /**
   * 管理员列表
   */
  public List<Long> Managers;

  /**
   * 家族等级
   */
  public int Level;

  /**
   * 家族公告
   */
  public String Notice;

  /**
   * 家族描述
   */
  public String Descript;

  /**
   * 家族经验
   */
  public long Experence;

  /**
   * 特有礼物
   */
  public int GiftId;

  /**
   * 礼物经验
   */
  public int GiftExp;

  /**
   * 家族创建者
   */
  public long CreaterId;

  /**
   * 家族拥有者
   */
  public long OwnerId;

  /**
   * 拥有者手机
   */
  public long PhoneId;

  /**
   * 成员上限
   */
  public int MemberMax;

  /**
   * 管理员上限
   */
  public int MangerMax;

  /**
   * 开放类型
   */
  public int OpenType;

  /**
   * 审批模式
   */
  public int AuthType;

  /**
   * 比特开关
   */
  public long BitData;

  /**
   * 族长后台密码
   */
  public String PassWord;

  /**
   * 身份证号码
   */
  public String IdCard;

  /**
   * 合作状态
   */
  public int Cooperate;

  /**
   * 锁定状态
   */
  public int Locked;

  /**
   * 更新时间
   */
  public long UpTime;

  /**
   * 创建时间
   */
  public long CtTime;

  public FamilyInfo(Builder builder, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.FamilyId = builder.FamilyId;
    this.ShowId = builder.ShowId;
    this.Kind = builder.Kind;
    this.RoomId = builder.RoomId;
    if (builder.Name == null) {
      throw new IllegalArgumentException("builder.Name == null");
    }
    this.Name = builder.Name;
    if (builder.Icon == null) {
      throw new IllegalArgumentException("builder.Icon == null");
    }
    this.Icon = builder.Icon;
    this.Member = builder.Member;
    this.Managers = Internal.immutableCopyOf("Managers", builder.Managers);
    this.Level = builder.Level;
    if (builder.Notice == null) {
      throw new IllegalArgumentException("builder.Notice == null");
    }
    this.Notice = builder.Notice;
    if (builder.Descript == null) {
      throw new IllegalArgumentException("builder.Descript == null");
    }
    this.Descript = builder.Descript;
    this.Experence = builder.Experence;
    this.GiftId = builder.GiftId;
    this.GiftExp = builder.GiftExp;
    this.CreaterId = builder.CreaterId;
    this.OwnerId = builder.OwnerId;
    this.PhoneId = builder.PhoneId;
    this.MemberMax = builder.MemberMax;
    this.MangerMax = builder.MangerMax;
    this.OpenType = builder.OpenType;
    this.AuthType = builder.AuthType;
    this.BitData = builder.BitData;
    if (builder.PassWord == null) {
      throw new IllegalArgumentException("builder.PassWord == null");
    }
    this.PassWord = builder.PassWord;
    if (builder.IdCard == null) {
      throw new IllegalArgumentException("builder.IdCard == null");
    }
    this.IdCard = builder.IdCard;
    this.Cooperate = builder.Cooperate;
    this.Locked = builder.Locked;
    this.UpTime = builder.UpTime;
    this.CtTime = builder.CtTime;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.FamilyId = FamilyId;
    builder.ShowId = ShowId;
    builder.Kind = Kind;
    builder.RoomId = RoomId;
    builder.Name = Name;
    builder.Icon = Icon;
    builder.Member = Member;
    builder.Managers = Internal.copyOf(Managers);
    builder.Level = Level;
    builder.Notice = Notice;
    builder.Descript = Descript;
    builder.Experence = Experence;
    builder.GiftId = GiftId;
    builder.GiftExp = GiftExp;
    builder.CreaterId = CreaterId;
    builder.OwnerId = OwnerId;
    builder.PhoneId = PhoneId;
    builder.MemberMax = MemberMax;
    builder.MangerMax = MangerMax;
    builder.OpenType = OpenType;
    builder.AuthType = AuthType;
    builder.BitData = BitData;
    builder.PassWord = PassWord;
    builder.IdCard = IdCard;
    builder.Cooperate = Cooperate;
    builder.Locked = Locked;
    builder.UpTime = UpTime;
    builder.CtTime = CtTime;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", FamilyId=").append(FamilyId);
    builder.append(", ShowId=").append(ShowId);
    builder.append(", Kind=").append(Kind);
    builder.append(", RoomId=").append(RoomId);
    if (Name != null) builder.append(", Name=").append(Internal.sanitize(Name));
    if (Icon != null) builder.append(", Icon=").append(Internal.sanitize(Icon));
    builder.append(", Member=").append(Member);
    if (!Managers.isEmpty()) builder.append(", Managers=").append(Managers);
    builder.append(", Level=").append(Level);
    if (Notice != null) builder.append(", Notice=").append(Internal.sanitize(Notice));
    if (Descript != null) builder.append(", Descript=").append(Internal.sanitize(Descript));
    builder.append(", Experence=").append(Experence);
    builder.append(", GiftId=").append(GiftId);
    builder.append(", GiftExp=").append(GiftExp);
    builder.append(", CreaterId=").append(CreaterId);
    builder.append(", OwnerId=").append(OwnerId);
    builder.append(", PhoneId=").append(PhoneId);
    builder.append(", MemberMax=").append(MemberMax);
    builder.append(", MangerMax=").append(MangerMax);
    builder.append(", OpenType=").append(OpenType);
    builder.append(", AuthType=").append(AuthType);
    builder.append(", BitData=").append(BitData);
    if (PassWord != null) builder.append(", PassWord=").append(Internal.sanitize(PassWord));
    if (IdCard != null) builder.append(", IdCard=").append(Internal.sanitize(IdCard));
    builder.append(", Cooperate=").append(Cooperate);
    builder.append(", Locked=").append(Locked);
    builder.append(", UpTime=").append(UpTime);
    builder.append(", CtTime=").append(CtTime);
    return builder.replace(0, 2, "FamilyInfo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<FamilyInfo, Builder> {
    public long FamilyId;

    public long ShowId;

    public int Kind;

    public long RoomId;

    public String Name;

    public String Icon;

    public int Member;

    public List<Long> Managers;

    public int Level;

    public String Notice;

    public String Descript;

    public long Experence;

    public int GiftId;

    public int GiftExp;

    public long CreaterId;

    public long OwnerId;

    public long PhoneId;

    public int MemberMax;

    public int MangerMax;

    public int OpenType;

    public int AuthType;

    public long BitData;

    public String PassWord;

    public String IdCard;

    public int Cooperate;

    public int Locked;

    public long UpTime;

    public long CtTime;

    public Builder() {
      FamilyId = 0L;
      ShowId = 0L;
      Kind = 0;
      RoomId = 0L;
      Name = "";
      Icon = "";
      Member = 0;
      Managers = Internal.newMutableList();
      Level = 0;
      Notice = "";
      Descript = "";
      Experence = 0L;
      GiftId = 0;
      GiftExp = 0;
      CreaterId = 0L;
      OwnerId = 0L;
      PhoneId = 0L;
      MemberMax = 0;
      MangerMax = 0;
      OpenType = 0;
      AuthType = 0;
      BitData = 0L;
      PassWord = "";
      IdCard = "";
      Cooperate = 0;
      Locked = 0;
      UpTime = 0L;
      CtTime = 0L;
    }

    /**
     * 家族Id
     */
    public Builder FamilyId(long FamilyId) {
      this.FamilyId = FamilyId;
      return this;
    }

    /**
     * 家族Id
     */
    public Builder ShowId(long ShowId) {
      this.ShowId = ShowId;
      return this;
    }

    /**
     * 家族类型
     */
    public Builder Kind(int Kind) {
      this.Kind = Kind;
      return this;
    }

    /**
     * 家族房间
     */
    public Builder RoomId(long RoomId) {
      this.RoomId = RoomId;
      return this;
    }

    /**
     * 家族名称
     */
    public Builder Name(String Name) {
      this.Name = Name;
      return this;
    }

    /**
     * 家族图标
     */
    public Builder Icon(String Icon) {
      this.Icon = Icon;
      return this;
    }

    /**
     * 成员数量
     */
    public Builder Member(int Member) {
      this.Member = Member;
      return this;
    }

    /**
     * 管理员列表
     */
    public Builder Managers(List<Long> Managers) {
      Internal.checkElementsNotNull(Managers);
      this.Managers = Managers;
      return this;
    }

    /**
     * 家族等级
     */
    public Builder Level(int Level) {
      this.Level = Level;
      return this;
    }

    /**
     * 家族公告
     */
    public Builder Notice(String Notice) {
      this.Notice = Notice;
      return this;
    }

    /**
     * 家族描述
     */
    public Builder Descript(String Descript) {
      this.Descript = Descript;
      return this;
    }

    /**
     * 家族经验
     */
    public Builder Experence(long Experence) {
      this.Experence = Experence;
      return this;
    }

    /**
     * 特有礼物
     */
    public Builder GiftId(int GiftId) {
      this.GiftId = GiftId;
      return this;
    }

    /**
     * 礼物经验
     */
    public Builder GiftExp(int GiftExp) {
      this.GiftExp = GiftExp;
      return this;
    }

    /**
     * 家族创建者
     */
    public Builder CreaterId(long CreaterId) {
      this.CreaterId = CreaterId;
      return this;
    }

    /**
     * 家族拥有者
     */
    public Builder OwnerId(long OwnerId) {
      this.OwnerId = OwnerId;
      return this;
    }

    /**
     * 拥有者手机
     */
    public Builder PhoneId(long PhoneId) {
      this.PhoneId = PhoneId;
      return this;
    }

    /**
     * 成员上限
     */
    public Builder MemberMax(int MemberMax) {
      this.MemberMax = MemberMax;
      return this;
    }

    /**
     * 管理员上限
     */
    public Builder MangerMax(int MangerMax) {
      this.MangerMax = MangerMax;
      return this;
    }

    /**
     * 开放类型
     */
    public Builder OpenType(int OpenType) {
      this.OpenType = OpenType;
      return this;
    }

    /**
     * 审批模式
     */
    public Builder AuthType(int AuthType) {
      this.AuthType = AuthType;
      return this;
    }

    /**
     * 比特开关
     */
    public Builder BitData(long BitData) {
      this.BitData = BitData;
      return this;
    }

    /**
     * 族长后台密码
     */
    public Builder PassWord(String PassWord) {
      this.PassWord = PassWord;
      return this;
    }

    /**
     * 身份证号码
     */
    public Builder IdCard(String IdCard) {
      this.IdCard = IdCard;
      return this;
    }

    /**
     * 合作状态
     */
    public Builder Cooperate(int Cooperate) {
      this.Cooperate = Cooperate;
      return this;
    }

    /**
     * 锁定状态
     */
    public Builder Locked(int Locked) {
      this.Locked = Locked;
      return this;
    }

    /**
     * 更新时间
     */
    public Builder UpTime(long UpTime) {
      this.UpTime = UpTime;
      return this;
    }

    /**
     * 创建时间
     */
    public Builder CtTime(long CtTime) {
      this.CtTime = CtTime;
      return this;
    }

    @Override
    public FamilyInfo build() {
      return new FamilyInfo(this, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_FamilyInfo extends ProtoAdapter<FamilyInfo> {
    public ProtoAdapter_FamilyInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, FamilyInfo.class, "type.googleapis.com/haiyaa.FamilyInfo", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(FamilyInfo value) {
      int result = 0;
      if (!Objects.equals(value.FamilyId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.FamilyId);
      }
      if (!Objects.equals(value.ShowId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(2, value.ShowId);
      }
      if (!Objects.equals(value.Kind, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(3, value.Kind);
      }
      if (!Objects.equals(value.RoomId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(4, value.RoomId);
      }
      if (!Objects.equals(value.Name, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(5, value.Name);
      }
      if (!Objects.equals(value.Icon, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(6, value.Icon);
      }
      if (!Objects.equals(value.Member, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(11, value.Member);
      }
      result += ProtoAdapter.UINT64.asPacked().encodedSizeWithTag(12, value.Managers);
      if (!Objects.equals(value.Level, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(13, value.Level);
      }
      if (!Objects.equals(value.Notice, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(14, value.Notice);
      }
      if (!Objects.equals(value.Descript, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(15, value.Descript);
      }
      if (!Objects.equals(value.Experence, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(21, value.Experence);
      }
      if (!Objects.equals(value.GiftId, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(22, value.GiftId);
      }
      if (!Objects.equals(value.GiftExp, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(23, value.GiftExp);
      }
      if (!Objects.equals(value.CreaterId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(31, value.CreaterId);
      }
      if (!Objects.equals(value.OwnerId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(32, value.OwnerId);
      }
      if (!Objects.equals(value.PhoneId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(33, value.PhoneId);
      }
      if (!Objects.equals(value.MemberMax, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(34, value.MemberMax);
      }
      if (!Objects.equals(value.MangerMax, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(35, value.MangerMax);
      }
      if (!Objects.equals(value.OpenType, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(41, value.OpenType);
      }
      if (!Objects.equals(value.AuthType, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(42, value.AuthType);
      }
      if (!Objects.equals(value.BitData, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(43, value.BitData);
      }
      if (!Objects.equals(value.PassWord, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(44, value.PassWord);
      }
      if (!Objects.equals(value.IdCard, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(51, value.IdCard);
      }
      if (!Objects.equals(value.Cooperate, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(52, value.Cooperate);
      }
      if (!Objects.equals(value.Locked, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(53, value.Locked);
      }
      if (!Objects.equals(value.UpTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(61, value.UpTime);
      }
      if (!Objects.equals(value.CtTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(62, value.CtTime);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, FamilyInfo value) throws IOException {
      if (!Objects.equals(value.FamilyId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.FamilyId);
      if (!Objects.equals(value.ShowId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.ShowId);
      if (!Objects.equals(value.Kind, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.Kind);
      if (!Objects.equals(value.RoomId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 4, value.RoomId);
      if (!Objects.equals(value.Name, "")) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.Name);
      if (!Objects.equals(value.Icon, "")) ProtoAdapter.STRING.encodeWithTag(writer, 6, value.Icon);
      if (!Objects.equals(value.Member, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 11, value.Member);
      ProtoAdapter.UINT64.asPacked().encodeWithTag(writer, 12, value.Managers);
      if (!Objects.equals(value.Level, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 13, value.Level);
      if (!Objects.equals(value.Notice, "")) ProtoAdapter.STRING.encodeWithTag(writer, 14, value.Notice);
      if (!Objects.equals(value.Descript, "")) ProtoAdapter.STRING.encodeWithTag(writer, 15, value.Descript);
      if (!Objects.equals(value.Experence, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 21, value.Experence);
      if (!Objects.equals(value.GiftId, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 22, value.GiftId);
      if (!Objects.equals(value.GiftExp, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 23, value.GiftExp);
      if (!Objects.equals(value.CreaterId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 31, value.CreaterId);
      if (!Objects.equals(value.OwnerId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 32, value.OwnerId);
      if (!Objects.equals(value.PhoneId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 33, value.PhoneId);
      if (!Objects.equals(value.MemberMax, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 34, value.MemberMax);
      if (!Objects.equals(value.MangerMax, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 35, value.MangerMax);
      if (!Objects.equals(value.OpenType, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 41, value.OpenType);
      if (!Objects.equals(value.AuthType, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 42, value.AuthType);
      if (!Objects.equals(value.BitData, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 43, value.BitData);
      if (!Objects.equals(value.PassWord, "")) ProtoAdapter.STRING.encodeWithTag(writer, 44, value.PassWord);
      if (!Objects.equals(value.IdCard, "")) ProtoAdapter.STRING.encodeWithTag(writer, 51, value.IdCard);
      if (!Objects.equals(value.Cooperate, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 52, value.Cooperate);
      if (!Objects.equals(value.Locked, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 53, value.Locked);
      if (!Objects.equals(value.UpTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 61, value.UpTime);
      if (!Objects.equals(value.CtTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 62, value.CtTime);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public FamilyInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.FamilyId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.ShowId(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.Kind(ProtoAdapter.INT32.decode(reader)); break;
          case 4: builder.RoomId(ProtoAdapter.UINT64.decode(reader)); break;
          case 5: builder.Name(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.Icon(ProtoAdapter.STRING.decode(reader)); break;
          case 11: builder.Member(ProtoAdapter.INT32.decode(reader)); break;
          case 12: builder.Managers.add(ProtoAdapter.UINT64.decode(reader)); break;
          case 13: builder.Level(ProtoAdapter.INT32.decode(reader)); break;
          case 14: builder.Notice(ProtoAdapter.STRING.decode(reader)); break;
          case 15: builder.Descript(ProtoAdapter.STRING.decode(reader)); break;
          case 21: builder.Experence(ProtoAdapter.INT64.decode(reader)); break;
          case 22: builder.GiftId(ProtoAdapter.INT32.decode(reader)); break;
          case 23: builder.GiftExp(ProtoAdapter.INT32.decode(reader)); break;
          case 31: builder.CreaterId(ProtoAdapter.UINT64.decode(reader)); break;
          case 32: builder.OwnerId(ProtoAdapter.UINT64.decode(reader)); break;
          case 33: builder.PhoneId(ProtoAdapter.UINT64.decode(reader)); break;
          case 34: builder.MemberMax(ProtoAdapter.INT32.decode(reader)); break;
          case 35: builder.MangerMax(ProtoAdapter.INT32.decode(reader)); break;
          case 41: builder.OpenType(ProtoAdapter.INT32.decode(reader)); break;
          case 42: builder.AuthType(ProtoAdapter.INT32.decode(reader)); break;
          case 43: builder.BitData(ProtoAdapter.UINT64.decode(reader)); break;
          case 44: builder.PassWord(ProtoAdapter.STRING.decode(reader)); break;
          case 51: builder.IdCard(ProtoAdapter.STRING.decode(reader)); break;
          case 52: builder.Cooperate(ProtoAdapter.INT32.decode(reader)); break;
          case 53: builder.Locked(ProtoAdapter.INT32.decode(reader)); break;
          case 61: builder.UpTime(ProtoAdapter.INT64.decode(reader)); break;
          case 62: builder.CtTime(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public FamilyInfo redact(FamilyInfo value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
