// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.FundCmd in pbcmd.proto
package com.hao.proto;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * 资产中心
 */
public enum FundCmd implements WireEnum {
  /**
   * 资产类请求
   */
  FundCmd_Zero(0),

  /**
   * 谷歌发起支付
   * &haiyaa.TradePay{}//&haiyaa.PayOrder{}//谷歌充值, 返回充值订单
   */
  GOOGLE_TRAEDE_PAY(3611),

  /**
   * 谷歌支付验签
   * &haiyaa.TradeReceipt{}//&haiyaa.WelthInfo{}//谷歌充值, 返回充值后的用户资产信息
   */
  GOOGLE_CHECK_RECEIPT(3612),

  /**
   * 黑钻提现解锁
   * GOOGLE_DRAW_UNLOCK		= 3613; //&haiyaa.TradeReceipt{}//&haiyaa.WelthInfo{}//谷歌提现解锁
   * 苹果发起支付
   * &haiyaa.TradePay{}//&haiyaa.PayOrder{}//苹果充值, 返回充值订单
   */
  APPLE_TRAEDE_PAY(3621),

  /**
   * 谷歌支付验签
   * &haiyaa.TradeReceipt{}//&haiyaa.WelthInfo{}//苹果充值, 返回充值后的用户资产信息
   */
  APPLE_CHECK_RECEIPT(3622),

  /**
   * 黑钻提现解锁
   * APPLE_DRAW_UNLOCK			= 3623; //&haiyaa.TradeReceipt{}//&haiyaa.WelthInfo{}//苹果提现解锁
   * 取消支付
   * &haiyaa.TradeCancel{}//&haiyaa.UtilRet{}//苹果/谷歌/三方 取消支付
   */
  CANCEL_TRADE(3630),

  /**
   * 黑钻兑换成黄钻
   * &haiyaa.TradeBCoin{}//&haiyaa.WelthInfo{}//黑钻兑换，ID = 兑换商品ID, 返回兑换后的用户资产信息
   */
  EXCHANGE_BCOIN(3631),

  /**
   * 黑钻提现申请
   * &haiyaa.TradeBCoin{}//&haiyaa.DrawOrder{}//黑钻体现申请，ID = 提现商品ID, 返回提现后的用户资产信息
   */
  WITHDRAW_APPLY(3641),

  /**
   * &haiyaa.TradeCancel{}//&haiyaa.UtilRet{}//黑钻取消提现
   */
  WITHDRAW_CANCEL(3644),

  /**
   * 黑钻提现审批
   * &haiyaa.DrawApprove{}//&haiyaa.WelthInfo{}//黑钻提现审批，ID = 提现商品ID, 返回提现后的用户资产信息
   */
  WITHDRAW_APPROVE(3642),

  /**
   * 三方变更
   * &haiyaa.SuperFundOper{}//&haiyaa.UtilRet{}//超管操作，
   */
  SUPER_FUND_OPER(3651);

  public static final ProtoAdapter<FundCmd> ADAPTER = new ProtoAdapter_FundCmd();

  private final int value;

  FundCmd(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static FundCmd fromValue(int value) {
    switch (value) {
      case 0: return FundCmd_Zero;
      case 3611: return GOOGLE_TRAEDE_PAY;
      case 3612: return GOOGLE_CHECK_RECEIPT;
      case 3621: return APPLE_TRAEDE_PAY;
      case 3622: return APPLE_CHECK_RECEIPT;
      case 3630: return CANCEL_TRADE;
      case 3631: return EXCHANGE_BCOIN;
      case 3641: return WITHDRAW_APPLY;
      case 3644: return WITHDRAW_CANCEL;
      case 3642: return WITHDRAW_APPROVE;
      case 3651: return SUPER_FUND_OPER;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_FundCmd extends EnumAdapter<FundCmd> {
    ProtoAdapter_FundCmd() {
      super(FundCmd.class, Syntax.PROTO_3, FundCmd.FundCmd_Zero);
    }

    @Override
    protected FundCmd fromValue(int value) {
      return FundCmd.fromValue(value);
    }
  }
}
