// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.FuzzySearchResult in user.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class FuzzySearchResult extends Message<FuzzySearchResult, FuzzySearchResult.Builder> {
  public static final ProtoAdapter<FuzzySearchResult> ADAPTER = new ProtoAdapter_FuzzySearchResult();

  private static final long serialVersionUID = 0L;

  public UserInfoS users;

  public FuzzySearchResult(UserInfoS users) {
    this(users, ByteString.EMPTY);
  }

  public FuzzySearchResult(UserInfoS users, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.users = users;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.users = users;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (users != null) builder.append(", users=").append(users);
    return builder.replace(0, 2, "FuzzySearchResult{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<FuzzySearchResult, Builder> {
    public UserInfoS users;

    public Builder() {
    }

    public Builder users(UserInfoS users) {
      this.users = users;
      return this;
    }

    @Override
    public FuzzySearchResult build() {
      return new FuzzySearchResult(users, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_FuzzySearchResult extends ProtoAdapter<FuzzySearchResult> {
    public ProtoAdapter_FuzzySearchResult() {
      super(FieldEncoding.LENGTH_DELIMITED, FuzzySearchResult.class, "type.googleapis.com/haiyaa.FuzzySearchResult", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(FuzzySearchResult value) {
      int result = 0;
      if (!Objects.equals(value.users, null)) {
        result += UserInfoS.ADAPTER.encodedSizeWithTag(1, value.users);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, FuzzySearchResult value) throws IOException {
      if (!Objects.equals(value.users, null)) UserInfoS.ADAPTER.encodeWithTag(writer, 1, value.users);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public FuzzySearchResult decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.users(UserInfoS.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public FuzzySearchResult redact(FuzzySearchResult value) {
      Builder builder = value.newBuilder();
      if (builder.users != null) builder.users = UserInfoS.ADAPTER.redact(builder.users);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
