// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.GameOperType in room.proto
package com.hao.proto;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * 被操作的类型
 */
public enum GameOperType implements WireEnum {
  /**
   * 未初始化
   */
  OT_UNKNOW(0),

  /**
   * 拉起游戏，首次拉起
   */
  OT_LUNCH_GAME(1),

  /**
   * 开始游戏，开始一局游戏
   */
  OT_START_GAME(2),

  /**
   * 结束游戏，结束当局游戏
   */
  OT_END_GAME(3),

  /**
   * 关闭游戏，回到直播模式
   */
  OT_CLOSE_GAME(4);

  public static final ProtoAdapter<GameOperType> ADAPTER = new ProtoAdapter_GameOperType();

  private final int value;

  GameOperType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static GameOperType fromValue(int value) {
    switch (value) {
      case 0: return OT_UNKNOW;
      case 1: return OT_LUNCH_GAME;
      case 2: return OT_START_GAME;
      case 3: return OT_END_GAME;
      case 4: return OT_CLOSE_GAME;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_GameOperType extends EnumAdapter<GameOperType> {
    ProtoAdapter_GameOperType() {
      super(GameOperType.class, Syntax.PROTO_3, GameOperType.OT_UNKNOW);
    }

    @Override
    protected GameOperType fromValue(int value) {
      return GameOperType.fromValue(value);
    }
  }
}
