// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.GameSUD in game.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 游戏频道频道列表
 */
public final class GameSUD extends Message<GameSUD, GameSUD.Builder> {
  public static final ProtoAdapter<GameSUD> ADAPTER = new ProtoAdapter_GameSUD();

  private static final long serialVersionUID = 0L;

  public String appId;

  public String appKey;

  public String sudCode;

  /**
   * 1表示测试环境， 0表示正式环境
   */
  public int sandbox;

  public GameSUD(String appId, String appKey, String sudCode, int sandbox) {
    this(appId, appKey, sudCode, sandbox, ByteString.EMPTY);
  }

  public GameSUD(String appId, String appKey, String sudCode, int sandbox,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (appId == null) {
      throw new IllegalArgumentException("appId == null");
    }
    this.appId = appId;
    if (appKey == null) {
      throw new IllegalArgumentException("appKey == null");
    }
    this.appKey = appKey;
    if (sudCode == null) {
      throw new IllegalArgumentException("sudCode == null");
    }
    this.sudCode = sudCode;
    this.sandbox = sandbox;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.appId = appId;
    builder.appKey = appKey;
    builder.sudCode = sudCode;
    builder.sandbox = sandbox;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (appId != null) builder.append(", appId=").append(Internal.sanitize(appId));
    if (appKey != null) builder.append(", appKey=").append(Internal.sanitize(appKey));
    if (sudCode != null) builder.append(", sudCode=").append(Internal.sanitize(sudCode));
    builder.append(", sandbox=").append(sandbox);
    return builder.replace(0, 2, "GameSUD{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GameSUD, Builder> {
    public String appId;

    public String appKey;

    public String sudCode;

    public int sandbox;

    public Builder() {
      appId = "";
      appKey = "";
      sudCode = "";
      sandbox = 0;
    }

    public Builder appId(String appId) {
      this.appId = appId;
      return this;
    }

    public Builder appKey(String appKey) {
      this.appKey = appKey;
      return this;
    }

    public Builder sudCode(String sudCode) {
      this.sudCode = sudCode;
      return this;
    }

    /**
     * 1表示测试环境， 0表示正式环境
     */
    public Builder sandbox(int sandbox) {
      this.sandbox = sandbox;
      return this;
    }

    @Override
    public GameSUD build() {
      return new GameSUD(appId, appKey, sudCode, sandbox, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GameSUD extends ProtoAdapter<GameSUD> {
    public ProtoAdapter_GameSUD() {
      super(FieldEncoding.LENGTH_DELIMITED, GameSUD.class, "type.googleapis.com/haiyaa.GameSUD", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(GameSUD value) {
      int result = 0;
      if (!Objects.equals(value.appId, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.appId);
      }
      if (!Objects.equals(value.appKey, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.appKey);
      }
      if (!Objects.equals(value.sudCode, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.sudCode);
      }
      if (!Objects.equals(value.sandbox, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(4, value.sandbox);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, GameSUD value) throws IOException {
      if (!Objects.equals(value.appId, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.appId);
      if (!Objects.equals(value.appKey, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.appKey);
      if (!Objects.equals(value.sudCode, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.sudCode);
      if (!Objects.equals(value.sandbox, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.sandbox);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GameSUD decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.appId(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.appKey(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.sudCode(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.sandbox(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public GameSUD redact(GameSUD value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
