// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.GetcfgGameChannelReq in haiyaa.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GetcfgGameChannelReq extends Message<GetcfgGameChannelReq, GetcfgGameChannelReq.Builder> {
  public static final ProtoAdapter<GetcfgGameChannelReq> ADAPTER = new ProtoAdapter_GetcfgGameChannelReq();

  private static final long serialVersionUID = 0L;

  public GetcfgGameChannelReq() {
    this(ByteString.EMPTY);
  }

  public GetcfgGameChannelReq(ByteString unknownFields) {
    super(ADAPTER, unknownFields);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    return builder.replace(0, 2, "GetcfgGameChannelReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetcfgGameChannelReq, Builder> {
    public Builder() {
    }

    @Override
    public GetcfgGameChannelReq build() {
      return new GetcfgGameChannelReq(super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetcfgGameChannelReq extends ProtoAdapter<GetcfgGameChannelReq> {
    public ProtoAdapter_GetcfgGameChannelReq() {
      super(FieldEncoding.LENGTH_DELIMITED, GetcfgGameChannelReq.class, "type.googleapis.com/haiyaa.GetcfgGameChannelReq", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(GetcfgGameChannelReq value) {
      int result = 0;
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, GetcfgGameChannelReq value) throws IOException {
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetcfgGameChannelReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public GetcfgGameChannelReq redact(GetcfgGameChannelReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
