// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.GetcfgRoomChannelRsp in haiyaa.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Objects;
import okio.ByteString;

public final class GetcfgRoomChannelRsp extends Message<GetcfgRoomChannelRsp, GetcfgRoomChannelRsp.Builder> {
  public static final ProtoAdapter<GetcfgRoomChannelRsp> ADAPTER = new ProtoAdapter_GetcfgRoomChannelRsp();

  private static final long serialVersionUID = 0L;

  public List<RoomChan> chans;

  /**
   * Room 优先显示的ChannelId
   */
  public int defaultChan;

  public GetcfgRoomChannelRsp(List<RoomChan> chans, int defaultChan) {
    this(chans, defaultChan, ByteString.EMPTY);
  }

  public GetcfgRoomChannelRsp(List<RoomChan> chans, int defaultChan, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.chans = Internal.immutableCopyOf("chans", chans);
    this.defaultChan = defaultChan;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.chans = Internal.copyOf(chans);
    builder.defaultChan = defaultChan;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!chans.isEmpty()) builder.append(", chans=").append(chans);
    builder.append(", defaultChan=").append(defaultChan);
    return builder.replace(0, 2, "GetcfgRoomChannelRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetcfgRoomChannelRsp, Builder> {
    public List<RoomChan> chans;

    public int defaultChan;

    public Builder() {
      chans = Internal.newMutableList();
      defaultChan = 0;
    }

    public Builder chans(List<RoomChan> chans) {
      Internal.checkElementsNotNull(chans);
      this.chans = chans;
      return this;
    }

    /**
     * Room 优先显示的ChannelId
     */
    public Builder defaultChan(int defaultChan) {
      this.defaultChan = defaultChan;
      return this;
    }

    @Override
    public GetcfgRoomChannelRsp build() {
      return new GetcfgRoomChannelRsp(chans, defaultChan, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetcfgRoomChannelRsp extends ProtoAdapter<GetcfgRoomChannelRsp> {
    public ProtoAdapter_GetcfgRoomChannelRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, GetcfgRoomChannelRsp.class, "type.googleapis.com/haiyaa.GetcfgRoomChannelRsp", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(GetcfgRoomChannelRsp value) {
      int result = 0;
      result += RoomChan.ADAPTER.asRepeated().encodedSizeWithTag(1, value.chans);
      if (!Objects.equals(value.defaultChan, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.defaultChan);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, GetcfgRoomChannelRsp value) throws IOException {
      RoomChan.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.chans);
      if (!Objects.equals(value.defaultChan, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.defaultChan);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetcfgRoomChannelRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.chans.add(RoomChan.ADAPTER.decode(reader)); break;
          case 2: builder.defaultChan(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public GetcfgRoomChannelRsp redact(GetcfgRoomChannelRsp value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.chans, RoomChan.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
