// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.GetcfgGameBannerReq in haiyaa.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GetcfgGameBannerReq extends Message<GetcfgGameBannerReq, GetcfgGameBannerReq.Builder> {
  public static final ProtoAdapter<GetcfgGameBannerReq> ADAPTER = new ProtoAdapter_GetcfgGameBannerReq();

  private static final long serialVersionUID = 0L;

  public GetcfgGameBannerReq() {
    this(ByteString.EMPTY);
  }

  public GetcfgGameBannerReq(ByteString unknownFields) {
    super(ADAPTER, unknownFields);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    return builder.replace(0, 2, "GetcfgGameBannerReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetcfgGameBannerReq, Builder> {
    public Builder() {
    }

    @Override
    public GetcfgGameBannerReq build() {
      return new GetcfgGameBannerReq(super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetcfgGameBannerReq extends ProtoAdapter<GetcfgGameBannerReq> {
    public ProtoAdapter_GetcfgGameBannerReq() {
      super(FieldEncoding.LENGTH_DELIMITED, GetcfgGameBannerReq.class, "type.googleapis.com/haiyaa.GetcfgGameBannerReq", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(GetcfgGameBannerReq value) {
      int result = 0;
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, GetcfgGameBannerReq value) throws IOException {
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetcfgGameBannerReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public GetcfgGameBannerReq redact(GetcfgGameBannerReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
