// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.GetcfgPayGoodsReq in haiyaa.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GetcfgPayGoodsReq extends Message<GetcfgPayGoodsReq, GetcfgPayGoodsReq.Builder> {
  public static final ProtoAdapter<GetcfgPayGoodsReq> ADAPTER = new ProtoAdapter_GetcfgPayGoodsReq();

  private static final long serialVersionUID = 0L;

  public GetcfgPayGoodsReq() {
    this(ByteString.EMPTY);
  }

  public GetcfgPayGoodsReq(ByteString unknownFields) {
    super(ADAPTER, unknownFields);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    return builder.replace(0, 2, "GetcfgPayGoodsReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetcfgPayGoodsReq, Builder> {
    public Builder() {
    }

    @Override
    public GetcfgPayGoodsReq build() {
      return new GetcfgPayGoodsReq(super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetcfgPayGoodsReq extends ProtoAdapter<GetcfgPayGoodsReq> {
    public ProtoAdapter_GetcfgPayGoodsReq() {
      super(FieldEncoding.LENGTH_DELIMITED, GetcfgPayGoodsReq.class, "type.googleapis.com/haiyaa.GetcfgPayGoodsReq", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(GetcfgPayGoodsReq value) {
      int result = 0;
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, GetcfgPayGoodsReq value) throws IOException {
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetcfgPayGoodsReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public GetcfgPayGoodsReq redact(GetcfgPayGoodsReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
