// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.GetcfgPayGoodsRsp in haiyaa.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Objects;
import okio.ByteString;

public final class GetcfgPayGoodsRsp extends Message<GetcfgPayGoodsRsp, GetcfgPayGoodsRsp.Builder> {
  public static final ProtoAdapter<GetcfgPayGoodsRsp> ADAPTER = new ProtoAdapter_GetcfgPayGoodsRsp();

  private static final long serialVersionUID = 0L;

  public List<PayProduct> Products;

  public PayProduct unlockProduct;

  public GetcfgPayGoodsRsp(List<PayProduct> Products, PayProduct unlockProduct) {
    this(Products, unlockProduct, ByteString.EMPTY);
  }

  public GetcfgPayGoodsRsp(List<PayProduct> Products, PayProduct unlockProduct,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.Products = Internal.immutableCopyOf("Products", Products);
    this.unlockProduct = unlockProduct;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.Products = Internal.copyOf(Products);
    builder.unlockProduct = unlockProduct;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!Products.isEmpty()) builder.append(", Products=").append(Products);
    if (unlockProduct != null) builder.append(", unlockProduct=").append(unlockProduct);
    return builder.replace(0, 2, "GetcfgPayGoodsRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetcfgPayGoodsRsp, Builder> {
    public List<PayProduct> Products;

    public PayProduct unlockProduct;

    public Builder() {
      Products = Internal.newMutableList();
    }

    public Builder Products(List<PayProduct> Products) {
      Internal.checkElementsNotNull(Products);
      this.Products = Products;
      return this;
    }

    public Builder unlockProduct(PayProduct unlockProduct) {
      this.unlockProduct = unlockProduct;
      return this;
    }

    @Override
    public GetcfgPayGoodsRsp build() {
      return new GetcfgPayGoodsRsp(Products, unlockProduct, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetcfgPayGoodsRsp extends ProtoAdapter<GetcfgPayGoodsRsp> {
    public ProtoAdapter_GetcfgPayGoodsRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, GetcfgPayGoodsRsp.class, "type.googleapis.com/haiyaa.GetcfgPayGoodsRsp", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(GetcfgPayGoodsRsp value) {
      int result = 0;
      result += PayProduct.ADAPTER.asRepeated().encodedSizeWithTag(1, value.Products);
      if (!Objects.equals(value.unlockProduct, null)) {
        result += PayProduct.ADAPTER.encodedSizeWithTag(2, value.unlockProduct);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, GetcfgPayGoodsRsp value) throws IOException {
      PayProduct.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.Products);
      if (!Objects.equals(value.unlockProduct, null)) PayProduct.ADAPTER.encodeWithTag(writer, 2, value.unlockProduct);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetcfgPayGoodsRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.Products.add(PayProduct.ADAPTER.decode(reader)); break;
          case 2: builder.unlockProduct(PayProduct.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public GetcfgPayGoodsRsp redact(GetcfgPayGoodsRsp value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.Products, PayProduct.ADAPTER);
      if (builder.unlockProduct != null) builder.unlockProduct = PayProduct.ADAPTER.redact(builder.unlockProduct);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
