// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.GetRecomGameRoomRsp in haiyaa.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class GetRecomGameRoomRsp extends Message<GetRecomGameRoomRsp, GetRecomGameRoomRsp.Builder> {
  public static final ProtoAdapter<GetRecomGameRoomRsp> ADAPTER = new ProtoAdapter_GetRecomGameRoomRsp();

  private static final long serialVersionUID = 0L;

  public List<GameItem> Games;

  public GetRecomGameRoomRsp(List<GameItem> Games) {
    this(Games, ByteString.EMPTY);
  }

  public GetRecomGameRoomRsp(List<GameItem> Games, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.Games = Internal.immutableCopyOf("Games", Games);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.Games = Internal.copyOf(Games);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!Games.isEmpty()) builder.append(", Games=").append(Games);
    return builder.replace(0, 2, "GetRecomGameRoomRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetRecomGameRoomRsp, Builder> {
    public List<GameItem> Games;

    public Builder() {
      Games = Internal.newMutableList();
    }

    public Builder Games(List<GameItem> Games) {
      Internal.checkElementsNotNull(Games);
      this.Games = Games;
      return this;
    }

    @Override
    public GetRecomGameRoomRsp build() {
      return new GetRecomGameRoomRsp(Games, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetRecomGameRoomRsp extends ProtoAdapter<GetRecomGameRoomRsp> {
    public ProtoAdapter_GetRecomGameRoomRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, GetRecomGameRoomRsp.class, "type.googleapis.com/haiyaa.GetRecomGameRoomRsp", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(GetRecomGameRoomRsp value) {
      int result = 0;
      result += GameItem.ADAPTER.asRepeated().encodedSizeWithTag(1, value.Games);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, GetRecomGameRoomRsp value) throws IOException {
      GameItem.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.Games);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetRecomGameRoomRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.Games.add(GameItem.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public GetRecomGameRoomRsp redact(GetRecomGameRoomRsp value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.Games, GameItem.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
