// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.GetUserAccessoriesRsp in haiyaa.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class GetUserAccessoriesRsp extends Message<GetUserAccessoriesRsp, GetUserAccessoriesRsp.Builder> {
  public static final ProtoAdapter<GetUserAccessoriesRsp> ADAPTER = new ProtoAdapter_GetUserAccessoriesRsp();

  private static final long serialVersionUID = 0L;

  public UserAcceS acces;

  public GetUserAccessoriesRsp(UserAcceS acces) {
    this(acces, ByteString.EMPTY);
  }

  public GetUserAccessoriesRsp(UserAcceS acces, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.acces = acces;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.acces = acces;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (acces != null) builder.append(", acces=").append(acces);
    return builder.replace(0, 2, "GetUserAccessoriesRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetUserAccessoriesRsp, Builder> {
    public UserAcceS acces;

    public Builder() {
    }

    public Builder acces(UserAcceS acces) {
      this.acces = acces;
      return this;
    }

    @Override
    public GetUserAccessoriesRsp build() {
      return new GetUserAccessoriesRsp(acces, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetUserAccessoriesRsp extends ProtoAdapter<GetUserAccessoriesRsp> {
    public ProtoAdapter_GetUserAccessoriesRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, GetUserAccessoriesRsp.class, "type.googleapis.com/haiyaa.GetUserAccessoriesRsp", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(GetUserAccessoriesRsp value) {
      int result = 0;
      if (!Objects.equals(value.acces, null)) {
        result += UserAcceS.ADAPTER.encodedSizeWithTag(1, value.acces);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, GetUserAccessoriesRsp value) throws IOException {
      if (!Objects.equals(value.acces, null)) UserAcceS.ADAPTER.encodeWithTag(writer, 1, value.acces);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetUserAccessoriesRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.acces(UserAcceS.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public GetUserAccessoriesRsp redact(GetUserAccessoriesRsp value) {
      Builder builder = value.newBuilder();
      if (builder.acces != null) builder.acces = UserAcceS.ADAPTER.redact(builder.acces);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
