// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.GetUserBaseRsp in haiyaa.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class GetUserBaseRsp extends Message<GetUserBaseRsp, GetUserBaseRsp.Builder> {
  public static final ProtoAdapter<GetUserBaseRsp> ADAPTER = new ProtoAdapter_GetUserBaseRsp();

  private static final long serialVersionUID = 0L;

  public UserBase head;

  public GetUserBaseRsp(UserBase head) {
    this(head, ByteString.EMPTY);
  }

  public GetUserBaseRsp(UserBase head, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.head = head;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.head = head;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (head != null) builder.append(", head=").append(head);
    return builder.replace(0, 2, "GetUserBaseRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetUserBaseRsp, Builder> {
    public UserBase head;

    public Builder() {
    }

    public Builder head(UserBase head) {
      this.head = head;
      return this;
    }

    @Override
    public GetUserBaseRsp build() {
      return new GetUserBaseRsp(head, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetUserBaseRsp extends ProtoAdapter<GetUserBaseRsp> {
    public ProtoAdapter_GetUserBaseRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, GetUserBaseRsp.class, "type.googleapis.com/haiyaa.GetUserBaseRsp", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(GetUserBaseRsp value) {
      int result = 0;
      if (!Objects.equals(value.head, null)) {
        result += UserBase.ADAPTER.encodedSizeWithTag(1, value.head);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, GetUserBaseRsp value) throws IOException {
      if (!Objects.equals(value.head, null)) UserBase.ADAPTER.encodeWithTag(writer, 1, value.head);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetUserBaseRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.head(UserBase.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public GetUserBaseRsp redact(GetUserBaseRsp value) {
      Builder builder = value.newBuilder();
      if (builder.head != null) builder.head = UserBase.ADAPTER.redact(builder.head);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
