// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.GiftRecordS in gift.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class GiftRecordS extends Message<GiftRecordS, GiftRecordS.Builder> {
  public static final ProtoAdapter<GiftRecordS> ADAPTER = new ProtoAdapter_GiftRecordS();

  private static final long serialVersionUID = 0L;

  /**
   * 送礼记录，或墙
   */
  public List<GiftRecord> Records;

  public GiftRecordS(List<GiftRecord> Records) {
    this(Records, ByteString.EMPTY);
  }

  public GiftRecordS(List<GiftRecord> Records, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.Records = Internal.immutableCopyOf("Records", Records);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.Records = Internal.copyOf(Records);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!Records.isEmpty()) builder.append(", Records=").append(Records);
    return builder.replace(0, 2, "GiftRecordS{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GiftRecordS, Builder> {
    public List<GiftRecord> Records;

    public Builder() {
      Records = Internal.newMutableList();
    }

    /**
     * 送礼记录，或墙
     */
    public Builder Records(List<GiftRecord> Records) {
      Internal.checkElementsNotNull(Records);
      this.Records = Records;
      return this;
    }

    @Override
    public GiftRecordS build() {
      return new GiftRecordS(Records, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GiftRecordS extends ProtoAdapter<GiftRecordS> {
    public ProtoAdapter_GiftRecordS() {
      super(FieldEncoding.LENGTH_DELIMITED, GiftRecordS.class, "type.googleapis.com/haiyaa.GiftRecordS", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(GiftRecordS value) {
      int result = 0;
      result += GiftRecord.ADAPTER.asRepeated().encodedSizeWithTag(1, value.Records);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, GiftRecordS value) throws IOException {
      GiftRecord.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.Records);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GiftRecordS decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.Records.add(GiftRecord.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public GiftRecordS redact(GiftRecordS value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.Records, GiftRecord.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
