// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.GiftRecord in gift.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class GiftRecord extends Message<GiftRecord, GiftRecord.Builder> {
  public static final ProtoAdapter<GiftRecord> ADAPTER = new ProtoAdapter_GiftRecord();

  private static final long serialVersionUID = 0L;

  /**
   * 礼物Id
   */
  public int giftId;

  /**
   * 礼物数量
   */
  public int giftNum;

  /**
   * 送礼时间
   */
  public long giftTime;

  /**
   * 描述信息，比如获得的理由
   */
  public String desc;

  /**
   * 礼物详情
   */
  public GiftInfo gInfo;

  /**
   * 送礼人头像，收礼列表里有，墙里不填
   */
  public UserBase sender;

  /**
   * 送礼人头像，收礼列表里有，墙里不填
   */
  public UserBase receiver;

  public GiftRecord(int giftId, int giftNum, long giftTime, String desc, GiftInfo gInfo,
      UserBase sender, UserBase receiver) {
    this(giftId, giftNum, giftTime, desc, gInfo, sender, receiver, ByteString.EMPTY);
  }

  public GiftRecord(int giftId, int giftNum, long giftTime, String desc, GiftInfo gInfo,
      UserBase sender, UserBase receiver, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.giftId = giftId;
    this.giftNum = giftNum;
    this.giftTime = giftTime;
    if (desc == null) {
      throw new IllegalArgumentException("desc == null");
    }
    this.desc = desc;
    this.gInfo = gInfo;
    this.sender = sender;
    this.receiver = receiver;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.giftId = giftId;
    builder.giftNum = giftNum;
    builder.giftTime = giftTime;
    builder.desc = desc;
    builder.gInfo = gInfo;
    builder.sender = sender;
    builder.receiver = receiver;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", giftId=").append(giftId);
    builder.append(", giftNum=").append(giftNum);
    builder.append(", giftTime=").append(giftTime);
    if (desc != null) builder.append(", desc=").append(Internal.sanitize(desc));
    if (gInfo != null) builder.append(", gInfo=").append(gInfo);
    if (sender != null) builder.append(", sender=").append(sender);
    if (receiver != null) builder.append(", receiver=").append(receiver);
    return builder.replace(0, 2, "GiftRecord{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GiftRecord, Builder> {
    public int giftId;

    public int giftNum;

    public long giftTime;

    public String desc;

    public GiftInfo gInfo;

    public UserBase sender;

    public UserBase receiver;

    public Builder() {
      giftId = 0;
      giftNum = 0;
      giftTime = 0L;
      desc = "";
    }

    /**
     * 礼物Id
     */
    public Builder giftId(int giftId) {
      this.giftId = giftId;
      return this;
    }

    /**
     * 礼物数量
     */
    public Builder giftNum(int giftNum) {
      this.giftNum = giftNum;
      return this;
    }

    /**
     * 送礼时间
     */
    public Builder giftTime(long giftTime) {
      this.giftTime = giftTime;
      return this;
    }

    /**
     * 描述信息，比如获得的理由
     */
    public Builder desc(String desc) {
      this.desc = desc;
      return this;
    }

    /**
     * 礼物详情
     */
    public Builder gInfo(GiftInfo gInfo) {
      this.gInfo = gInfo;
      return this;
    }

    /**
     * 送礼人头像，收礼列表里有，墙里不填
     */
    public Builder sender(UserBase sender) {
      this.sender = sender;
      return this;
    }

    /**
     * 送礼人头像，收礼列表里有，墙里不填
     */
    public Builder receiver(UserBase receiver) {
      this.receiver = receiver;
      return this;
    }

    @Override
    public GiftRecord build() {
      return new GiftRecord(giftId, giftNum, giftTime, desc, gInfo, sender, receiver, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GiftRecord extends ProtoAdapter<GiftRecord> {
    public ProtoAdapter_GiftRecord() {
      super(FieldEncoding.LENGTH_DELIMITED, GiftRecord.class, "type.googleapis.com/haiyaa.GiftRecord", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(GiftRecord value) {
      int result = 0;
      if (!Objects.equals(value.giftId, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(1, value.giftId);
      }
      if (!Objects.equals(value.giftNum, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.giftNum);
      }
      if (!Objects.equals(value.giftTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(3, value.giftTime);
      }
      if (!Objects.equals(value.desc, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(4, value.desc);
      }
      if (!Objects.equals(value.gInfo, null)) {
        result += GiftInfo.ADAPTER.encodedSizeWithTag(5, value.gInfo);
      }
      if (!Objects.equals(value.sender, null)) {
        result += UserBase.ADAPTER.encodedSizeWithTag(6, value.sender);
      }
      if (!Objects.equals(value.receiver, null)) {
        result += UserBase.ADAPTER.encodedSizeWithTag(7, value.receiver);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, GiftRecord value) throws IOException {
      if (!Objects.equals(value.giftId, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.giftId);
      if (!Objects.equals(value.giftNum, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.giftNum);
      if (!Objects.equals(value.giftTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 3, value.giftTime);
      if (!Objects.equals(value.desc, "")) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.desc);
      if (!Objects.equals(value.gInfo, null)) GiftInfo.ADAPTER.encodeWithTag(writer, 5, value.gInfo);
      if (!Objects.equals(value.sender, null)) UserBase.ADAPTER.encodeWithTag(writer, 6, value.sender);
      if (!Objects.equals(value.receiver, null)) UserBase.ADAPTER.encodeWithTag(writer, 7, value.receiver);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GiftRecord decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.giftId(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.giftNum(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.giftTime(ProtoAdapter.INT64.decode(reader)); break;
          case 4: builder.desc(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.gInfo(GiftInfo.ADAPTER.decode(reader)); break;
          case 6: builder.sender(UserBase.ADAPTER.decode(reader)); break;
          case 7: builder.receiver(UserBase.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public GiftRecord redact(GiftRecord value) {
      Builder builder = value.newBuilder();
      if (builder.gInfo != null) builder.gInfo = GiftInfo.ADAPTER.redact(builder.gInfo);
      if (builder.sender != null) builder.sender = UserBase.ADAPTER.redact(builder.sender);
      if (builder.receiver != null) builder.receiver = UserBase.ADAPTER.redact(builder.receiver);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
