// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.IdsQuery in public.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Objects;
import okio.ByteString;

public final class IdsQuery extends Message<IdsQuery, IdsQuery.Builder> {
  public static final ProtoAdapter<IdsQuery> ADAPTER = new ProtoAdapter_IdsQuery();

  private static final long serialVersionUID = 0L;

  /**
   * 查询的厂商，游戏，瞬间，评论等Id,具体根据Cmd
   */
  public List<Long> ids;

  /**
   * 查询类型
   */
  public int type;

  /**
   * 查询参数，必要时填写，如 UserInfoPart
   */
  public int parm;

  public IdsQuery(List<Long> ids, int type, int parm) {
    this(ids, type, parm, ByteString.EMPTY);
  }

  public IdsQuery(List<Long> ids, int type, int parm, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.ids = Internal.immutableCopyOf("ids", ids);
    this.type = type;
    this.parm = parm;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.ids = Internal.copyOf(ids);
    builder.type = type;
    builder.parm = parm;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!ids.isEmpty()) builder.append(", ids=").append(ids);
    builder.append(", type=").append(type);
    builder.append(", parm=").append(parm);
    return builder.replace(0, 2, "IdsQuery{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<IdsQuery, Builder> {
    public List<Long> ids;

    public int type;

    public int parm;

    public Builder() {
      ids = Internal.newMutableList();
      type = 0;
      parm = 0;
    }

    /**
     * 查询的厂商，游戏，瞬间，评论等Id,具体根据Cmd
     */
    public Builder ids(List<Long> ids) {
      Internal.checkElementsNotNull(ids);
      this.ids = ids;
      return this;
    }

    /**
     * 查询类型
     */
    public Builder type(int type) {
      this.type = type;
      return this;
    }

    /**
     * 查询参数，必要时填写，如 UserInfoPart
     */
    public Builder parm(int parm) {
      this.parm = parm;
      return this;
    }

    @Override
    public IdsQuery build() {
      return new IdsQuery(ids, type, parm, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_IdsQuery extends ProtoAdapter<IdsQuery> {
    public ProtoAdapter_IdsQuery() {
      super(FieldEncoding.LENGTH_DELIMITED, IdsQuery.class, "type.googleapis.com/haiyaa.IdsQuery", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(IdsQuery value) {
      int result = 0;
      result += ProtoAdapter.UINT64.asPacked().encodedSizeWithTag(1, value.ids);
      if (!Objects.equals(value.type, 0)) {
        result += ProtoAdapter.UINT32.encodedSizeWithTag(2, value.type);
      }
      if (!Objects.equals(value.parm, 0)) {
        result += ProtoAdapter.UINT32.encodedSizeWithTag(3, value.parm);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, IdsQuery value) throws IOException {
      ProtoAdapter.UINT64.asPacked().encodeWithTag(writer, 1, value.ids);
      if (!Objects.equals(value.type, 0)) ProtoAdapter.UINT32.encodeWithTag(writer, 2, value.type);
      if (!Objects.equals(value.parm, 0)) ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.parm);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public IdsQuery decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.ids.add(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.type(ProtoAdapter.UINT32.decode(reader)); break;
          case 3: builder.parm(ProtoAdapter.UINT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public IdsQuery redact(IdsQuery value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
