// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.LikeAction in public.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class LikeAction extends Message<LikeAction, LikeAction.Builder> {
  public static final ProtoAdapter<LikeAction> ADAPTER = new ProtoAdapter_LikeAction();

  private static final long serialVersionUID = 0L;

  /**
   * 动作 1：喜欢，2、不喜欢
   */
  public int like;

  /**
   * 操作类型,1动态， 2,评论 3 人
   */
  public int type;

  /**
   * 游戏、厂商、瞬间id，UserId
   */
  public long likedId;

  public LikeAction(int like, int type, long likedId) {
    this(like, type, likedId, ByteString.EMPTY);
  }

  public LikeAction(int like, int type, long likedId, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.like = like;
    this.type = type;
    this.likedId = likedId;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.like = like;
    builder.type = type;
    builder.likedId = likedId;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", like=").append(like);
    builder.append(", type=").append(type);
    builder.append(", likedId=").append(likedId);
    return builder.replace(0, 2, "LikeAction{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<LikeAction, Builder> {
    public int like;

    public int type;

    public long likedId;

    public Builder() {
      like = 0;
      type = 0;
      likedId = 0L;
    }

    /**
     * 动作 1：喜欢，2、不喜欢
     */
    public Builder like(int like) {
      this.like = like;
      return this;
    }

    /**
     * 操作类型,1动态， 2,评论 3 人
     */
    public Builder type(int type) {
      this.type = type;
      return this;
    }

    /**
     * 游戏、厂商、瞬间id，UserId
     */
    public Builder likedId(long likedId) {
      this.likedId = likedId;
      return this;
    }

    @Override
    public LikeAction build() {
      return new LikeAction(like, type, likedId, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_LikeAction extends ProtoAdapter<LikeAction> {
    public ProtoAdapter_LikeAction() {
      super(FieldEncoding.LENGTH_DELIMITED, LikeAction.class, "type.googleapis.com/haiyaa.LikeAction", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(LikeAction value) {
      int result = 0;
      if (!Objects.equals(value.like, 0)) {
        result += ProtoAdapter.UINT32.encodedSizeWithTag(1, value.like);
      }
      if (!Objects.equals(value.type, 0)) {
        result += ProtoAdapter.UINT32.encodedSizeWithTag(2, value.type);
      }
      if (!Objects.equals(value.likedId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(3, value.likedId);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, LikeAction value) throws IOException {
      if (!Objects.equals(value.like, 0)) ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.like);
      if (!Objects.equals(value.type, 0)) ProtoAdapter.UINT32.encodeWithTag(writer, 2, value.type);
      if (!Objects.equals(value.likedId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 3, value.likedId);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public LikeAction decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.like(ProtoAdapter.UINT32.decode(reader)); break;
          case 2: builder.type(ProtoAdapter.UINT32.decode(reader)); break;
          case 3: builder.likedId(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public LikeAction redact(LikeAction value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
