// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.LinkText in public.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Objects;
import okio.ByteString;

/**
 * 链接文本
 */
public final class LinkText extends Message<LinkText, LinkText.Builder> {
  public static final ProtoAdapter<LinkText> ADAPTER = new ProtoAdapter_LinkText();

  private static final long serialVersionUID = 0L;

  public List<Node> list;

  public LinkText(List<Node> list) {
    this(list, ByteString.EMPTY);
  }

  public LinkText(List<Node> list, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.list = Internal.immutableCopyOf("list", list);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.list = Internal.copyOf(list);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!list.isEmpty()) builder.append(", list=").append(list);
    return builder.replace(0, 2, "LinkText{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<LinkText, Builder> {
    public List<Node> list;

    public Builder() {
      list = Internal.newMutableList();
    }

    public Builder list(List<Node> list) {
      Internal.checkElementsNotNull(list);
      this.list = list;
      return this;
    }

    @Override
    public LinkText build() {
      return new LinkText(list, super.buildUnknownFields());
    }
  }

  public static final class Node extends Message<Node, Node.Builder> {
    public static final ProtoAdapter<Node> ADAPTER = new ProtoAdapter_Node();

    private static final long serialVersionUID = 0L;

    /**
     * 文本内容
     */
    public String text;

    /**
     * 文本颜色
     */
    public String color;

    /**
     * 1：纯文本，2：用户id
     */
    public int textType;

    /**
     * uint64 id     = 4; // 跳转id = roomid
     * 跳转进房或跳URL
     */
    public String jumpUrl;

    public Node(String text, String color, int textType, String jumpUrl) {
      this(text, color, textType, jumpUrl, ByteString.EMPTY);
    }

    public Node(String text, String color, int textType, String jumpUrl, ByteString unknownFields) {
      super(ADAPTER, unknownFields);
      if (text == null) {
        throw new IllegalArgumentException("text == null");
      }
      this.text = text;
      if (color == null) {
        throw new IllegalArgumentException("color == null");
      }
      this.color = color;
      this.textType = textType;
      if (jumpUrl == null) {
        throw new IllegalArgumentException("jumpUrl == null");
      }
      this.jumpUrl = jumpUrl;
    }

    @Override
    public Builder newBuilder() {
      Builder builder = new Builder();
      builder.text = text;
      builder.color = color;
      builder.textType = textType;
      builder.jumpUrl = jumpUrl;
      builder.addUnknownFields(unknownFields());
      return builder;
    }

    @Override
    public String toString() {
      StringBuilder builder = new StringBuilder();
      if (text != null) builder.append(", text=").append(Internal.sanitize(text));
      if (color != null) builder.append(", color=").append(Internal.sanitize(color));
      builder.append(", textType=").append(textType);
      if (jumpUrl != null) builder.append(", jumpUrl=").append(Internal.sanitize(jumpUrl));
      return builder.replace(0, 2, "Node{").append('}').toString();
    }

    public static final class Builder extends Message.Builder<Node, Builder> {
      public String text;

      public String color;

      public int textType;

      public String jumpUrl;

      public Builder() {
        text = "";
        color = "";
        textType = 0;
        jumpUrl = "";
      }

      /**
       * 文本内容
       */
      public Builder text(String text) {
        this.text = text;
        return this;
      }

      /**
       * 文本颜色
       */
      public Builder color(String color) {
        this.color = color;
        return this;
      }

      /**
       * 1：纯文本，2：用户id
       */
      public Builder textType(int textType) {
        this.textType = textType;
        return this;
      }

      /**
       * uint64 id     = 4; // 跳转id = roomid
       * 跳转进房或跳URL
       */
      public Builder jumpUrl(String jumpUrl) {
        this.jumpUrl = jumpUrl;
        return this;
      }

      @Override
      public Node build() {
        return new Node(text, color, textType, jumpUrl, super.buildUnknownFields());
      }
    }

    private static final class ProtoAdapter_Node extends ProtoAdapter<Node> {
      public ProtoAdapter_Node() {
        super(FieldEncoding.LENGTH_DELIMITED, Node.class, "type.googleapis.com/haiyaa.LinkText.Node", Syntax.PROTO_3, null);
      }

      @Override
      public int encodedSize(Node value) {
        int result = 0;
        if (!Objects.equals(value.text, "")) {
          result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.text);
        }
        if (!Objects.equals(value.color, "")) {
          result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.color);
        }
        if (!Objects.equals(value.textType, 0)) {
          result += ProtoAdapter.INT32.encodedSizeWithTag(3, value.textType);
        }
        if (!Objects.equals(value.jumpUrl, "")) {
          result += ProtoAdapter.STRING.encodedSizeWithTag(5, value.jumpUrl);
        }
        result += value.unknownFields().size();
        return result;
      }

      @Override
      public void encode(ProtoWriter writer, Node value) throws IOException {
        if (!Objects.equals(value.text, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.text);
        if (!Objects.equals(value.color, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.color);
        if (!Objects.equals(value.textType, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.textType);
        if (!Objects.equals(value.jumpUrl, "")) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.jumpUrl);
        writer.writeBytes(value.unknownFields());
      }

      @Override
      public Node decode(ProtoReader reader) throws IOException {
        Builder builder = new Builder();
        long token = reader.beginMessage();
        for (int tag; (tag = reader.nextTag()) != -1;) {
          switch (tag) {
            case 1: builder.text(ProtoAdapter.STRING.decode(reader)); break;
            case 2: builder.color(ProtoAdapter.STRING.decode(reader)); break;
            case 3: builder.textType(ProtoAdapter.INT32.decode(reader)); break;
            case 5: builder.jumpUrl(ProtoAdapter.STRING.decode(reader)); break;
            default: {
              reader.readUnknownField(tag);
            }
          }
        }
        builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
        return builder.build();
      }

      @Override
      public Node redact(Node value) {
        Builder builder = value.newBuilder();
        builder.clearUnknownFields();
        return builder.build();
      }
    }
  }

  private static final class ProtoAdapter_LinkText extends ProtoAdapter<LinkText> {
    public ProtoAdapter_LinkText() {
      super(FieldEncoding.LENGTH_DELIMITED, LinkText.class, "type.googleapis.com/haiyaa.LinkText", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(LinkText value) {
      int result = 0;
      result += Node.ADAPTER.asRepeated().encodedSizeWithTag(4, value.list);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, LinkText value) throws IOException {
      Node.ADAPTER.asRepeated().encodeWithTag(writer, 4, value.list);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public LinkText decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 4: builder.list.add(Node.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public LinkText redact(LinkText value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.list, Node.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
