// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.LoginType in login.proto
package com.hao.proto;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * 1、通过什么方式登录
 */
public enum LoginType implements WireEnum {
  AT_Zero(0),

  /**
   * 设备登录账号
   */
  AT_Device(1),

  /**
   * 手机登录账号
   */
  AT_Phone(2),

  /**
   * 邮箱登录账号
   */
  AT_Email(3),

  /**
   * 球球账号登录
   */
  AT_BoB(4),

  /**
   * QQ登录
   */
  AT_QQ(5),

  /**
   * 微信登录
   */
  AT_WeChat(6),

  /**
   * 苹果账号
   */
  AT_Apple(7),

  /**
   * 谷歌登录账号
   */
  AT_Google(8),

  /**
   * Face登录账号
   */
  AT_FaceBook(9);

  public static final ProtoAdapter<LoginType> ADAPTER = new ProtoAdapter_LoginType();

  private final int value;

  LoginType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static LoginType fromValue(int value) {
    switch (value) {
      case 0: return AT_Zero;
      case 1: return AT_Device;
      case 2: return AT_Phone;
      case 3: return AT_Email;
      case 4: return AT_BoB;
      case 5: return AT_QQ;
      case 6: return AT_WeChat;
      case 7: return AT_Apple;
      case 8: return AT_Google;
      case 9: return AT_FaceBook;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_LoginType extends EnumAdapter<LoginType> {
    ProtoAdapter_LoginType() {
      super(LoginType.class, Syntax.PROTO_3, LoginType.AT_Zero);
    }

    @Override
    protected LoginType fromValue(int value) {
      return LoginType.fromValue(value);
    }
  }
}
