// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.LoginInfo in login.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class LoginInfo extends Message<LoginInfo, LoginInfo.Builder> {
  public static final ProtoAdapter<LoginInfo> ADAPTER = new ProtoAdapter_LoginInfo();

  private static final long serialVersionUID = 0L;

  /**
   * 用户信息
   */
  public UserInfo user;

  /**
   * 每次登陆会刷新Token，保留14天
   */
  public String tokenId;

  /**
   * 长连接地址返回，每次登陆后会返回
   */
  public String gateAddr;

  /**
   * 上传地址
   */
  public String uploadAddr;

  /**
   * 如果返回短地址，APP自动补齐前缀
   */
  public String sourceAddr;

  /**
   * 语音SDK
   */
  public SDKInfo sdkinfo;

  public LoginInfo(UserInfo user, String tokenId, String gateAddr, String uploadAddr,
      String sourceAddr, SDKInfo sdkinfo) {
    this(user, tokenId, gateAddr, uploadAddr, sourceAddr, sdkinfo, ByteString.EMPTY);
  }

  public LoginInfo(UserInfo user, String tokenId, String gateAddr, String uploadAddr,
      String sourceAddr, SDKInfo sdkinfo, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.user = user;
    if (tokenId == null) {
      throw new IllegalArgumentException("tokenId == null");
    }
    this.tokenId = tokenId;
    if (gateAddr == null) {
      throw new IllegalArgumentException("gateAddr == null");
    }
    this.gateAddr = gateAddr;
    if (uploadAddr == null) {
      throw new IllegalArgumentException("uploadAddr == null");
    }
    this.uploadAddr = uploadAddr;
    if (sourceAddr == null) {
      throw new IllegalArgumentException("sourceAddr == null");
    }
    this.sourceAddr = sourceAddr;
    this.sdkinfo = sdkinfo;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.user = user;
    builder.tokenId = tokenId;
    builder.gateAddr = gateAddr;
    builder.uploadAddr = uploadAddr;
    builder.sourceAddr = sourceAddr;
    builder.sdkinfo = sdkinfo;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (user != null) builder.append(", user=").append(user);
    if (tokenId != null) builder.append(", tokenId=").append(Internal.sanitize(tokenId));
    if (gateAddr != null) builder.append(", gateAddr=").append(Internal.sanitize(gateAddr));
    if (uploadAddr != null) builder.append(", uploadAddr=").append(Internal.sanitize(uploadAddr));
    if (sourceAddr != null) builder.append(", sourceAddr=").append(Internal.sanitize(sourceAddr));
    if (sdkinfo != null) builder.append(", sdkinfo=").append(sdkinfo);
    return builder.replace(0, 2, "LoginInfo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<LoginInfo, Builder> {
    public UserInfo user;

    public String tokenId;

    public String gateAddr;

    public String uploadAddr;

    public String sourceAddr;

    public SDKInfo sdkinfo;

    public Builder() {
      tokenId = "";
      gateAddr = "";
      uploadAddr = "";
      sourceAddr = "";
    }

    /**
     * 用户信息
     */
    public Builder user(UserInfo user) {
      this.user = user;
      return this;
    }

    /**
     * 每次登陆会刷新Token，保留14天
     */
    public Builder tokenId(String tokenId) {
      this.tokenId = tokenId;
      return this;
    }

    /**
     * 长连接地址返回，每次登陆后会返回
     */
    public Builder gateAddr(String gateAddr) {
      this.gateAddr = gateAddr;
      return this;
    }

    /**
     * 上传地址
     */
    public Builder uploadAddr(String uploadAddr) {
      this.uploadAddr = uploadAddr;
      return this;
    }

    /**
     * 如果返回短地址，APP自动补齐前缀
     */
    public Builder sourceAddr(String sourceAddr) {
      this.sourceAddr = sourceAddr;
      return this;
    }

    /**
     * 语音SDK
     */
    public Builder sdkinfo(SDKInfo sdkinfo) {
      this.sdkinfo = sdkinfo;
      return this;
    }

    @Override
    public LoginInfo build() {
      return new LoginInfo(user, tokenId, gateAddr, uploadAddr, sourceAddr, sdkinfo, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_LoginInfo extends ProtoAdapter<LoginInfo> {
    public ProtoAdapter_LoginInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, LoginInfo.class, "type.googleapis.com/haiyaa.LoginInfo", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(LoginInfo value) {
      int result = 0;
      if (!Objects.equals(value.user, null)) {
        result += UserInfo.ADAPTER.encodedSizeWithTag(1, value.user);
      }
      if (!Objects.equals(value.tokenId, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.tokenId);
      }
      if (!Objects.equals(value.gateAddr, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.gateAddr);
      }
      if (!Objects.equals(value.uploadAddr, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(4, value.uploadAddr);
      }
      if (!Objects.equals(value.sourceAddr, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(5, value.sourceAddr);
      }
      if (!Objects.equals(value.sdkinfo, null)) {
        result += SDKInfo.ADAPTER.encodedSizeWithTag(6, value.sdkinfo);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, LoginInfo value) throws IOException {
      if (!Objects.equals(value.user, null)) UserInfo.ADAPTER.encodeWithTag(writer, 1, value.user);
      if (!Objects.equals(value.tokenId, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.tokenId);
      if (!Objects.equals(value.gateAddr, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.gateAddr);
      if (!Objects.equals(value.uploadAddr, "")) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.uploadAddr);
      if (!Objects.equals(value.sourceAddr, "")) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.sourceAddr);
      if (!Objects.equals(value.sdkinfo, null)) SDKInfo.ADAPTER.encodeWithTag(writer, 6, value.sdkinfo);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public LoginInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.user(UserInfo.ADAPTER.decode(reader)); break;
          case 2: builder.tokenId(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.gateAddr(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.uploadAddr(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.sourceAddr(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.sdkinfo(SDKInfo.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public LoginInfo redact(LoginInfo value) {
      Builder builder = value.newBuilder();
      if (builder.user != null) builder.user = UserInfo.ADAPTER.redact(builder.user);
      if (builder.sdkinfo != null) builder.sdkinfo = SDKInfo.ADAPTER.redact(builder.sdkinfo);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
