// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.LongProto in public.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class LongProto extends Message<LongProto, LongProto.Builder> {
  public static final ProtoAdapter<LongProto> ADAPTER = new ProtoAdapter_LongProto();

  private static final long serialVersionUID = 0L;

  /**
   * 查询参数
   */
  public long Value;

  public LongProto(long Value) {
    this(Value, ByteString.EMPTY);
  }

  public LongProto(long Value, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.Value = Value;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.Value = Value;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", Value=").append(Value);
    return builder.replace(0, 2, "LongProto{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<LongProto, Builder> {
    public long Value;

    public Builder() {
      Value = 0L;
    }

    /**
     * 查询参数
     */
    public Builder Value(long Value) {
      this.Value = Value;
      return this;
    }

    @Override
    public LongProto build() {
      return new LongProto(Value, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_LongProto extends ProtoAdapter<LongProto> {
    public ProtoAdapter_LongProto() {
      super(FieldEncoding.LENGTH_DELIMITED, LongProto.class, "type.googleapis.com/haiyaa.LongProto", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(LongProto value) {
      int result = 0;
      if (!Objects.equals(value.Value, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.Value);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, LongProto value) throws IOException {
      if (!Objects.equals(value.Value, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.Value);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public LongProto decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.Value(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public LongProto redact(LongProto value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
