// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.LoveStatus in user.proto
package com.hao.proto;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum LoveStatus implements WireEnum {
  LS_Zero(0),

  /**
   * 已发出，待回应
   */
  LS_NEED_ACK(1),

  /**
   * 已同意
   */
  LS_IN_LOVE(2),

  /**
   * 已过期，超时未回应
   */
  LS_OVERDUE(3),

  /**
   * 已拒绝
   */
  LS_REJECT(4),

  /**
   * 已分手
   */
  LS_APART(5);

  public static final ProtoAdapter<LoveStatus> ADAPTER = new ProtoAdapter_LoveStatus();

  private final int value;

  LoveStatus(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static LoveStatus fromValue(int value) {
    switch (value) {
      case 0: return LS_Zero;
      case 1: return LS_NEED_ACK;
      case 2: return LS_IN_LOVE;
      case 3: return LS_OVERDUE;
      case 4: return LS_REJECT;
      case 5: return LS_APART;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_LoveStatus extends EnumAdapter<LoveStatus> {
    ProtoAdapter_LoveStatus() {
      super(LoveStatus.class, Syntax.PROTO_3, LoveStatus.LS_Zero);
    }

    @Override
    protected LoveStatus fromValue(int value) {
      return LoveStatus.fromValue(value);
    }
  }
}
