// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.MgrOperGame in room.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 操控游戏
 */
public final class MgrOperGame extends Message<MgrOperGame, MgrOperGame.Builder> {
  public static final ProtoAdapter<MgrOperGame> ADAPTER = new ProtoAdapter_MgrOperGame();

  private static final long serialVersionUID = 0L;

  /**
   * 操作类型 GameOperType
   */
  public int optype;

  /**
   * 操作对应的房间
   */
  public long roomId;

  /**
   * 对应的游戏
   */
  public long gameId;

  public MgrOperGame(int optype, long roomId, long gameId) {
    this(optype, roomId, gameId, ByteString.EMPTY);
  }

  public MgrOperGame(int optype, long roomId, long gameId, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.optype = optype;
    this.roomId = roomId;
    this.gameId = gameId;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.optype = optype;
    builder.roomId = roomId;
    builder.gameId = gameId;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", optype=").append(optype);
    builder.append(", roomId=").append(roomId);
    builder.append(", gameId=").append(gameId);
    return builder.replace(0, 2, "MgrOperGame{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<MgrOperGame, Builder> {
    public int optype;

    public long roomId;

    public long gameId;

    public Builder() {
      optype = 0;
      roomId = 0L;
      gameId = 0L;
    }

    /**
     * 操作类型 GameOperType
     */
    public Builder optype(int optype) {
      this.optype = optype;
      return this;
    }

    /**
     * 操作对应的房间
     */
    public Builder roomId(long roomId) {
      this.roomId = roomId;
      return this;
    }

    /**
     * 对应的游戏
     */
    public Builder gameId(long gameId) {
      this.gameId = gameId;
      return this;
    }

    @Override
    public MgrOperGame build() {
      return new MgrOperGame(optype, roomId, gameId, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_MgrOperGame extends ProtoAdapter<MgrOperGame> {
    public ProtoAdapter_MgrOperGame() {
      super(FieldEncoding.LENGTH_DELIMITED, MgrOperGame.class, "type.googleapis.com/haiyaa.MgrOperGame", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(MgrOperGame value) {
      int result = 0;
      if (!Objects.equals(value.optype, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(1, value.optype);
      }
      if (!Objects.equals(value.roomId, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(2, value.roomId);
      }
      if (!Objects.equals(value.gameId, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(3, value.gameId);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, MgrOperGame value) throws IOException {
      if (!Objects.equals(value.optype, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.optype);
      if (!Objects.equals(value.roomId, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 2, value.roomId);
      if (!Objects.equals(value.gameId, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 3, value.gameId);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public MgrOperGame decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.optype(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.roomId(ProtoAdapter.INT64.decode(reader)); break;
          case 3: builder.gameId(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public MgrOperGame redact(MgrOperGame value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
