// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.MicroFace in room.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 房间中的麦上表情
 */
public final class MicroFace extends Message<MicroFace, MicroFace.Builder> {
  public static final ProtoAdapter<MicroFace> ADAPTER = new ProtoAdapter_MicroFace();

  private static final long serialVersionUID = 0L;

  /**
   * 房间Id
   */
  public long roomId;

  /**
   * 用户id
   */
  public long userId;

  /**
   * 表情id
   */
  public int faceId;

  /**
   * 麦位Id
   */
  public int micoId;

  public MicroFace(long roomId, long userId, int faceId, int micoId) {
    this(roomId, userId, faceId, micoId, ByteString.EMPTY);
  }

  public MicroFace(long roomId, long userId, int faceId, int micoId, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.roomId = roomId;
    this.userId = userId;
    this.faceId = faceId;
    this.micoId = micoId;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.roomId = roomId;
    builder.userId = userId;
    builder.faceId = faceId;
    builder.micoId = micoId;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", roomId=").append(roomId);
    builder.append(", userId=").append(userId);
    builder.append(", faceId=").append(faceId);
    builder.append(", micoId=").append(micoId);
    return builder.replace(0, 2, "MicroFace{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<MicroFace, Builder> {
    public long roomId;

    public long userId;

    public int faceId;

    public int micoId;

    public Builder() {
      roomId = 0L;
      userId = 0L;
      faceId = 0;
      micoId = 0;
    }

    /**
     * 房间Id
     */
    public Builder roomId(long roomId) {
      this.roomId = roomId;
      return this;
    }

    /**
     * 用户id
     */
    public Builder userId(long userId) {
      this.userId = userId;
      return this;
    }

    /**
     * 表情id
     */
    public Builder faceId(int faceId) {
      this.faceId = faceId;
      return this;
    }

    /**
     * 麦位Id
     */
    public Builder micoId(int micoId) {
      this.micoId = micoId;
      return this;
    }

    @Override
    public MicroFace build() {
      return new MicroFace(roomId, userId, faceId, micoId, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_MicroFace extends ProtoAdapter<MicroFace> {
    public ProtoAdapter_MicroFace() {
      super(FieldEncoding.LENGTH_DELIMITED, MicroFace.class, "type.googleapis.com/haiyaa.MicroFace", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(MicroFace value) {
      int result = 0;
      if (!Objects.equals(value.roomId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.roomId);
      }
      if (!Objects.equals(value.userId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(2, value.userId);
      }
      if (!Objects.equals(value.faceId, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(3, value.faceId);
      }
      if (!Objects.equals(value.micoId, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(4, value.micoId);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, MicroFace value) throws IOException {
      if (!Objects.equals(value.roomId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.roomId);
      if (!Objects.equals(value.userId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.userId);
      if (!Objects.equals(value.faceId, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.faceId);
      if (!Objects.equals(value.micoId, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.micoId);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public MicroFace decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.roomId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.userId(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.faceId(ProtoAdapter.INT32.decode(reader)); break;
          case 4: builder.micoId(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public MicroFace redact(MicroFace value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
