// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.MicroChange in room.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Objects;
import okio.ByteString;

public final class MicroChange extends Message<MicroChange, MicroChange.Builder> {
  public static final ProtoAdapter<MicroChange> ADAPTER = new ProtoAdapter_MicroChange();

  private static final long serialVersionUID = 0L;

  /**
   * 变化类型
   */
  public int ctype;

  /**
   * 麦位序列号
   */
  public long serialno;

  /**
   * 变化前一麦位信息，ChangeOne，不刷新area, seat 可能为0， 表示没有原位置
   */
  public RoomMicro old;

  /**
   * 变化后一麦位信息，一定有area, seat, state 不一定有人，如果是封闭麦的情况，上麦才有人
   */
  public RoomMicro cur;

  /**
   * 操作者信息
   */
  public RoomMicro oper;

  /**
   * 操作后全新的麦位信息，端上刷新即可
   */
  public List<RoomMicro> micros;

  public MicroChange(int ctype, long serialno, RoomMicro old, RoomMicro cur, RoomMicro oper,
      List<RoomMicro> micros) {
    this(ctype, serialno, old, cur, oper, micros, ByteString.EMPTY);
  }

  public MicroChange(int ctype, long serialno, RoomMicro old, RoomMicro cur, RoomMicro oper,
      List<RoomMicro> micros, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.ctype = ctype;
    this.serialno = serialno;
    this.old = old;
    this.cur = cur;
    this.oper = oper;
    this.micros = Internal.immutableCopyOf("micros", micros);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.ctype = ctype;
    builder.serialno = serialno;
    builder.old = old;
    builder.cur = cur;
    builder.oper = oper;
    builder.micros = Internal.copyOf(micros);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", ctype=").append(ctype);
    builder.append(", serialno=").append(serialno);
    if (old != null) builder.append(", old=").append(old);
    if (cur != null) builder.append(", cur=").append(cur);
    if (oper != null) builder.append(", oper=").append(oper);
    if (!micros.isEmpty()) builder.append(", micros=").append(micros);
    return builder.replace(0, 2, "MicroChange{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<MicroChange, Builder> {
    public int ctype;

    public long serialno;

    public RoomMicro old;

    public RoomMicro cur;

    public RoomMicro oper;

    public List<RoomMicro> micros;

    public Builder() {
      ctype = 0;
      serialno = 0L;
      micros = Internal.newMutableList();
    }

    /**
     * 变化类型
     */
    public Builder ctype(int ctype) {
      this.ctype = ctype;
      return this;
    }

    /**
     * 麦位序列号
     */
    public Builder serialno(long serialno) {
      this.serialno = serialno;
      return this;
    }

    /**
     * 变化前一麦位信息，ChangeOne，不刷新area, seat 可能为0， 表示没有原位置
     */
    public Builder old(RoomMicro old) {
      this.old = old;
      return this;
    }

    /**
     * 变化后一麦位信息，一定有area, seat, state 不一定有人，如果是封闭麦的情况，上麦才有人
     */
    public Builder cur(RoomMicro cur) {
      this.cur = cur;
      return this;
    }

    /**
     * 操作者信息
     */
    public Builder oper(RoomMicro oper) {
      this.oper = oper;
      return this;
    }

    /**
     * 操作后全新的麦位信息，端上刷新即可
     */
    public Builder micros(List<RoomMicro> micros) {
      Internal.checkElementsNotNull(micros);
      this.micros = micros;
      return this;
    }

    @Override
    public MicroChange build() {
      return new MicroChange(ctype, serialno, old, cur, oper, micros, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_MicroChange extends ProtoAdapter<MicroChange> {
    public ProtoAdapter_MicroChange() {
      super(FieldEncoding.LENGTH_DELIMITED, MicroChange.class, "type.googleapis.com/haiyaa.MicroChange", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(MicroChange value) {
      int result = 0;
      if (!Objects.equals(value.ctype, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(1, value.ctype);
      }
      if (!Objects.equals(value.serialno, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(2, value.serialno);
      }
      if (!Objects.equals(value.old, null)) {
        result += RoomMicro.ADAPTER.encodedSizeWithTag(3, value.old);
      }
      if (!Objects.equals(value.cur, null)) {
        result += RoomMicro.ADAPTER.encodedSizeWithTag(4, value.cur);
      }
      if (!Objects.equals(value.oper, null)) {
        result += RoomMicro.ADAPTER.encodedSizeWithTag(5, value.oper);
      }
      result += RoomMicro.ADAPTER.asRepeated().encodedSizeWithTag(6, value.micros);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, MicroChange value) throws IOException {
      if (!Objects.equals(value.ctype, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.ctype);
      if (!Objects.equals(value.serialno, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 2, value.serialno);
      if (!Objects.equals(value.old, null)) RoomMicro.ADAPTER.encodeWithTag(writer, 3, value.old);
      if (!Objects.equals(value.cur, null)) RoomMicro.ADAPTER.encodeWithTag(writer, 4, value.cur);
      if (!Objects.equals(value.oper, null)) RoomMicro.ADAPTER.encodeWithTag(writer, 5, value.oper);
      RoomMicro.ADAPTER.asRepeated().encodeWithTag(writer, 6, value.micros);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public MicroChange decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.ctype(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.serialno(ProtoAdapter.INT64.decode(reader)); break;
          case 3: builder.old(RoomMicro.ADAPTER.decode(reader)); break;
          case 4: builder.cur(RoomMicro.ADAPTER.decode(reader)); break;
          case 5: builder.oper(RoomMicro.ADAPTER.decode(reader)); break;
          case 6: builder.micros.add(RoomMicro.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public MicroChange redact(MicroChange value) {
      Builder builder = value.newBuilder();
      if (builder.old != null) builder.old = RoomMicro.ADAPTER.redact(builder.old);
      if (builder.cur != null) builder.cur = RoomMicro.ADAPTER.redact(builder.cur);
      if (builder.oper != null) builder.oper = RoomMicro.ADAPTER.redact(builder.oper);
      Internal.redactElements(builder.micros, RoomMicro.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
