// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.MicroState in room.proto
package com.hao.proto;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum MicroState implements WireEnum {
  /**
   * 未初始化，默认为开麦状态
   */
  MS_UNDEFINE(0),

  /**
   * 麦状态，开麦
   */
  MS_OPENING(1),

  /**
   * 麦状态，静音，关闭
   */
  MS_SLIENCE(2),

  /**
   * 麦状态，封麦
   */
  MS_CLOSED(3);

  public static final ProtoAdapter<MicroState> ADAPTER = new ProtoAdapter_MicroState();

  private final int value;

  MicroState(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static MicroState fromValue(int value) {
    switch (value) {
      case 0: return MS_UNDEFINE;
      case 1: return MS_OPENING;
      case 2: return MS_SLIENCE;
      case 3: return MS_CLOSED;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_MicroState extends EnumAdapter<MicroState> {
    ProtoAdapter_MicroState() {
      super(MicroState.class, Syntax.PROTO_3, MicroState.MS_UNDEFINE);
    }

    @Override
    protected MicroState fromValue(int value) {
      return MicroState.fromValue(value);
    }
  }
}
