// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.MomentCmd in pbcmd.proto
package com.hao.proto;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * 动态及评论
 */
public enum MomentCmd implements WireEnum {
  MomentCmd_Zero(0),

  /**
   * 查看人工推荐列表
   * &haiyaa.IdQuery{}//&haiyaa.MomentInfoS{}//UJ,查看人工推荐列表
   */
  GET_ARTIFICIAL_MOMENT_LIST(7707),

  /**
   * 查看最新的帖子列表
   * &haiyaa.IdQuery{}//&haiyaa.MomentInfoS{}//UJ,查看最新的帖子列表
   */
  GET_LATEST_MOMENT_LIST(7703),

  /**
   * 查看候选的帖子列表
   * &haiyaa.IdQuery{}//&haiyaa.MomentInfoS{}//查看候选的帖子列表
   */
  GET_CANDIDATE_MOMENT_LIST(7701),

  /**
   * 查看待审核帖子列表
   * &haiyaa.IdQuery{}//&haiyaa.MomentInfoS{}//查看待审核帖子列表
   */
  GET_AUDIT_MOMENT_LIST(7709),

  /**
   * 查询帖子详情页
   * &haiyaa.IdQuery{}//&haiyaa.MomentInfo{}//查询帖子详情页
   */
  GET_MOMENT_INFO(7705),

  /**
   * 用户个人动态列表
   * &haiyaa.IdQuery{}//&haiyaa.MomentInfoS{}//UJ,用户个人动态列表
   */
  GET_USER_MOMENT_LIST(7711),

  /**
   * 查询帖子评论列表
   * &haiyaa.IdQuery{}//&haiyaa.CommentInfoS{}//UJ,查询帖子评论列表
   */
  GET_COMMENT_LIST(7713),

  /**
   * 查询用户动态消息
   * &haiyaa.IdQuery{}//&haiyaa.MomentMsgS{}//查询用户动态消息
   */
  GET_USER_MOMENT_MSG(7715),

  /**
   * 发布帖子
   * &haiyaa.MomentInfo{}//&haiyaa.MomentInfo{}//UJ,发布帖子
   */
  PUBLISH_MOMENT_INFO(7721),

  /**
   * 重新编辑完善帖子，已经有帖子Id的情况
   * &haiyaa.MomentInfo{}//&haiyaa.MomentInfo{}//重新编辑完善帖子，已经有帖子Id的情况
   */
  EDIT_MOMENT_INFO(7723),

  /**
   * 用户删除一个已经发布的帖子
   * &haiyaa.IdQuery{}//&haiyaa.UtilRet{}//UJ,用户删除一个已经发布的帖子
   */
  DEL_MOMENT(7731),

  /**
   * 回复帖子
   * &haiyaa.CommentInfo{}//&haiyaa.CommentInfo{}//UJ,回复帖子
   */
  REPLY_TO_MOMENT(7741),

  /**
   * 回复评论
   * &haiyaa.CommentInfo{}//&haiyaa.CommentInfo{}//UJ,回复评论
   */
  REPLY_TO_COMMENT(7743),

  /**
   * 点赞帖子
   * &haiyaa.LikeAction{}//&haiyaa.UtilRet{}//UJ,点赞帖子
   */
  LIKE_TO_MOMENT(7751),

  /**
   * 变更帖子状态
   * &haiyaa.IdQuery{}//&haiyaa.UtilRet{}//变更帖子状态
   */
  EDIT_MOMENT_STATUS(7761),

  /**
   * 帖子审核，正式用户发出的帖子
   * &haiyaa.IdQuery{}//&haiyaa.UtilRet{}//帖子审核，正式用户发出的帖子
   */
  AUDIT_MOMENT(7763);

  public static final ProtoAdapter<MomentCmd> ADAPTER = new ProtoAdapter_MomentCmd();

  private final int value;

  MomentCmd(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static MomentCmd fromValue(int value) {
    switch (value) {
      case 0: return MomentCmd_Zero;
      case 7707: return GET_ARTIFICIAL_MOMENT_LIST;
      case 7703: return GET_LATEST_MOMENT_LIST;
      case 7701: return GET_CANDIDATE_MOMENT_LIST;
      case 7709: return GET_AUDIT_MOMENT_LIST;
      case 7705: return GET_MOMENT_INFO;
      case 7711: return GET_USER_MOMENT_LIST;
      case 7713: return GET_COMMENT_LIST;
      case 7715: return GET_USER_MOMENT_MSG;
      case 7721: return PUBLISH_MOMENT_INFO;
      case 7723: return EDIT_MOMENT_INFO;
      case 7731: return DEL_MOMENT;
      case 7741: return REPLY_TO_MOMENT;
      case 7743: return REPLY_TO_COMMENT;
      case 7751: return LIKE_TO_MOMENT;
      case 7761: return EDIT_MOMENT_STATUS;
      case 7763: return AUDIT_MOMENT;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_MomentCmd extends EnumAdapter<MomentCmd> {
    ProtoAdapter_MomentCmd() {
      super(MomentCmd.class, Syntax.PROTO_3, MomentCmd.MomentCmd_Zero);
    }

    @Override
    protected MomentCmd fromValue(int value) {
      return MomentCmd.fromValue(value);
    }
  }
}
