// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.MsgTypeNum in message.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class MsgTypeNum extends Message<MsgTypeNum, MsgTypeNum.Builder> {
  public static final ProtoAdapter<MsgTypeNum> ADAPTER = new ProtoAdapter_MsgTypeNum();

  private static final long serialVersionUID = 0L;

  /**
   * 消息类型
   */
  public NoticeMsgType msgType;

  /**
   * 新消息数量
   */
  public int msgNum;

  public MsgTypeNum(NoticeMsgType msgType, int msgNum) {
    this(msgType, msgNum, ByteString.EMPTY);
  }

  public MsgTypeNum(NoticeMsgType msgType, int msgNum, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (msgType == null) {
      throw new IllegalArgumentException("msgType == null");
    }
    this.msgType = msgType;
    this.msgNum = msgNum;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.msgType = msgType;
    builder.msgNum = msgNum;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (msgType != null) builder.append(", msgType=").append(msgType);
    builder.append(", msgNum=").append(msgNum);
    return builder.replace(0, 2, "MsgTypeNum{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<MsgTypeNum, Builder> {
    public NoticeMsgType msgType;

    public int msgNum;

    public Builder() {
      msgType = NoticeMsgType.NM_TYPE_ZERO;
      msgNum = 0;
    }

    /**
     * 消息类型
     */
    public Builder msgType(NoticeMsgType msgType) {
      this.msgType = msgType;
      return this;
    }

    /**
     * 新消息数量
     */
    public Builder msgNum(int msgNum) {
      this.msgNum = msgNum;
      return this;
    }

    @Override
    public MsgTypeNum build() {
      return new MsgTypeNum(msgType, msgNum, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_MsgTypeNum extends ProtoAdapter<MsgTypeNum> {
    public ProtoAdapter_MsgTypeNum() {
      super(FieldEncoding.LENGTH_DELIMITED, MsgTypeNum.class, "type.googleapis.com/haiyaa.MsgTypeNum", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(MsgTypeNum value) {
      int result = 0;
      if (!Objects.equals(value.msgType, NoticeMsgType.NM_TYPE_ZERO)) {
        result += NoticeMsgType.ADAPTER.encodedSizeWithTag(1, value.msgType);
      }
      if (!Objects.equals(value.msgNum, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.msgNum);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, MsgTypeNum value) throws IOException {
      if (!Objects.equals(value.msgType, NoticeMsgType.NM_TYPE_ZERO)) NoticeMsgType.ADAPTER.encodeWithTag(writer, 1, value.msgType);
      if (!Objects.equals(value.msgNum, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.msgNum);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public MsgTypeNum decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: {
            try {
              builder.msgType(NoticeMsgType.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 2: builder.msgNum(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public MsgTypeNum redact(MsgTypeNum value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
