// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.MusicInfo in public.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class MusicInfo extends Message<MusicInfo, MusicInfo.Builder> {
  public static final ProtoAdapter<MusicInfo> ADAPTER = new ProtoAdapter_MusicInfo();

  private static final long serialVersionUID = 0L;

  /**
   * 曲库Id
   */
  public String musicId;

  /**
   * 歌曲名字
   */
  public String name;

  /**
   * 艺术家
   */
  public String artist;

  /**
   * 歌曲地址
   */
  public String url;

  /**
   * 状态
   */
  public int state;

  /**
   * 总下载量
   */
  public int downNum;

  /**
   * 文件大小
   */
  public int size;

  /**
   * 上传者
   */
  public long upUid;

  /**
   * 上传者姓名
   */
  public String upName;

  /**
   * 上传时间
   */
  public long upTime;

  /**
   * 记录时间
   */
  public long ctTime;

  public MusicInfo(String musicId, String name, String artist, String url, int state, int downNum,
      int size, long upUid, String upName, long upTime, long ctTime) {
    this(musicId, name, artist, url, state, downNum, size, upUid, upName, upTime, ctTime, ByteString.EMPTY);
  }

  public MusicInfo(String musicId, String name, String artist, String url, int state, int downNum,
      int size, long upUid, String upName, long upTime, long ctTime, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (musicId == null) {
      throw new IllegalArgumentException("musicId == null");
    }
    this.musicId = musicId;
    if (name == null) {
      throw new IllegalArgumentException("name == null");
    }
    this.name = name;
    if (artist == null) {
      throw new IllegalArgumentException("artist == null");
    }
    this.artist = artist;
    if (url == null) {
      throw new IllegalArgumentException("url == null");
    }
    this.url = url;
    this.state = state;
    this.downNum = downNum;
    this.size = size;
    this.upUid = upUid;
    if (upName == null) {
      throw new IllegalArgumentException("upName == null");
    }
    this.upName = upName;
    this.upTime = upTime;
    this.ctTime = ctTime;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.musicId = musicId;
    builder.name = name;
    builder.artist = artist;
    builder.url = url;
    builder.state = state;
    builder.downNum = downNum;
    builder.size = size;
    builder.upUid = upUid;
    builder.upName = upName;
    builder.upTime = upTime;
    builder.ctTime = ctTime;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (musicId != null) builder.append(", musicId=").append(Internal.sanitize(musicId));
    if (name != null) builder.append(", name=").append(Internal.sanitize(name));
    if (artist != null) builder.append(", artist=").append(Internal.sanitize(artist));
    if (url != null) builder.append(", url=").append(Internal.sanitize(url));
    builder.append(", state=").append(state);
    builder.append(", downNum=").append(downNum);
    builder.append(", size=").append(size);
    builder.append(", upUid=").append(upUid);
    if (upName != null) builder.append(", upName=").append(Internal.sanitize(upName));
    builder.append(", upTime=").append(upTime);
    builder.append(", ctTime=").append(ctTime);
    return builder.replace(0, 2, "MusicInfo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<MusicInfo, Builder> {
    public String musicId;

    public String name;

    public String artist;

    public String url;

    public int state;

    public int downNum;

    public int size;

    public long upUid;

    public String upName;

    public long upTime;

    public long ctTime;

    public Builder() {
      musicId = "";
      name = "";
      artist = "";
      url = "";
      state = 0;
      downNum = 0;
      size = 0;
      upUid = 0L;
      upName = "";
      upTime = 0L;
      ctTime = 0L;
    }

    /**
     * 曲库Id
     */
    public Builder musicId(String musicId) {
      this.musicId = musicId;
      return this;
    }

    /**
     * 歌曲名字
     */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /**
     * 艺术家
     */
    public Builder artist(String artist) {
      this.artist = artist;
      return this;
    }

    /**
     * 歌曲地址
     */
    public Builder url(String url) {
      this.url = url;
      return this;
    }

    /**
     * 状态
     */
    public Builder state(int state) {
      this.state = state;
      return this;
    }

    /**
     * 总下载量
     */
    public Builder downNum(int downNum) {
      this.downNum = downNum;
      return this;
    }

    /**
     * 文件大小
     */
    public Builder size(int size) {
      this.size = size;
      return this;
    }

    /**
     * 上传者
     */
    public Builder upUid(long upUid) {
      this.upUid = upUid;
      return this;
    }

    /**
     * 上传者姓名
     */
    public Builder upName(String upName) {
      this.upName = upName;
      return this;
    }

    /**
     * 上传时间
     */
    public Builder upTime(long upTime) {
      this.upTime = upTime;
      return this;
    }

    /**
     * 记录时间
     */
    public Builder ctTime(long ctTime) {
      this.ctTime = ctTime;
      return this;
    }

    @Override
    public MusicInfo build() {
      return new MusicInfo(musicId, name, artist, url, state, downNum, size, upUid, upName, upTime, ctTime, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_MusicInfo extends ProtoAdapter<MusicInfo> {
    public ProtoAdapter_MusicInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, MusicInfo.class, "type.googleapis.com/haiyaa.MusicInfo", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(MusicInfo value) {
      int result = 0;
      if (!Objects.equals(value.musicId, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.musicId);
      }
      if (!Objects.equals(value.name, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.name);
      }
      if (!Objects.equals(value.artist, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.artist);
      }
      if (!Objects.equals(value.url, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(4, value.url);
      }
      if (!Objects.equals(value.state, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(5, value.state);
      }
      if (!Objects.equals(value.downNum, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(6, value.downNum);
      }
      if (!Objects.equals(value.size, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(7, value.size);
      }
      if (!Objects.equals(value.upUid, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(8, value.upUid);
      }
      if (!Objects.equals(value.upName, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(9, value.upName);
      }
      if (!Objects.equals(value.upTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(11, value.upTime);
      }
      if (!Objects.equals(value.ctTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(12, value.ctTime);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, MusicInfo value) throws IOException {
      if (!Objects.equals(value.musicId, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.musicId);
      if (!Objects.equals(value.name, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name);
      if (!Objects.equals(value.artist, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.artist);
      if (!Objects.equals(value.url, "")) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.url);
      if (!Objects.equals(value.state, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 5, value.state);
      if (!Objects.equals(value.downNum, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 6, value.downNum);
      if (!Objects.equals(value.size, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 7, value.size);
      if (!Objects.equals(value.upUid, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 8, value.upUid);
      if (!Objects.equals(value.upName, "")) ProtoAdapter.STRING.encodeWithTag(writer, 9, value.upName);
      if (!Objects.equals(value.upTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 11, value.upTime);
      if (!Objects.equals(value.ctTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 12, value.ctTime);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public MusicInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.musicId(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.name(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.artist(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.url(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.state(ProtoAdapter.INT32.decode(reader)); break;
          case 6: builder.downNum(ProtoAdapter.INT32.decode(reader)); break;
          case 7: builder.size(ProtoAdapter.INT32.decode(reader)); break;
          case 8: builder.upUid(ProtoAdapter.UINT64.decode(reader)); break;
          case 9: builder.upName(ProtoAdapter.STRING.decode(reader)); break;
          case 11: builder.upTime(ProtoAdapter.INT64.decode(reader)); break;
          case 12: builder.ctTime(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public MusicInfo redact(MusicInfo value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
