// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.PhotoInfoS in public.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class PhotoInfoS extends Message<PhotoInfoS, PhotoInfoS.Builder> {
  public static final ProtoAdapter<PhotoInfoS> ADAPTER = new ProtoAdapter_PhotoInfoS();

  private static final long serialVersionUID = 0L;

  public List<PhotoInfo> photos;

  public PhotoInfoS(List<PhotoInfo> photos) {
    this(photos, ByteString.EMPTY);
  }

  public PhotoInfoS(List<PhotoInfo> photos, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.photos = Internal.immutableCopyOf("photos", photos);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.photos = Internal.copyOf(photos);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!photos.isEmpty()) builder.append(", photos=").append(photos);
    return builder.replace(0, 2, "PhotoInfoS{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PhotoInfoS, Builder> {
    public List<PhotoInfo> photos;

    public Builder() {
      photos = Internal.newMutableList();
    }

    public Builder photos(List<PhotoInfo> photos) {
      Internal.checkElementsNotNull(photos);
      this.photos = photos;
      return this;
    }

    @Override
    public PhotoInfoS build() {
      return new PhotoInfoS(photos, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PhotoInfoS extends ProtoAdapter<PhotoInfoS> {
    public ProtoAdapter_PhotoInfoS() {
      super(FieldEncoding.LENGTH_DELIMITED, PhotoInfoS.class, "type.googleapis.com/haiyaa.PhotoInfoS", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(PhotoInfoS value) {
      int result = 0;
      result += PhotoInfo.ADAPTER.asRepeated().encodedSizeWithTag(1, value.photos);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, PhotoInfoS value) throws IOException {
      PhotoInfo.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.photos);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PhotoInfoS decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.photos.add(PhotoInfo.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public PhotoInfoS redact(PhotoInfoS value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.photos, PhotoInfo.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
