// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RankType in event.proto
package com.hao.proto;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum RankType implements WireEnum {
  RT_ZERO(0),

  RT_WELTH(1),

  RT_CHARM(2);

  public static final ProtoAdapter<RankType> ADAPTER = new ProtoAdapter_RankType();

  private final int value;

  RankType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static RankType fromValue(int value) {
    switch (value) {
      case 0: return RT_ZERO;
      case 1: return RT_WELTH;
      case 2: return RT_CHARM;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_RankType extends EnumAdapter<RankType> {
    ProtoAdapter_RankType() {
      super(RankType.class, Syntax.PROTO_3, RankType.RT_ZERO);
    }

    @Override
    protected RankType fromValue(int value) {
      return RankType.fromValue(value);
    }
  }
}
