// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RegisterInfo in user.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 主态注册类信息
 */
public final class RegisterInfo extends Message<RegisterInfo, RegisterInfo.Builder> {
  public static final ProtoAdapter<RegisterInfo> ADAPTER = new ProtoAdapter_RegisterInfo();

  private static final long serialVersionUID = 0L;

  /**
   * RegisterInfo
   * 手机Id, 放到注册类信息里
   */
  public long phoneId;

  /**
   * Email
   */
  public String email;

  /**
   * 谷歌Key/Token
   */
  public String googleId;

  /**
   * 实名姓名
   */
  public String realName;

  /**
   * 身份证号
   */
  public String idCard;

  /**
   * 注册时间
   */
  public long regTime;

  /**
   * 被封禁的时间
   */
  public long banTime;

  /**
   * 最新登录时间
   */
  public long logTime;

  /**
   * 最新离线时间
   */
  public long offTime;

  /**
   * 情侣账号
   */
  public long loveId;

  /**
   * 邀请人Id
   */
  public long mentorId;

  /**
   * 认证情况
   */
  public int verify;

  public RegisterInfo(long phoneId, String email, String googleId, String realName, String idCard,
      long regTime, long banTime, long logTime, long offTime, long loveId, long mentorId,
      int verify) {
    this(phoneId, email, googleId, realName, idCard, regTime, banTime, logTime, offTime, loveId, mentorId, verify, ByteString.EMPTY);
  }

  public RegisterInfo(long phoneId, String email, String googleId, String realName, String idCard,
      long regTime, long banTime, long logTime, long offTime, long loveId, long mentorId,
      int verify, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.phoneId = phoneId;
    if (email == null) {
      throw new IllegalArgumentException("email == null");
    }
    this.email = email;
    if (googleId == null) {
      throw new IllegalArgumentException("googleId == null");
    }
    this.googleId = googleId;
    if (realName == null) {
      throw new IllegalArgumentException("realName == null");
    }
    this.realName = realName;
    if (idCard == null) {
      throw new IllegalArgumentException("idCard == null");
    }
    this.idCard = idCard;
    this.regTime = regTime;
    this.banTime = banTime;
    this.logTime = logTime;
    this.offTime = offTime;
    this.loveId = loveId;
    this.mentorId = mentorId;
    this.verify = verify;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.phoneId = phoneId;
    builder.email = email;
    builder.googleId = googleId;
    builder.realName = realName;
    builder.idCard = idCard;
    builder.regTime = regTime;
    builder.banTime = banTime;
    builder.logTime = logTime;
    builder.offTime = offTime;
    builder.loveId = loveId;
    builder.mentorId = mentorId;
    builder.verify = verify;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", phoneId=").append(phoneId);
    if (email != null) builder.append(", email=").append(Internal.sanitize(email));
    if (googleId != null) builder.append(", googleId=").append(Internal.sanitize(googleId));
    if (realName != null) builder.append(", realName=").append(Internal.sanitize(realName));
    if (idCard != null) builder.append(", idCard=").append(Internal.sanitize(idCard));
    builder.append(", regTime=").append(regTime);
    builder.append(", banTime=").append(banTime);
    builder.append(", logTime=").append(logTime);
    builder.append(", offTime=").append(offTime);
    builder.append(", loveId=").append(loveId);
    builder.append(", mentorId=").append(mentorId);
    builder.append(", verify=").append(verify);
    return builder.replace(0, 2, "RegisterInfo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RegisterInfo, Builder> {
    public long phoneId;

    public String email;

    public String googleId;

    public String realName;

    public String idCard;

    public long regTime;

    public long banTime;

    public long logTime;

    public long offTime;

    public long loveId;

    public long mentorId;

    public int verify;

    public Builder() {
      phoneId = 0L;
      email = "";
      googleId = "";
      realName = "";
      idCard = "";
      regTime = 0L;
      banTime = 0L;
      logTime = 0L;
      offTime = 0L;
      loveId = 0L;
      mentorId = 0L;
      verify = 0;
    }

    /**
     * RegisterInfo
     * 手机Id, 放到注册类信息里
     */
    public Builder phoneId(long phoneId) {
      this.phoneId = phoneId;
      return this;
    }

    /**
     * Email
     */
    public Builder email(String email) {
      this.email = email;
      return this;
    }

    /**
     * 谷歌Key/Token
     */
    public Builder googleId(String googleId) {
      this.googleId = googleId;
      return this;
    }

    /**
     * 实名姓名
     */
    public Builder realName(String realName) {
      this.realName = realName;
      return this;
    }

    /**
     * 身份证号
     */
    public Builder idCard(String idCard) {
      this.idCard = idCard;
      return this;
    }

    /**
     * 注册时间
     */
    public Builder regTime(long regTime) {
      this.regTime = regTime;
      return this;
    }

    /**
     * 被封禁的时间
     */
    public Builder banTime(long banTime) {
      this.banTime = banTime;
      return this;
    }

    /**
     * 最新登录时间
     */
    public Builder logTime(long logTime) {
      this.logTime = logTime;
      return this;
    }

    /**
     * 最新离线时间
     */
    public Builder offTime(long offTime) {
      this.offTime = offTime;
      return this;
    }

    /**
     * 情侣账号
     */
    public Builder loveId(long loveId) {
      this.loveId = loveId;
      return this;
    }

    /**
     * 邀请人Id
     */
    public Builder mentorId(long mentorId) {
      this.mentorId = mentorId;
      return this;
    }

    /**
     * 认证情况
     */
    public Builder verify(int verify) {
      this.verify = verify;
      return this;
    }

    @Override
    public RegisterInfo build() {
      return new RegisterInfo(phoneId, email, googleId, realName, idCard, regTime, banTime, logTime, offTime, loveId, mentorId, verify, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RegisterInfo extends ProtoAdapter<RegisterInfo> {
    public ProtoAdapter_RegisterInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, RegisterInfo.class, "type.googleapis.com/haiyaa.RegisterInfo", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(RegisterInfo value) {
      int result = 0;
      if (!Objects.equals(value.phoneId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.phoneId);
      }
      if (!Objects.equals(value.email, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.email);
      }
      if (!Objects.equals(value.googleId, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.googleId);
      }
      if (!Objects.equals(value.realName, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(4, value.realName);
      }
      if (!Objects.equals(value.idCard, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(5, value.idCard);
      }
      if (!Objects.equals(value.regTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(11, value.regTime);
      }
      if (!Objects.equals(value.banTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(12, value.banTime);
      }
      if (!Objects.equals(value.logTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(13, value.logTime);
      }
      if (!Objects.equals(value.offTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(14, value.offTime);
      }
      if (!Objects.equals(value.loveId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(15, value.loveId);
      }
      if (!Objects.equals(value.mentorId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(16, value.mentorId);
      }
      if (!Objects.equals(value.verify, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(17, value.verify);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, RegisterInfo value) throws IOException {
      if (!Objects.equals(value.phoneId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.phoneId);
      if (!Objects.equals(value.email, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.email);
      if (!Objects.equals(value.googleId, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.googleId);
      if (!Objects.equals(value.realName, "")) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.realName);
      if (!Objects.equals(value.idCard, "")) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.idCard);
      if (!Objects.equals(value.regTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 11, value.regTime);
      if (!Objects.equals(value.banTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 12, value.banTime);
      if (!Objects.equals(value.logTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 13, value.logTime);
      if (!Objects.equals(value.offTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 14, value.offTime);
      if (!Objects.equals(value.loveId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 15, value.loveId);
      if (!Objects.equals(value.mentorId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 16, value.mentorId);
      if (!Objects.equals(value.verify, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 17, value.verify);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RegisterInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.phoneId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.email(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.googleId(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.realName(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.idCard(ProtoAdapter.STRING.decode(reader)); break;
          case 11: builder.regTime(ProtoAdapter.INT64.decode(reader)); break;
          case 12: builder.banTime(ProtoAdapter.INT64.decode(reader)); break;
          case 13: builder.logTime(ProtoAdapter.INT64.decode(reader)); break;
          case 14: builder.offTime(ProtoAdapter.INT64.decode(reader)); break;
          case 15: builder.loveId(ProtoAdapter.UINT64.decode(reader)); break;
          case 16: builder.mentorId(ProtoAdapter.UINT64.decode(reader)); break;
          case 17: builder.verify(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public RegisterInfo redact(RegisterInfo value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
