// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RewardRecordS in gift.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class RewardRecordS extends Message<RewardRecordS, RewardRecordS.Builder> {
  public static final ProtoAdapter<RewardRecordS> ADAPTER = new ProtoAdapter_RewardRecordS();

  private static final long serialVersionUID = 0L;

  public List<RewardRecord> records;

  public RewardRecordS(List<RewardRecord> records) {
    this(records, ByteString.EMPTY);
  }

  public RewardRecordS(List<RewardRecord> records, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.records = Internal.immutableCopyOf("records", records);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.records = Internal.copyOf(records);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!records.isEmpty()) builder.append(", records=").append(records);
    return builder.replace(0, 2, "RewardRecordS{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RewardRecordS, Builder> {
    public List<RewardRecord> records;

    public Builder() {
      records = Internal.newMutableList();
    }

    public Builder records(List<RewardRecord> records) {
      Internal.checkElementsNotNull(records);
      this.records = records;
      return this;
    }

    @Override
    public RewardRecordS build() {
      return new RewardRecordS(records, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RewardRecordS extends ProtoAdapter<RewardRecordS> {
    public ProtoAdapter_RewardRecordS() {
      super(FieldEncoding.LENGTH_DELIMITED, RewardRecordS.class, "type.googleapis.com/haiyaa.RewardRecordS", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(RewardRecordS value) {
      int result = 0;
      result += RewardRecord.ADAPTER.asRepeated().encodedSizeWithTag(1, value.records);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, RewardRecordS value) throws IOException {
      RewardRecord.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.records);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RewardRecordS decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.records.add(RewardRecord.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public RewardRecordS redact(RewardRecordS value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.records, RewardRecord.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
