// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RoomBg in room.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class RoomBg extends Message<RoomBg, RoomBg.Builder> {
  public static final ProtoAdapter<RoomBg> ADAPTER = new ProtoAdapter_RoomBg();

  private static final long serialVersionUID = 0L;

  /**
   * 图片地址
   */
  public String url;

  /**
   * 如果图片有名字
   */
  public String name;

  public RoomBg(String url, String name) {
    this(url, name, ByteString.EMPTY);
  }

  public RoomBg(String url, String name, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (url == null) {
      throw new IllegalArgumentException("url == null");
    }
    this.url = url;
    if (name == null) {
      throw new IllegalArgumentException("name == null");
    }
    this.name = name;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.url = url;
    builder.name = name;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (url != null) builder.append(", url=").append(Internal.sanitize(url));
    if (name != null) builder.append(", name=").append(Internal.sanitize(name));
    return builder.replace(0, 2, "RoomBg{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RoomBg, Builder> {
    public String url;

    public String name;

    public Builder() {
      url = "";
      name = "";
    }

    /**
     * 图片地址
     */
    public Builder url(String url) {
      this.url = url;
      return this;
    }

    /**
     * 如果图片有名字
     */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    @Override
    public RoomBg build() {
      return new RoomBg(url, name, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RoomBg extends ProtoAdapter<RoomBg> {
    public ProtoAdapter_RoomBg() {
      super(FieldEncoding.LENGTH_DELIMITED, RoomBg.class, "type.googleapis.com/haiyaa.RoomBg", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(RoomBg value) {
      int result = 0;
      if (!Objects.equals(value.url, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.url);
      }
      if (!Objects.equals(value.name, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.name);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, RoomBg value) throws IOException {
      if (!Objects.equals(value.url, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.url);
      if (!Objects.equals(value.name, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RoomBg decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.url(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.name(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public RoomBg redact(RoomBg value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
