// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RoomOperType in room.proto
package com.hao.proto;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * 被操作的类型
 */
public enum RoomOperType implements WireEnum {
  /**
   * 未初始化，默认为开麦状态
   */
  OT_UNDEFINE(0),

  /**
   * 麦状态，开麦
   */
  OT_MIC_OPENING(1),

  /**
   * 麦状态，静音，关闭
   */
  OT_MIC_SLIENCE(2),

  /**
   * 麦状态，封麦
   */
  OT_MIC_CLOSED(3),

  /**
   * 被邀请上麦
   */
  OT_MIC_INVITED(6),

  /**
   * 被踢下麦
   */
  OT_MIC_KICKED(7),

  /**
   * 被踢出房间
   */
  OT_ROOM_KICKED(8),

  /**
   * 公屏禁言
   */
  OT_CHAT_BANNED(11),

  /**
   * 允许公屏
   */
  OT_CHAT_ALLOWED(12),

  /**
   * 被设为管理员
   */
  OT_MANAGER_SET(16),

  /**
   * 被取消管理员
   */
  OT_MANAGER_UNSET(17);

  public static final ProtoAdapter<RoomOperType> ADAPTER = new ProtoAdapter_RoomOperType();

  private final int value;

  RoomOperType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static RoomOperType fromValue(int value) {
    switch (value) {
      case 0: return OT_UNDEFINE;
      case 1: return OT_MIC_OPENING;
      case 2: return OT_MIC_SLIENCE;
      case 3: return OT_MIC_CLOSED;
      case 6: return OT_MIC_INVITED;
      case 7: return OT_MIC_KICKED;
      case 8: return OT_ROOM_KICKED;
      case 11: return OT_CHAT_BANNED;
      case 12: return OT_CHAT_ALLOWED;
      case 16: return OT_MANAGER_SET;
      case 17: return OT_MANAGER_UNSET;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_RoomOperType extends EnumAdapter<RoomOperType> {
    ProtoAdapter_RoomOperType() {
      super(RoomOperType.class, Syntax.PROTO_3, RoomOperType.OT_UNDEFINE);
    }

    @Override
    protected RoomOperType fromValue(int value) {
      return RoomOperType.fromValue(value);
    }
  }
}
