// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RoomUid in room.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class RoomUid extends Message<RoomUid, RoomUid.Builder> {
  public static final ProtoAdapter<RoomUid> ADAPTER = new ProtoAdapter_RoomUid();

  private static final long serialVersionUID = 0L;

  /**
   * 房间Id
   */
  public long roomId;

  /**
   * UserId
   */
  public long userId;

  public RoomUid(long roomId, long userId) {
    this(roomId, userId, ByteString.EMPTY);
  }

  public RoomUid(long roomId, long userId, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.roomId = roomId;
    this.userId = userId;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.roomId = roomId;
    builder.userId = userId;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", roomId=").append(roomId);
    builder.append(", userId=").append(userId);
    return builder.replace(0, 2, "RoomUid{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RoomUid, Builder> {
    public long roomId;

    public long userId;

    public Builder() {
      roomId = 0L;
      userId = 0L;
    }

    /**
     * 房间Id
     */
    public Builder roomId(long roomId) {
      this.roomId = roomId;
      return this;
    }

    /**
     * UserId
     */
    public Builder userId(long userId) {
      this.userId = userId;
      return this;
    }

    @Override
    public RoomUid build() {
      return new RoomUid(roomId, userId, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RoomUid extends ProtoAdapter<RoomUid> {
    public ProtoAdapter_RoomUid() {
      super(FieldEncoding.LENGTH_DELIMITED, RoomUid.class, "type.googleapis.com/haiyaa.RoomUid", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(RoomUid value) {
      int result = 0;
      if (!Objects.equals(value.roomId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.roomId);
      }
      if (!Objects.equals(value.userId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(2, value.userId);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, RoomUid value) throws IOException {
      if (!Objects.equals(value.roomId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.roomId);
      if (!Objects.equals(value.userId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.userId);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RoomUid decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.roomId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.userId(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public RoomUid redact(RoomUid value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
