// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RoomCmd in pbcmd.proto
package com.hao.proto;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * 房间
 */
public enum RoomCmd implements WireEnum {
  ROOM_CMD_ZERO(0),

  /**
   * 获取推荐游戏房间
   * &haiyaa.ChanIdQuery{}//&haiyaa.GameItemS{}//频道房间
   */
  GET_CHAN_GAME_ROOMS(7004),

  /**
   * &haiyaa.ChanIdQuery{}//&haiyaa.RoomItemS{}//UJ,私聊房间
   */
  GET_CHAN_LIVE_ROOMS(7005),

  /**
   * &haiyaa.RoomIdQuery{}//&haiyaa.RoomInfo{}//查询房间基础信息，Id填写房间Id，用户Id填pbhead中
   */
  GET_ROOM_INFO(7006),

  /**
   * &haiyaa.UserIdQuery{}//&haiyaa.RoomInfo{}//
   */
  GET_USER_ROOM(7007),

  /**
   * 房主创建房间，解散房间
   * &haiyaa.RoomCreate{}//&haiyaa.RoomInfo{}//
   */
  ROOM_OWNER_CREATE_ROOM(7025),

  /**
   * &haiyaa.IdQuery{}//&haiyaa.UtilRet{}//UJ,用户解散房间, 填写 RoomId，UserId，表示XX请求解散房间
   */
  ROOM_MGR_DISMISS_ROOM(7027),

  /**
   * &haiyaa.RoomInfo{}//&haiyaa.NilProto{}//
   */
  ROOMPUSH_MGR_DISSMISS_ROOM(7028),

  /**
   * 进房间，进入加锁房间，出房间, 邀请进房，踢出房间
   * &haiyaa.IdQuery{}//&haiyaa.RoomInfo{}//用户应邀加入房间, 填写 RoomId，UserId，表示XX请求进入房间，无视房间房间锁房
   */
  ROOM_MGR_INVITE_IN_ROOM(7031),

  /**
   * &haiyaa.JoinRoom{}//&haiyaa.RoomInfo{}//UJ,用户加入房间, 填写 RoomId，UserId，表示XX请求进入房间
   */
  ROOM_USER_IN_ROOM(7033),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.NilProto{}//
   */
  ROOMPUSH_USER_IN_ROOM(7034),

  /**
   * &haiyaa.RoomIdQuery{}//&haiyaa.UtilRet{}//UJ,用户退出房间
   */
  ROOM_USER_OUT_ROOM(7036),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.UtilRet{}//
   */
  ROOMPUSH_USER_OUT_ROOM(7037),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.UtilRet{}//踢出房间
   */
  ROOM_MGR_KICK_ROOM(7038),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.UtilRet{}//
   */
  ROOMPUSH_MGR_KICK_ROOM(7039),

  /**
   * &haiyaa.IdQuery{}//&haiyaa.UtilRet{}//主动退房
   */
  ROOM_USER_GETOUT(7040),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.UtilRet{}//
   */
  ROOMPUSH_USER_GETOUT(7041),

  /**
   * &haiyaa.MgrOperOnMe{}//&haiyaa.UtilRet{}//
   */
  ROOMPUSH_MGR_OPERME(7043),

  /**
   * 房内人员列表，麦上人员列表，可邀请列表，可抱麦列表
   * &haiyaa.RoomIdQuery{}//&haiyaa.RoomUserS{}//查询房间用户列表，Id填写房间Id，用户Id填pbhead中
   */
  ROOM_GET_USER_LIST(7051),

  /**
   * &haiyaa.RoomIdQuery{}//&haiyaa.RoomMicroS{}//查询房间麦上用户列表，Id填写房间Id，用户Id填pbhead中
   */
  ROOM_GET_MICRO_LIST(7052),

  /**
   * &haiyaa.RoomIdQuery{}//&haiyaa.RoomUserS{}//查看房间可邀请列表
   */
  ROOM_GET_CAN_INVITE(7053),

  /**
   * &haiyaa.RoomIdQuery{}//&haiyaa.RoomUserS{}//查看房间抱麦列表
   */
  ROOM_GET_MIC_INVITE(7054),

  /**
   * 房间公屏
   * &haiyaa.UserStdMsg{}//&haiyaa.UtilRet{}//UJ,房间公屏,用户设置哪些人可以私信
   */
  ROOM_USER_CHAT(7055),

  /**
   * &haiyaa.UserStdMsg{}//&haiyaa.UtilRet{}//ROOM_GET_ROOM_CHAT 			= 7349; //&haiyaa.IdQuery{}//&haiyaa.UserStdMsg{}//查询房间历史公屏消息
   */
  ROOMPUSH_USER_CHAT(7056),

  /**
   * 用户上下麦、设置、抱麦及踢麦
   * &haiyaa.RoomMicro{}//&haiyaa.RoomMicro{}//UJ,房间内用户上麦
   */
  ROOM_USER_ON_MICRO(7061),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.RoomMicro{}//UJ,下麦房间内用户上麦
   */
  ROOM_USER_DOWN_MICRO(7062),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.RoomMicro{}//管理员封闭麦
   */
  ROOM_MGR_SET_MICRO(7063),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.UtilRet{}//抱麦
   */
  ROOM_MGR_INVITE_MICRO(7064),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.MicroChange{}//
   */
  ROOMPUSH_MGR_INVITE_MICRO(7065),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.UtilRet{}//
   */
  ROOM_USER_RSP_MICIVT(7066),

  /**
   * &haiyaa.UtilRet{}//&haiyaa.UtilRet{}//
   */
  ROOM_USER_RSP_MICIVT_RSP(7067),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.RoomMicro{}//UJ,踢麦
   */
  ROOM_MGR_KICK_MICRO(7068),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.MicroChange{}//
   */
  ROOMPUSH_MGR_KICK_MICRO(7069),

  /**
   * &haiyaa.RoomMicroS{}//&haiyaa.UtilRet{}//
   */
  ROOMPUSH_MICRO_ALL(7070),

  /**
   * 麦上游戏，麦上表情
   * &haiyaa.RoomMicro{}//&haiyaa.UtilRet{}//UJ,麦上游戏
   */
  ROOM_USER_MICRO_GAME(7071),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.NilProto{}//
   */
  ROOMPUSH_USER_MICRO_GAME(7072),

  /**
   * &haiyaa.MicroFace{}//&haiyaa.UtilRet{}//UJ,麦上表情
   */
  ROOM_USER_MICRO_FACE(7073),

  /**
   * &haiyaa.MicroFace{}//&haiyaa.NilProto{}//
   */
  ROOMPUSH_USER_MICRO_FACE(7074),

  /**
   * 礼物相关
   * &haiyaa.SendGift{}//&haiyaa.UtilRet{}//
   */
  ROOMPUSH_USER_GIFT(7081),

  /**
   * ROOM_MICRO_GIFT 			= 7083; //&haiyaa.RoomMicro{}//&haiyaa.UtilRet{}//UJ,全麦送礼
   * ROOMPUSH_MICRO_GIFT	    = 7084; //&haiyaa.RoomMicro{}//&haiyaa.NilProto{}
   * 房间黑名单
   * &haiyaa.RoomMicro{}//&haiyaa.UtilRet{}//禁言某人，禁止上麦，禁止公屏
   */
  ROOM_MGR_BAN_USER(7101),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.NilProto{}
   */
  ROOMPUSH_MGR_BAN_USER(7102),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.UtilRet{}//取消禁言
   */
  ROOM_MGR_UNBAN_USER(7103),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.NilProto{}
   */
  ROOMPUSH_MGR_UNBAN_USER(7104),

  /**
   * &haiyaa.IdQuery{}//&haiyaa.RoomMicroS{}//禁言列表
   */
  ROOM_GET_BANNER_LIST(7105),

  /**
   * 房间基础设置
   * &haiyaa.RoomBase{}//&haiyaa.RoomBase{}//UJ,设置房间，公屏，如果有标签的话，需要额外的标签处理
   */
  ROOM_MGR_SET_ROOM(7111),

  /**
   * &haiyaa.MgrOperGame{}//&haiyaa.RoomGame{}// 房主拉起或关闭游戏
   */
  ROOM_MGR_SET_GAME(7112),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.UtilRet{}//UJ,管理员设置别的管理员
   */
  ROOM_MGR_SET_MGR(7114),

  /**
   * &haiyaa.RoomMicro{}//&haiyaa.UtilRet{}//UJ,管理员设置别的管理员
   */
  ROOM_MGR_UNSET_MGR(7115),

  /**
   * &haiyaa.IdQuery{}//&haiyaa.RoomMicroS{}//管理员列表
   */
  ROOM_GET_MGR_LIST(7118),

  /**
   * &haiyaa.IdQuery{}//&haiyaa.RoomMicroS{}//管理员列表
   */
  ROOMPUSH_ROOM_INFO(7119),

  /**
   * &haiyaa.RoomBase{}//&haiyaa.NilProto{}//
   */
  ROOMPUSH_ROOM_BASE(7120),

  /**
   * &haiyaa.RoomStatic{}//&haiyaa.NilProto{}//
   */
  ROOMPUSH_ROOM_STATIC(7121),

  /**
   * &haiyaa.RoomManager{}//&haiyaa.NilProto{}//
   */
  ROOMPUSH_ROOM_MANAGER(7122),

  /**
   * &haiyaa.RoomGame{}//&haiyaa.NilProto{}//
   */
  ROOMPUSH_ROOM_GAME(7123),

  /**
   * 匹配游戏房间=创建房间+进房+上麦,模式变更，普通模式转换到游戏模式, 游戏模式转换到普通模式只有游戏结束
   * &haiyaa.RoomMatch{}//&haiyaa.RoomBase{} //用户加入房间, 填写 RoomId，UserId，表示XX请求进入房间
   */
  MATCH_CHAN_ROOM(7131),

  /**
   * GET_USER_GAME_SUD  		= 7132; //&haiyaa.UserIdQuery{}//&haiyaa.GameSUD{}
   * ROOM_MGR_LUNCH_GAME     	= 7132; //&haiyaa.IdQuery{}//&haiyaa.RoomInfo{}
   * ROOMPUSH_MGR_LUNCH_GAME 	= 7133; //&haiyaa.RoomGame{}//&haiyaa.NilProto{}//UJ,房主设置模式，所有人退出，类似于解散。
   * ROOM_MGR_START_GAME 		= 7134; //&haiyaa.RoomGame{}//&haiyaa.UtilRet{}//管理员封闭麦
   * ROOMPUSH_MGR_START_GAME 	= 7135;
   * GAMER_STATE_CHANGE 		= 7136; //&haiyaa.IdQuery{}//&haiyaa.RoomInfo{}//用户加入房间, 填写 RoomId，UserId，表示XX请求进入房间
   * GAMER_STATE_TO_UNREADY 	= 7137; //&haiyaa.IdQuery{}//&haiyaa.RoomInfo{}//用户加入房间, 填写 RoomId，UserId，表示XX请求进入房间
   * ROOMPUSH_GAMER_STATE    	= 7138;
   * ROOM_MGR_END_GAME 		= 7139; //&haiyaa.RoomMicro{}//&haiyaa.UtilRet{}//管理员封闭麦
   * ROOMPUSH_MGR_END_GAME 	= 7140; //&haiyaa.RoomInfo{}//&haiyaa.NilProto{}//UJ,房主设置模式，所有人退出，类似于解散。
   * ROOM_MGR_CLOSE_GAME 		= 7141; //&haiyaa.RoomMicro{}//&haiyaa.UtilRet{}//关闭游戏
   * ROOMPUSH_MGR_CLOSE_GAME 	= 7142; //&haiyaa.RoomInfo{}//&haiyaa.NilProto{}//关闭游戏，模式回到直播模式
   * 系统消息类
   * &haiyaa.IdsQuery{}//&haiyaa.NilProto{}//用户断线
   */
  MUSER_DISSCONN(7191),

  /**
   * &haiyaa.UserStdMsg{}//&haiyaa.NilProto{}//您收到一条房间广播
   */
  ROOMPUSH_ROOM_BROADCAST(7193),

  /**
   * &haiyaa.IdQuery{}//&haiyaa.NilProto{}//房间倒计时
   */
  ROOMPUSH_COUNT_DOWN(7194),

  /**
   * &haiyaa.IdQuery{}//&haiyaa.RoomVisitS{}//
   */
  ROOM_GET_VISITER_LIST(7195);

  public static final ProtoAdapter<RoomCmd> ADAPTER = new ProtoAdapter_RoomCmd();

  private final int value;

  RoomCmd(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static RoomCmd fromValue(int value) {
    switch (value) {
      case 0: return ROOM_CMD_ZERO;
      case 7004: return GET_CHAN_GAME_ROOMS;
      case 7005: return GET_CHAN_LIVE_ROOMS;
      case 7006: return GET_ROOM_INFO;
      case 7007: return GET_USER_ROOM;
      case 7025: return ROOM_OWNER_CREATE_ROOM;
      case 7027: return ROOM_MGR_DISMISS_ROOM;
      case 7028: return ROOMPUSH_MGR_DISSMISS_ROOM;
      case 7031: return ROOM_MGR_INVITE_IN_ROOM;
      case 7033: return ROOM_USER_IN_ROOM;
      case 7034: return ROOMPUSH_USER_IN_ROOM;
      case 7036: return ROOM_USER_OUT_ROOM;
      case 7037: return ROOMPUSH_USER_OUT_ROOM;
      case 7038: return ROOM_MGR_KICK_ROOM;
      case 7039: return ROOMPUSH_MGR_KICK_ROOM;
      case 7040: return ROOM_USER_GETOUT;
      case 7041: return ROOMPUSH_USER_GETOUT;
      case 7043: return ROOMPUSH_MGR_OPERME;
      case 7051: return ROOM_GET_USER_LIST;
      case 7052: return ROOM_GET_MICRO_LIST;
      case 7053: return ROOM_GET_CAN_INVITE;
      case 7054: return ROOM_GET_MIC_INVITE;
      case 7055: return ROOM_USER_CHAT;
      case 7056: return ROOMPUSH_USER_CHAT;
      case 7061: return ROOM_USER_ON_MICRO;
      case 7062: return ROOM_USER_DOWN_MICRO;
      case 7063: return ROOM_MGR_SET_MICRO;
      case 7064: return ROOM_MGR_INVITE_MICRO;
      case 7065: return ROOMPUSH_MGR_INVITE_MICRO;
      case 7066: return ROOM_USER_RSP_MICIVT;
      case 7067: return ROOM_USER_RSP_MICIVT_RSP;
      case 7068: return ROOM_MGR_KICK_MICRO;
      case 7069: return ROOMPUSH_MGR_KICK_MICRO;
      case 7070: return ROOMPUSH_MICRO_ALL;
      case 7071: return ROOM_USER_MICRO_GAME;
      case 7072: return ROOMPUSH_USER_MICRO_GAME;
      case 7073: return ROOM_USER_MICRO_FACE;
      case 7074: return ROOMPUSH_USER_MICRO_FACE;
      case 7081: return ROOMPUSH_USER_GIFT;
      case 7101: return ROOM_MGR_BAN_USER;
      case 7102: return ROOMPUSH_MGR_BAN_USER;
      case 7103: return ROOM_MGR_UNBAN_USER;
      case 7104: return ROOMPUSH_MGR_UNBAN_USER;
      case 7105: return ROOM_GET_BANNER_LIST;
      case 7111: return ROOM_MGR_SET_ROOM;
      case 7112: return ROOM_MGR_SET_GAME;
      case 7114: return ROOM_MGR_SET_MGR;
      case 7115: return ROOM_MGR_UNSET_MGR;
      case 7118: return ROOM_GET_MGR_LIST;
      case 7119: return ROOMPUSH_ROOM_INFO;
      case 7120: return ROOMPUSH_ROOM_BASE;
      case 7121: return ROOMPUSH_ROOM_STATIC;
      case 7122: return ROOMPUSH_ROOM_MANAGER;
      case 7123: return ROOMPUSH_ROOM_GAME;
      case 7131: return MATCH_CHAN_ROOM;
      case 7191: return MUSER_DISSCONN;
      case 7193: return ROOMPUSH_ROOM_BROADCAST;
      case 7194: return ROOMPUSH_COUNT_DOWN;
      case 7195: return ROOM_GET_VISITER_LIST;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_RoomCmd extends EnumAdapter<RoomCmd> {
    ProtoAdapter_RoomCmd() {
      super(RoomCmd.class, Syntax.PROTO_3, RoomCmd.ROOM_CMD_ZERO);
    }

    @Override
    protected RoomCmd fromValue(int value) {
      return RoomCmd.fromValue(value);
    }
  }
}
