// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RoomCreatePage in room.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * UserQuery
 */
public final class RoomCreatePage extends Message<RoomCreatePage, RoomCreatePage.Builder> {
  public static final ProtoAdapter<RoomCreatePage> ADAPTER = new ProtoAdapter_RoomCreatePage();

  private static final long serialVersionUID = 0L;

  public List<RoomChan> chans;

  public RoomCreatePage(List<RoomChan> chans) {
    this(chans, ByteString.EMPTY);
  }

  public RoomCreatePage(List<RoomChan> chans, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.chans = Internal.immutableCopyOf("chans", chans);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.chans = Internal.copyOf(chans);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!chans.isEmpty()) builder.append(", chans=").append(chans);
    return builder.replace(0, 2, "RoomCreatePage{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RoomCreatePage, Builder> {
    public List<RoomChan> chans;

    public Builder() {
      chans = Internal.newMutableList();
    }

    public Builder chans(List<RoomChan> chans) {
      Internal.checkElementsNotNull(chans);
      this.chans = chans;
      return this;
    }

    @Override
    public RoomCreatePage build() {
      return new RoomCreatePage(chans, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RoomCreatePage extends ProtoAdapter<RoomCreatePage> {
    public ProtoAdapter_RoomCreatePage() {
      super(FieldEncoding.LENGTH_DELIMITED, RoomCreatePage.class, "type.googleapis.com/haiyaa.RoomCreatePage", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(RoomCreatePage value) {
      int result = 0;
      result += RoomChan.ADAPTER.asRepeated().encodedSizeWithTag(1, value.chans);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, RoomCreatePage value) throws IOException {
      RoomChan.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.chans);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RoomCreatePage decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.chans.add(RoomChan.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public RoomCreatePage redact(RoomCreatePage value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.chans, RoomChan.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
