// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RoomIdQuery in public.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class RoomIdQuery extends Message<RoomIdQuery, RoomIdQuery.Builder> {
  public static final ProtoAdapter<RoomIdQuery> ADAPTER = new ProtoAdapter_RoomIdQuery();

  private static final long serialVersionUID = 0L;

  /**
   * 查询参数
   */
  public long roomId;

  /**
   * 分页参数
   */
  public int skip;

  /**
   * 分页参数
   */
  public int limit;

  public RoomIdQuery(long roomId, int skip, int limit) {
    this(roomId, skip, limit, ByteString.EMPTY);
  }

  public RoomIdQuery(long roomId, int skip, int limit, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.roomId = roomId;
    this.skip = skip;
    this.limit = limit;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.roomId = roomId;
    builder.skip = skip;
    builder.limit = limit;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", roomId=").append(roomId);
    builder.append(", skip=").append(skip);
    builder.append(", limit=").append(limit);
    return builder.replace(0, 2, "RoomIdQuery{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RoomIdQuery, Builder> {
    public long roomId;

    public int skip;

    public int limit;

    public Builder() {
      roomId = 0L;
      skip = 0;
      limit = 0;
    }

    /**
     * 查询参数
     */
    public Builder roomId(long roomId) {
      this.roomId = roomId;
      return this;
    }

    /**
     * 分页参数
     */
    public Builder skip(int skip) {
      this.skip = skip;
      return this;
    }

    /**
     * 分页参数
     */
    public Builder limit(int limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public RoomIdQuery build() {
      return new RoomIdQuery(roomId, skip, limit, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RoomIdQuery extends ProtoAdapter<RoomIdQuery> {
    public ProtoAdapter_RoomIdQuery() {
      super(FieldEncoding.LENGTH_DELIMITED, RoomIdQuery.class, "type.googleapis.com/haiyaa.RoomIdQuery", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(RoomIdQuery value) {
      int result = 0;
      if (!Objects.equals(value.roomId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.roomId);
      }
      if (!Objects.equals(value.skip, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.skip);
      }
      if (!Objects.equals(value.limit, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(3, value.limit);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, RoomIdQuery value) throws IOException {
      if (!Objects.equals(value.roomId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.roomId);
      if (!Objects.equals(value.skip, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.skip);
      if (!Objects.equals(value.limit, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.limit);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RoomIdQuery decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.roomId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.skip(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.limit(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public RoomIdQuery redact(RoomIdQuery value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
