// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RoomMatch in room.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 匹配游戏/直播房
 */
public final class RoomMatch extends Message<RoomMatch, RoomMatch.Builder> {
  public static final ProtoAdapter<RoomMatch> ADAPTER = new ProtoAdapter_RoomMatch();

  private static final long serialVersionUID = 0L;

  /**
   * 选填，匹配一个直播频道房
   */
  public int liveChan;

  /**
   * 选填，匹配一个游戏频道房
   */
  public int gameChan;

  public RoomMatch(int liveChan, int gameChan) {
    this(liveChan, gameChan, ByteString.EMPTY);
  }

  public RoomMatch(int liveChan, int gameChan, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.liveChan = liveChan;
    this.gameChan = gameChan;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.liveChan = liveChan;
    builder.gameChan = gameChan;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", liveChan=").append(liveChan);
    builder.append(", gameChan=").append(gameChan);
    return builder.replace(0, 2, "RoomMatch{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RoomMatch, Builder> {
    public int liveChan;

    public int gameChan;

    public Builder() {
      liveChan = 0;
      gameChan = 0;
    }

    /**
     * 选填，匹配一个直播频道房
     */
    public Builder liveChan(int liveChan) {
      this.liveChan = liveChan;
      return this;
    }

    /**
     * 选填，匹配一个游戏频道房
     */
    public Builder gameChan(int gameChan) {
      this.gameChan = gameChan;
      return this;
    }

    @Override
    public RoomMatch build() {
      return new RoomMatch(liveChan, gameChan, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RoomMatch extends ProtoAdapter<RoomMatch> {
    public ProtoAdapter_RoomMatch() {
      super(FieldEncoding.LENGTH_DELIMITED, RoomMatch.class, "type.googleapis.com/haiyaa.RoomMatch", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(RoomMatch value) {
      int result = 0;
      if (!Objects.equals(value.liveChan, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(1, value.liveChan);
      }
      if (!Objects.equals(value.gameChan, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.gameChan);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, RoomMatch value) throws IOException {
      if (!Objects.equals(value.liveChan, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.liveChan);
      if (!Objects.equals(value.gameChan, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.gameChan);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RoomMatch decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.liveChan(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.gameChan(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public RoomMatch redact(RoomMatch value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
