// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RoomGame in game.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * for svr
 */
public final class RoomGame extends Message<RoomGame, RoomGame.Builder> {
  public static final ProtoAdapter<RoomGame> ADAPTER = new ProtoAdapter_RoomGame();

  private static final long serialVersionUID = 0L;

  /**
   * 游戏Id，标签Id
   */
  public long gameId;

  /**
   * 频道名
   */
  public String gameName;

  /**
   * 频道ID
   */
  public int gameChan;

  /**
   * Icon地址
   */
  public String gameIcon;

  /**
   * 长图
   */
  public String gameImage;

  /**
   * 游戏模式
   */
  public String gameMode;

  /**
   * GameState 当前游戏状态，开启，开始，结束
   */
  public int gameState;

  /**
   * 最大参与游戏人数
   */
  public int gamerMax;

  /**
   * 当前参与人数
   */
  public int gamerCur;

  public RoomGame(long gameId, String gameName, int gameChan, String gameIcon, String gameImage,
      String gameMode, int gameState, int gamerMax, int gamerCur) {
    this(gameId, gameName, gameChan, gameIcon, gameImage, gameMode, gameState, gamerMax, gamerCur, ByteString.EMPTY);
  }

  public RoomGame(long gameId, String gameName, int gameChan, String gameIcon, String gameImage,
      String gameMode, int gameState, int gamerMax, int gamerCur, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.gameId = gameId;
    if (gameName == null) {
      throw new IllegalArgumentException("gameName == null");
    }
    this.gameName = gameName;
    this.gameChan = gameChan;
    if (gameIcon == null) {
      throw new IllegalArgumentException("gameIcon == null");
    }
    this.gameIcon = gameIcon;
    if (gameImage == null) {
      throw new IllegalArgumentException("gameImage == null");
    }
    this.gameImage = gameImage;
    if (gameMode == null) {
      throw new IllegalArgumentException("gameMode == null");
    }
    this.gameMode = gameMode;
    this.gameState = gameState;
    this.gamerMax = gamerMax;
    this.gamerCur = gamerCur;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.gameId = gameId;
    builder.gameName = gameName;
    builder.gameChan = gameChan;
    builder.gameIcon = gameIcon;
    builder.gameImage = gameImage;
    builder.gameMode = gameMode;
    builder.gameState = gameState;
    builder.gamerMax = gamerMax;
    builder.gamerCur = gamerCur;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", gameId=").append(gameId);
    if (gameName != null) builder.append(", gameName=").append(Internal.sanitize(gameName));
    builder.append(", gameChan=").append(gameChan);
    if (gameIcon != null) builder.append(", gameIcon=").append(Internal.sanitize(gameIcon));
    if (gameImage != null) builder.append(", gameImage=").append(Internal.sanitize(gameImage));
    if (gameMode != null) builder.append(", gameMode=").append(Internal.sanitize(gameMode));
    builder.append(", gameState=").append(gameState);
    builder.append(", gamerMax=").append(gamerMax);
    builder.append(", gamerCur=").append(gamerCur);
    return builder.replace(0, 2, "RoomGame{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RoomGame, Builder> {
    public long gameId;

    public String gameName;

    public int gameChan;

    public String gameIcon;

    public String gameImage;

    public String gameMode;

    public int gameState;

    public int gamerMax;

    public int gamerCur;

    public Builder() {
      gameId = 0L;
      gameName = "";
      gameChan = 0;
      gameIcon = "";
      gameImage = "";
      gameMode = "";
      gameState = 0;
      gamerMax = 0;
      gamerCur = 0;
    }

    /**
     * 游戏Id，标签Id
     */
    public Builder gameId(long gameId) {
      this.gameId = gameId;
      return this;
    }

    /**
     * 频道名
     */
    public Builder gameName(String gameName) {
      this.gameName = gameName;
      return this;
    }

    /**
     * 频道ID
     */
    public Builder gameChan(int gameChan) {
      this.gameChan = gameChan;
      return this;
    }

    /**
     * Icon地址
     */
    public Builder gameIcon(String gameIcon) {
      this.gameIcon = gameIcon;
      return this;
    }

    /**
     * 长图
     */
    public Builder gameImage(String gameImage) {
      this.gameImage = gameImage;
      return this;
    }

    /**
     * 游戏模式
     */
    public Builder gameMode(String gameMode) {
      this.gameMode = gameMode;
      return this;
    }

    /**
     * GameState 当前游戏状态，开启，开始，结束
     */
    public Builder gameState(int gameState) {
      this.gameState = gameState;
      return this;
    }

    /**
     * 最大参与游戏人数
     */
    public Builder gamerMax(int gamerMax) {
      this.gamerMax = gamerMax;
      return this;
    }

    /**
     * 当前参与人数
     */
    public Builder gamerCur(int gamerCur) {
      this.gamerCur = gamerCur;
      return this;
    }

    @Override
    public RoomGame build() {
      return new RoomGame(gameId, gameName, gameChan, gameIcon, gameImage, gameMode, gameState, gamerMax, gamerCur, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RoomGame extends ProtoAdapter<RoomGame> {
    public ProtoAdapter_RoomGame() {
      super(FieldEncoding.LENGTH_DELIMITED, RoomGame.class, "type.googleapis.com/haiyaa.RoomGame", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(RoomGame value) {
      int result = 0;
      if (!Objects.equals(value.gameId, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(1, value.gameId);
      }
      if (!Objects.equals(value.gameName, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.gameName);
      }
      if (!Objects.equals(value.gameChan, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(3, value.gameChan);
      }
      if (!Objects.equals(value.gameIcon, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(4, value.gameIcon);
      }
      if (!Objects.equals(value.gameImage, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(5, value.gameImage);
      }
      if (!Objects.equals(value.gameMode, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(6, value.gameMode);
      }
      if (!Objects.equals(value.gameState, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(7, value.gameState);
      }
      if (!Objects.equals(value.gamerMax, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(8, value.gamerMax);
      }
      if (!Objects.equals(value.gamerCur, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(9, value.gamerCur);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, RoomGame value) throws IOException {
      if (!Objects.equals(value.gameId, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.gameId);
      if (!Objects.equals(value.gameName, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.gameName);
      if (!Objects.equals(value.gameChan, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.gameChan);
      if (!Objects.equals(value.gameIcon, "")) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.gameIcon);
      if (!Objects.equals(value.gameImage, "")) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.gameImage);
      if (!Objects.equals(value.gameMode, "")) ProtoAdapter.STRING.encodeWithTag(writer, 6, value.gameMode);
      if (!Objects.equals(value.gameState, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 7, value.gameState);
      if (!Objects.equals(value.gamerMax, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 8, value.gamerMax);
      if (!Objects.equals(value.gamerCur, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 9, value.gamerCur);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RoomGame decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.gameId(ProtoAdapter.INT64.decode(reader)); break;
          case 2: builder.gameName(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.gameChan(ProtoAdapter.INT32.decode(reader)); break;
          case 4: builder.gameIcon(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.gameImage(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.gameMode(ProtoAdapter.STRING.decode(reader)); break;
          case 7: builder.gameState(ProtoAdapter.INT32.decode(reader)); break;
          case 8: builder.gamerMax(ProtoAdapter.INT32.decode(reader)); break;
          case 9: builder.gamerCur(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public RoomGame redact(RoomGame value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
