// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RoomInOut in room.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 只有现房间，表明是进入，只有原房间，说明是退出，有两个，说明是跳房
 */
public final class RoomInOut extends Message<RoomInOut, RoomInOut.Builder> {
  public static final ProtoAdapter<RoomInOut> ADAPTER = new ProtoAdapter_RoomInOut();

  private static final long serialVersionUID = 0L;

  /**
   * 用户id
   */
  public long userId;

  /**
   * 原房间Id
   */
  public long oldRoomId;

  /**
   * 现房间Id
   */
  public long newRoomId;

  public RoomInOut(long userId, long oldRoomId, long newRoomId) {
    this(userId, oldRoomId, newRoomId, ByteString.EMPTY);
  }

  public RoomInOut(long userId, long oldRoomId, long newRoomId, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.userId = userId;
    this.oldRoomId = oldRoomId;
    this.newRoomId = newRoomId;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.userId = userId;
    builder.oldRoomId = oldRoomId;
    builder.newRoomId = newRoomId;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", userId=").append(userId);
    builder.append(", oldRoomId=").append(oldRoomId);
    builder.append(", newRoomId=").append(newRoomId);
    return builder.replace(0, 2, "RoomInOut{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RoomInOut, Builder> {
    public long userId;

    public long oldRoomId;

    public long newRoomId;

    public Builder() {
      userId = 0L;
      oldRoomId = 0L;
      newRoomId = 0L;
    }

    /**
     * 用户id
     */
    public Builder userId(long userId) {
      this.userId = userId;
      return this;
    }

    /**
     * 原房间Id
     */
    public Builder oldRoomId(long oldRoomId) {
      this.oldRoomId = oldRoomId;
      return this;
    }

    /**
     * 现房间Id
     */
    public Builder newRoomId(long newRoomId) {
      this.newRoomId = newRoomId;
      return this;
    }

    @Override
    public RoomInOut build() {
      return new RoomInOut(userId, oldRoomId, newRoomId, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RoomInOut extends ProtoAdapter<RoomInOut> {
    public ProtoAdapter_RoomInOut() {
      super(FieldEncoding.LENGTH_DELIMITED, RoomInOut.class, "type.googleapis.com/haiyaa.RoomInOut", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(RoomInOut value) {
      int result = 0;
      if (!Objects.equals(value.userId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.userId);
      }
      if (!Objects.equals(value.oldRoomId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(2, value.oldRoomId);
      }
      if (!Objects.equals(value.newRoomId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(3, value.newRoomId);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, RoomInOut value) throws IOException {
      if (!Objects.equals(value.userId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.userId);
      if (!Objects.equals(value.oldRoomId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.oldRoomId);
      if (!Objects.equals(value.newRoomId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 3, value.newRoomId);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RoomInOut decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.userId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.oldRoomId(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.newRoomId(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public RoomInOut redact(RoomInOut value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
