// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RoomItemS in room.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class RoomItemS extends Message<RoomItemS, RoomItemS.Builder> {
  public static final ProtoAdapter<RoomItemS> ADAPTER = new ProtoAdapter_RoomItemS();

  private static final long serialVersionUID = 0L;

  /**
   * 推荐房间列表
   */
  public List<RoomItem> rooms;

  public RoomItemS(List<RoomItem> rooms) {
    this(rooms, ByteString.EMPTY);
  }

  public RoomItemS(List<RoomItem> rooms, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.rooms = Internal.immutableCopyOf("rooms", rooms);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.rooms = Internal.copyOf(rooms);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!rooms.isEmpty()) builder.append(", rooms=").append(rooms);
    return builder.replace(0, 2, "RoomItemS{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RoomItemS, Builder> {
    public List<RoomItem> rooms;

    public Builder() {
      rooms = Internal.newMutableList();
    }

    /**
     * 推荐房间列表
     */
    public Builder rooms(List<RoomItem> rooms) {
      Internal.checkElementsNotNull(rooms);
      this.rooms = rooms;
      return this;
    }

    @Override
    public RoomItemS build() {
      return new RoomItemS(rooms, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RoomItemS extends ProtoAdapter<RoomItemS> {
    public ProtoAdapter_RoomItemS() {
      super(FieldEncoding.LENGTH_DELIMITED, RoomItemS.class, "type.googleapis.com/haiyaa.RoomItemS", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(RoomItemS value) {
      int result = 0;
      result += RoomItem.ADAPTER.asRepeated().encodedSizeWithTag(1, value.rooms);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, RoomItemS value) throws IOException {
      RoomItem.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.rooms);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RoomItemS decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.rooms.add(RoomItem.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public RoomItemS redact(RoomItemS value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.rooms, RoomItem.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
