// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RoomVisitS in room.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Objects;
import okio.ByteString;

public final class RoomVisitS extends Message<RoomVisitS, RoomVisitS.Builder> {
  public static final ProtoAdapter<RoomVisitS> ADAPTER = new ProtoAdapter_RoomVisitS();

  private static final long serialVersionUID = 0L;

  /**
   * 房间Id
   */
  public long roomId;

  public List<RoomVisit> visits;

  public RoomVisitS(long roomId, List<RoomVisit> visits) {
    this(roomId, visits, ByteString.EMPTY);
  }

  public RoomVisitS(long roomId, List<RoomVisit> visits, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.roomId = roomId;
    this.visits = Internal.immutableCopyOf("visits", visits);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.roomId = roomId;
    builder.visits = Internal.copyOf(visits);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", roomId=").append(roomId);
    if (!visits.isEmpty()) builder.append(", visits=").append(visits);
    return builder.replace(0, 2, "RoomVisitS{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RoomVisitS, Builder> {
    public long roomId;

    public List<RoomVisit> visits;

    public Builder() {
      roomId = 0L;
      visits = Internal.newMutableList();
    }

    /**
     * 房间Id
     */
    public Builder roomId(long roomId) {
      this.roomId = roomId;
      return this;
    }

    public Builder visits(List<RoomVisit> visits) {
      Internal.checkElementsNotNull(visits);
      this.visits = visits;
      return this;
    }

    @Override
    public RoomVisitS build() {
      return new RoomVisitS(roomId, visits, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RoomVisitS extends ProtoAdapter<RoomVisitS> {
    public ProtoAdapter_RoomVisitS() {
      super(FieldEncoding.LENGTH_DELIMITED, RoomVisitS.class, "type.googleapis.com/haiyaa.RoomVisitS", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(RoomVisitS value) {
      int result = 0;
      if (!Objects.equals(value.roomId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.roomId);
      }
      result += RoomVisit.ADAPTER.asRepeated().encodedSizeWithTag(2, value.visits);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, RoomVisitS value) throws IOException {
      if (!Objects.equals(value.roomId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.roomId);
      RoomVisit.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.visits);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RoomVisitS decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.roomId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.visits.add(RoomVisit.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public RoomVisitS redact(RoomVisitS value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.visits, RoomVisit.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
