// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RoomVisit in room.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 房间访问记录, 进房记录
 */
public final class RoomVisit extends Message<RoomVisit, RoomVisit.Builder> {
  public static final ProtoAdapter<RoomVisit> ADAPTER = new ProtoAdapter_RoomVisit();

  private static final long serialVersionUID = 0L;

  /**
   * 用户id
   */
  public long userId;

  /**
   * 当前所在房间，是否在房
   */
  public long roomId;

  /**
   * 访问时间
   */
  public long visitTime;

  /**
   * 用户头像，未必有, 如果是麦位状态变化，也忽略麦上人的因素
   */
  public UserBase user;

  public RoomVisit(long userId, long roomId, long visitTime, UserBase user) {
    this(userId, roomId, visitTime, user, ByteString.EMPTY);
  }

  public RoomVisit(long userId, long roomId, long visitTime, UserBase user,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.userId = userId;
    this.roomId = roomId;
    this.visitTime = visitTime;
    this.user = user;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.userId = userId;
    builder.roomId = roomId;
    builder.visitTime = visitTime;
    builder.user = user;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", userId=").append(userId);
    builder.append(", roomId=").append(roomId);
    builder.append(", visitTime=").append(visitTime);
    if (user != null) builder.append(", user=").append(user);
    return builder.replace(0, 2, "RoomVisit{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RoomVisit, Builder> {
    public long userId;

    public long roomId;

    public long visitTime;

    public UserBase user;

    public Builder() {
      userId = 0L;
      roomId = 0L;
      visitTime = 0L;
    }

    /**
     * 用户id
     */
    public Builder userId(long userId) {
      this.userId = userId;
      return this;
    }

    /**
     * 当前所在房间，是否在房
     */
    public Builder roomId(long roomId) {
      this.roomId = roomId;
      return this;
    }

    /**
     * 访问时间
     */
    public Builder visitTime(long visitTime) {
      this.visitTime = visitTime;
      return this;
    }

    /**
     * 用户头像，未必有, 如果是麦位状态变化，也忽略麦上人的因素
     */
    public Builder user(UserBase user) {
      this.user = user;
      return this;
    }

    @Override
    public RoomVisit build() {
      return new RoomVisit(userId, roomId, visitTime, user, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RoomVisit extends ProtoAdapter<RoomVisit> {
    public ProtoAdapter_RoomVisit() {
      super(FieldEncoding.LENGTH_DELIMITED, RoomVisit.class, "type.googleapis.com/haiyaa.RoomVisit", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(RoomVisit value) {
      int result = 0;
      if (!Objects.equals(value.userId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.userId);
      }
      if (!Objects.equals(value.roomId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(2, value.roomId);
      }
      if (!Objects.equals(value.visitTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(3, value.visitTime);
      }
      if (!Objects.equals(value.user, null)) {
        result += UserBase.ADAPTER.encodedSizeWithTag(4, value.user);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, RoomVisit value) throws IOException {
      if (!Objects.equals(value.userId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.userId);
      if (!Objects.equals(value.roomId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.roomId);
      if (!Objects.equals(value.visitTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 3, value.visitTime);
      if (!Objects.equals(value.user, null)) UserBase.ADAPTER.encodeWithTag(writer, 4, value.user);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RoomVisit decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.userId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.roomId(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.visitTime(ProtoAdapter.INT64.decode(reader)); break;
          case 4: builder.user(UserBase.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public RoomVisit redact(RoomVisit value) {
      Builder builder = value.newBuilder();
      if (builder.user != null) builder.user = UserBase.ADAPTER.redact(builder.user);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
