// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RoomUidS in room.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Objects;
import okio.ByteString;

public final class RoomUidS extends Message<RoomUidS, RoomUidS.Builder> {
  public static final ProtoAdapter<RoomUidS> ADAPTER = new ProtoAdapter_RoomUidS();

  private static final long serialVersionUID = 0L;

  /**
   * 房间Id
   */
  public long roomId;

  public List<Long> userIds;

  public RoomUidS(long roomId, List<Long> userIds) {
    this(roomId, userIds, ByteString.EMPTY);
  }

  public RoomUidS(long roomId, List<Long> userIds, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.roomId = roomId;
    this.userIds = Internal.immutableCopyOf("userIds", userIds);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.roomId = roomId;
    builder.userIds = Internal.copyOf(userIds);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", roomId=").append(roomId);
    if (!userIds.isEmpty()) builder.append(", userIds=").append(userIds);
    return builder.replace(0, 2, "RoomUidS{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RoomUidS, Builder> {
    public long roomId;

    public List<Long> userIds;

    public Builder() {
      roomId = 0L;
      userIds = Internal.newMutableList();
    }

    /**
     * 房间Id
     */
    public Builder roomId(long roomId) {
      this.roomId = roomId;
      return this;
    }

    public Builder userIds(List<Long> userIds) {
      Internal.checkElementsNotNull(userIds);
      this.userIds = userIds;
      return this;
    }

    @Override
    public RoomUidS build() {
      return new RoomUidS(roomId, userIds, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RoomUidS extends ProtoAdapter<RoomUidS> {
    public ProtoAdapter_RoomUidS() {
      super(FieldEncoding.LENGTH_DELIMITED, RoomUidS.class, "type.googleapis.com/haiyaa.RoomUidS", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(RoomUidS value) {
      int result = 0;
      if (!Objects.equals(value.roomId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.roomId);
      }
      result += ProtoAdapter.UINT64.asPacked().encodedSizeWithTag(2, value.userIds);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, RoomUidS value) throws IOException {
      if (!Objects.equals(value.roomId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.roomId);
      ProtoAdapter.UINT64.asPacked().encodeWithTag(writer, 2, value.userIds);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RoomUidS decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.roomId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.userIds.add(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public RoomUidS redact(RoomUidS value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
