// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.RoomRole in room.proto
package com.hao.proto;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum RoomRole implements WireEnum {
  /**
   * 听众
   */
  RR_VISITER(0),

  /**
   * 麦上
   */
  RR_SPEAKER(1),

  /**
   * 管理员
   */
  RR_MANAGER(2),

  /**
   * 房主
   */
  RR_OWNER(3);

  public static final ProtoAdapter<RoomRole> ADAPTER = new ProtoAdapter_RoomRole();

  private final int value;

  RoomRole(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static RoomRole fromValue(int value) {
    switch (value) {
      case 0: return RR_VISITER;
      case 1: return RR_SPEAKER;
      case 2: return RR_MANAGER;
      case 3: return RR_OWNER;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_RoomRole extends EnumAdapter<RoomRole> {
    ProtoAdapter_RoomRole() {
      super(RoomRole.class, Syntax.PROTO_3, RoomRole.RR_VISITER);
    }

    @Override
    protected RoomRole fromValue(int value) {
      return RoomRole.fromValue(value);
    }
  }
}
