// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.SendGift in gift.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Objects;
import okio.ByteString;

public final class SendGift extends Message<SendGift, SendGift.Builder> {
  public static final ProtoAdapter<SendGift> ADAPTER = new ProtoAdapter_SendGift();

  private static final long serialVersionUID = 0L;

  /**
   * 如果是房间，则填写，主页送礼，不写
   */
  public long roomId;

  /**
   * 收礼人列表
   */
  public List<Long> toUids;

  /**
   * 礼物Id
   */
  public int giftId;

  /**
   * 礼物数量
   */
  public int giftNum;

  /**
   * 礼物详情，送礼时不填
   */
  public GiftInfo gInfo;

  /**
   * 送礼人头像
   */
  public UserBase sender;

  /**
   * 收礼人头像，人送
   */
  public List<UserBase> recvs;

  public SendGift(long roomId, List<Long> toUids, int giftId, int giftNum, GiftInfo gInfo,
      UserBase sender, List<UserBase> recvs) {
    this(roomId, toUids, giftId, giftNum, gInfo, sender, recvs, ByteString.EMPTY);
  }

  public SendGift(long roomId, List<Long> toUids, int giftId, int giftNum, GiftInfo gInfo,
      UserBase sender, List<UserBase> recvs, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.roomId = roomId;
    this.toUids = Internal.immutableCopyOf("toUids", toUids);
    this.giftId = giftId;
    this.giftNum = giftNum;
    this.gInfo = gInfo;
    this.sender = sender;
    this.recvs = Internal.immutableCopyOf("recvs", recvs);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.roomId = roomId;
    builder.toUids = Internal.copyOf(toUids);
    builder.giftId = giftId;
    builder.giftNum = giftNum;
    builder.gInfo = gInfo;
    builder.sender = sender;
    builder.recvs = Internal.copyOf(recvs);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", roomId=").append(roomId);
    if (!toUids.isEmpty()) builder.append(", toUids=").append(toUids);
    builder.append(", giftId=").append(giftId);
    builder.append(", giftNum=").append(giftNum);
    if (gInfo != null) builder.append(", gInfo=").append(gInfo);
    if (sender != null) builder.append(", sender=").append(sender);
    if (!recvs.isEmpty()) builder.append(", recvs=").append(recvs);
    return builder.replace(0, 2, "SendGift{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<SendGift, Builder> {
    public long roomId;

    public List<Long> toUids;

    public int giftId;

    public int giftNum;

    public GiftInfo gInfo;

    public UserBase sender;

    public List<UserBase> recvs;

    public Builder() {
      roomId = 0L;
      toUids = Internal.newMutableList();
      giftId = 0;
      giftNum = 0;
      recvs = Internal.newMutableList();
    }

    /**
     * 如果是房间，则填写，主页送礼，不写
     */
    public Builder roomId(long roomId) {
      this.roomId = roomId;
      return this;
    }

    /**
     * 收礼人列表
     */
    public Builder toUids(List<Long> toUids) {
      Internal.checkElementsNotNull(toUids);
      this.toUids = toUids;
      return this;
    }

    /**
     * 礼物Id
     */
    public Builder giftId(int giftId) {
      this.giftId = giftId;
      return this;
    }

    /**
     * 礼物数量
     */
    public Builder giftNum(int giftNum) {
      this.giftNum = giftNum;
      return this;
    }

    /**
     * 礼物详情，送礼时不填
     */
    public Builder gInfo(GiftInfo gInfo) {
      this.gInfo = gInfo;
      return this;
    }

    /**
     * 送礼人头像
     */
    public Builder sender(UserBase sender) {
      this.sender = sender;
      return this;
    }

    /**
     * 收礼人头像，人送
     */
    public Builder recvs(List<UserBase> recvs) {
      Internal.checkElementsNotNull(recvs);
      this.recvs = recvs;
      return this;
    }

    @Override
    public SendGift build() {
      return new SendGift(roomId, toUids, giftId, giftNum, gInfo, sender, recvs, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_SendGift extends ProtoAdapter<SendGift> {
    public ProtoAdapter_SendGift() {
      super(FieldEncoding.LENGTH_DELIMITED, SendGift.class, "type.googleapis.com/haiyaa.SendGift", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(SendGift value) {
      int result = 0;
      if (!Objects.equals(value.roomId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.roomId);
      }
      result += ProtoAdapter.UINT64.asPacked().encodedSizeWithTag(2, value.toUids);
      if (!Objects.equals(value.giftId, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(3, value.giftId);
      }
      if (!Objects.equals(value.giftNum, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(4, value.giftNum);
      }
      if (!Objects.equals(value.gInfo, null)) {
        result += GiftInfo.ADAPTER.encodedSizeWithTag(5, value.gInfo);
      }
      if (!Objects.equals(value.sender, null)) {
        result += UserBase.ADAPTER.encodedSizeWithTag(10, value.sender);
      }
      result += UserBase.ADAPTER.asRepeated().encodedSizeWithTag(11, value.recvs);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, SendGift value) throws IOException {
      if (!Objects.equals(value.roomId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.roomId);
      ProtoAdapter.UINT64.asPacked().encodeWithTag(writer, 2, value.toUids);
      if (!Objects.equals(value.giftId, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.giftId);
      if (!Objects.equals(value.giftNum, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.giftNum);
      if (!Objects.equals(value.gInfo, null)) GiftInfo.ADAPTER.encodeWithTag(writer, 5, value.gInfo);
      if (!Objects.equals(value.sender, null)) UserBase.ADAPTER.encodeWithTag(writer, 10, value.sender);
      UserBase.ADAPTER.asRepeated().encodeWithTag(writer, 11, value.recvs);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public SendGift decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.roomId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.toUids.add(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.giftId(ProtoAdapter.INT32.decode(reader)); break;
          case 4: builder.giftNum(ProtoAdapter.INT32.decode(reader)); break;
          case 5: builder.gInfo(GiftInfo.ADAPTER.decode(reader)); break;
          case 10: builder.sender(UserBase.ADAPTER.decode(reader)); break;
          case 11: builder.recvs.add(UserBase.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public SendGift redact(SendGift value) {
      Builder builder = value.newBuilder();
      if (builder.gInfo != null) builder.gInfo = GiftInfo.ADAPTER.redact(builder.gInfo);
      if (builder.sender != null) builder.sender = UserBase.ADAPTER.redact(builder.sender);
      Internal.redactElements(builder.recvs, UserBase.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
