// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.SetUserAccessoriesReq in haiyaa.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 设置用户装扮
 */
public final class SetUserAccessoriesReq extends Message<SetUserAccessoriesReq, SetUserAccessoriesReq.Builder> {
  public static final ProtoAdapter<SetUserAccessoriesReq> ADAPTER = new ProtoAdapter_SetUserAccessoriesReq();

  private static final long serialVersionUID = 0L;

  public SetUserAccessoriesReq() {
    this(ByteString.EMPTY);
  }

  public SetUserAccessoriesReq(ByteString unknownFields) {
    super(ADAPTER, unknownFields);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    return builder.replace(0, 2, "SetUserAccessoriesReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<SetUserAccessoriesReq, Builder> {
    public Builder() {
    }

    @Override
    public SetUserAccessoriesReq build() {
      return new SetUserAccessoriesReq(super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_SetUserAccessoriesReq extends ProtoAdapter<SetUserAccessoriesReq> {
    public ProtoAdapter_SetUserAccessoriesReq() {
      super(FieldEncoding.LENGTH_DELIMITED, SetUserAccessoriesReq.class, "type.googleapis.com/haiyaa.SetUserAccessoriesReq", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(SetUserAccessoriesReq value) {
      int result = 0;
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, SetUserAccessoriesReq value) throws IOException {
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public SetUserAccessoriesReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public SetUserAccessoriesReq redact(SetUserAccessoriesReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
