// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.StrQuery in public.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class StrQuery extends Message<StrQuery, StrQuery.Builder> {
  public static final ProtoAdapter<StrQuery> ADAPTER = new ProtoAdapter_StrQuery();

  private static final long serialVersionUID = 0L;

  /**
   * 查询参数
   */
  public String strId;

  /**
   * 分页参数
   */
  public int skip;

  /**
   * 分页参数
   */
  public int limit;

  public StrQuery(String strId, int skip, int limit) {
    this(strId, skip, limit, ByteString.EMPTY);
  }

  public StrQuery(String strId, int skip, int limit, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (strId == null) {
      throw new IllegalArgumentException("strId == null");
    }
    this.strId = strId;
    this.skip = skip;
    this.limit = limit;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.strId = strId;
    builder.skip = skip;
    builder.limit = limit;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (strId != null) builder.append(", strId=").append(Internal.sanitize(strId));
    builder.append(", skip=").append(skip);
    builder.append(", limit=").append(limit);
    return builder.replace(0, 2, "StrQuery{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<StrQuery, Builder> {
    public String strId;

    public int skip;

    public int limit;

    public Builder() {
      strId = "";
      skip = 0;
      limit = 0;
    }

    /**
     * 查询参数
     */
    public Builder strId(String strId) {
      this.strId = strId;
      return this;
    }

    /**
     * 分页参数
     */
    public Builder skip(int skip) {
      this.skip = skip;
      return this;
    }

    /**
     * 分页参数
     */
    public Builder limit(int limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public StrQuery build() {
      return new StrQuery(strId, skip, limit, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_StrQuery extends ProtoAdapter<StrQuery> {
    public ProtoAdapter_StrQuery() {
      super(FieldEncoding.LENGTH_DELIMITED, StrQuery.class, "type.googleapis.com/haiyaa.StrQuery", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(StrQuery value) {
      int result = 0;
      if (!Objects.equals(value.strId, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.strId);
      }
      if (!Objects.equals(value.skip, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.skip);
      }
      if (!Objects.equals(value.limit, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(3, value.limit);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, StrQuery value) throws IOException {
      if (!Objects.equals(value.strId, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.strId);
      if (!Objects.equals(value.skip, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.skip);
      if (!Objects.equals(value.limit, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.limit);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public StrQuery decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.strId(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.skip(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.limit(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public StrQuery redact(StrQuery value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
