// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.SvrInCmd in pbcmd.proto
package com.hao.proto;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * 服务器内部命
 */
public enum SvrInCmd implements WireEnum {
  /**
   * 查询用户信息，默认多人
   */
  SvrInCmd_Zero(0),

  /**
   * &haiyaa.IdQuery{}//&haiyaa.UtilRet{}//判断用户操作权限
   */
  IF_I_CAN(9501),

  /**
   * &haiyaa.StrQuery{}//&haiyaa.UtilRet{}//判断用户操作权限
   */
  IF_I_CAN_RSP(9502),

  /**
   * &haiyaa.StrQuery{}//&haiyaa.UtilRet{}//更新用户操作权限
   */
  SET_USER_AUTH(9511),

  /**
   * &haiyaa.StrQuery{}//&haiyaa.UtilRet{}//判断用户操作权限
   */
  SET_USER_AUTH_RSP(9512),

  /**
   * &haiyaa.StrQuery{}//&haiyaa.UtilRet{}//判断用户操作权限
   */
  ASYC_USER_JOURNEY(9521),

  /**
   * &haiyaa.StrQuery{}//&haiyaa.UtilRet{}//用户旅程结束
   */
  USER_JOURNEY_END(9522);

  public static final ProtoAdapter<SvrInCmd> ADAPTER = new ProtoAdapter_SvrInCmd();

  private final int value;

  SvrInCmd(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static SvrInCmd fromValue(int value) {
    switch (value) {
      case 0: return SvrInCmd_Zero;
      case 9501: return IF_I_CAN;
      case 9502: return IF_I_CAN_RSP;
      case 9511: return SET_USER_AUTH;
      case 9512: return SET_USER_AUTH_RSP;
      case 9521: return ASYC_USER_JOURNEY;
      case 9522: return USER_JOURNEY_END;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_SvrInCmd extends EnumAdapter<SvrInCmd> {
    ProtoAdapter_SvrInCmd() {
      super(SvrInCmd.class, Syntax.PROTO_3, SvrInCmd.SvrInCmd_Zero);
    }

    @Override
    protected SvrInCmd fromValue(int value) {
      return SvrInCmd.fromValue(value);
    }
  }
}
