// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.TalkMsg in message.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class TalkMsg extends Message<TalkMsg, TalkMsg.Builder> {
  public static final ProtoAdapter<TalkMsg> ADAPTER = new ProtoAdapter_TalkMsg();

  private static final long serialVersionUID = 0L;

  /**
   * 动态类型;不能为None; TalkType的枚举
   */
  public long type;

  /**
   * 文字
   */
  public String text;

  /**
   * 图片
   */
  public PhotoInfo photo;

  /**
   * 语音
   */
  public AudioInfo audio;

  /**
   * 视频
   */
  public VideoInfo video;

  /**
   * 文件
   */
  public FileInfo file;

  /**
   * 图文链接
   */
  public HyperlinkInfo hyperlink;

  /**
   * 提示
   */
  public TipInfo tip;

  /**
   * 链接文本
   */
  public LinkText linkText;

  public TalkMsg(long type, String text, PhotoInfo photo, AudioInfo audio, VideoInfo video,
      FileInfo file, HyperlinkInfo hyperlink, TipInfo tip, LinkText linkText) {
    this(type, text, photo, audio, video, file, hyperlink, tip, linkText, ByteString.EMPTY);
  }

  public TalkMsg(long type, String text, PhotoInfo photo, AudioInfo audio, VideoInfo video,
      FileInfo file, HyperlinkInfo hyperlink, TipInfo tip, LinkText linkText,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.type = type;
    if (text == null) {
      throw new IllegalArgumentException("text == null");
    }
    this.text = text;
    this.photo = photo;
    this.audio = audio;
    this.video = video;
    this.file = file;
    this.hyperlink = hyperlink;
    this.tip = tip;
    this.linkText = linkText;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.type = type;
    builder.text = text;
    builder.photo = photo;
    builder.audio = audio;
    builder.video = video;
    builder.file = file;
    builder.hyperlink = hyperlink;
    builder.tip = tip;
    builder.linkText = linkText;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", type=").append(type);
    if (text != null) builder.append(", text=").append(Internal.sanitize(text));
    if (photo != null) builder.append(", photo=").append(photo);
    if (audio != null) builder.append(", audio=").append(audio);
    if (video != null) builder.append(", video=").append(video);
    if (file != null) builder.append(", file=").append(file);
    if (hyperlink != null) builder.append(", hyperlink=").append(hyperlink);
    if (tip != null) builder.append(", tip=").append(tip);
    if (linkText != null) builder.append(", linkText=").append(linkText);
    return builder.replace(0, 2, "TalkMsg{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<TalkMsg, Builder> {
    public long type;

    public String text;

    public PhotoInfo photo;

    public AudioInfo audio;

    public VideoInfo video;

    public FileInfo file;

    public HyperlinkInfo hyperlink;

    public TipInfo tip;

    public LinkText linkText;

    public Builder() {
      type = 0L;
      text = "";
    }

    /**
     * 动态类型;不能为None; TalkType的枚举
     */
    public Builder type(long type) {
      this.type = type;
      return this;
    }

    /**
     * 文字
     */
    public Builder text(String text) {
      this.text = text;
      return this;
    }

    /**
     * 图片
     */
    public Builder photo(PhotoInfo photo) {
      this.photo = photo;
      return this;
    }

    /**
     * 语音
     */
    public Builder audio(AudioInfo audio) {
      this.audio = audio;
      return this;
    }

    /**
     * 视频
     */
    public Builder video(VideoInfo video) {
      this.video = video;
      return this;
    }

    /**
     * 文件
     */
    public Builder file(FileInfo file) {
      this.file = file;
      return this;
    }

    /**
     * 图文链接
     */
    public Builder hyperlink(HyperlinkInfo hyperlink) {
      this.hyperlink = hyperlink;
      return this;
    }

    /**
     * 提示
     */
    public Builder tip(TipInfo tip) {
      this.tip = tip;
      return this;
    }

    /**
     * 链接文本
     */
    public Builder linkText(LinkText linkText) {
      this.linkText = linkText;
      return this;
    }

    @Override
    public TalkMsg build() {
      return new TalkMsg(type, text, photo, audio, video, file, hyperlink, tip, linkText, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_TalkMsg extends ProtoAdapter<TalkMsg> {
    public ProtoAdapter_TalkMsg() {
      super(FieldEncoding.LENGTH_DELIMITED, TalkMsg.class, "type.googleapis.com/haiyaa.TalkMsg", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(TalkMsg value) {
      int result = 0;
      if (!Objects.equals(value.type, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(1, value.type);
      }
      if (!Objects.equals(value.text, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.text);
      }
      if (!Objects.equals(value.photo, null)) {
        result += PhotoInfo.ADAPTER.encodedSizeWithTag(3, value.photo);
      }
      if (!Objects.equals(value.audio, null)) {
        result += AudioInfo.ADAPTER.encodedSizeWithTag(4, value.audio);
      }
      if (!Objects.equals(value.video, null)) {
        result += VideoInfo.ADAPTER.encodedSizeWithTag(5, value.video);
      }
      if (!Objects.equals(value.file, null)) {
        result += FileInfo.ADAPTER.encodedSizeWithTag(6, value.file);
      }
      if (!Objects.equals(value.hyperlink, null)) {
        result += HyperlinkInfo.ADAPTER.encodedSizeWithTag(7, value.hyperlink);
      }
      if (!Objects.equals(value.tip, null)) {
        result += TipInfo.ADAPTER.encodedSizeWithTag(8, value.tip);
      }
      if (!Objects.equals(value.linkText, null)) {
        result += LinkText.ADAPTER.encodedSizeWithTag(9, value.linkText);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, TalkMsg value) throws IOException {
      if (!Objects.equals(value.type, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.type);
      if (!Objects.equals(value.text, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.text);
      if (!Objects.equals(value.photo, null)) PhotoInfo.ADAPTER.encodeWithTag(writer, 3, value.photo);
      if (!Objects.equals(value.audio, null)) AudioInfo.ADAPTER.encodeWithTag(writer, 4, value.audio);
      if (!Objects.equals(value.video, null)) VideoInfo.ADAPTER.encodeWithTag(writer, 5, value.video);
      if (!Objects.equals(value.file, null)) FileInfo.ADAPTER.encodeWithTag(writer, 6, value.file);
      if (!Objects.equals(value.hyperlink, null)) HyperlinkInfo.ADAPTER.encodeWithTag(writer, 7, value.hyperlink);
      if (!Objects.equals(value.tip, null)) TipInfo.ADAPTER.encodeWithTag(writer, 8, value.tip);
      if (!Objects.equals(value.linkText, null)) LinkText.ADAPTER.encodeWithTag(writer, 9, value.linkText);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public TalkMsg decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.type(ProtoAdapter.INT64.decode(reader)); break;
          case 2: builder.text(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.photo(PhotoInfo.ADAPTER.decode(reader)); break;
          case 4: builder.audio(AudioInfo.ADAPTER.decode(reader)); break;
          case 5: builder.video(VideoInfo.ADAPTER.decode(reader)); break;
          case 6: builder.file(FileInfo.ADAPTER.decode(reader)); break;
          case 7: builder.hyperlink(HyperlinkInfo.ADAPTER.decode(reader)); break;
          case 8: builder.tip(TipInfo.ADAPTER.decode(reader)); break;
          case 9: builder.linkText(LinkText.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public TalkMsg redact(TalkMsg value) {
      Builder builder = value.newBuilder();
      if (builder.photo != null) builder.photo = PhotoInfo.ADAPTER.redact(builder.photo);
      if (builder.audio != null) builder.audio = AudioInfo.ADAPTER.redact(builder.audio);
      if (builder.video != null) builder.video = VideoInfo.ADAPTER.redact(builder.video);
      if (builder.file != null) builder.file = FileInfo.ADAPTER.redact(builder.file);
      if (builder.hyperlink != null) builder.hyperlink = HyperlinkInfo.ADAPTER.redact(builder.hyperlink);
      if (builder.tip != null) builder.tip = TipInfo.ADAPTER.redact(builder.tip);
      if (builder.linkText != null) builder.linkText = LinkText.ADAPTER.redact(builder.linkText);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
