// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.TcpTokenLoginRsp in haiyaa.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class TcpTokenLoginRsp extends Message<TcpTokenLoginRsp, TcpTokenLoginRsp.Builder> {
  public static final ProtoAdapter<TcpTokenLoginRsp> ADAPTER = new ProtoAdapter_TcpTokenLoginRsp();

  private static final long serialVersionUID = 0L;

  /**
   * TcpTokenLoginRsp = UtilRet
   * 从WebToken中得到的Token，Web登陆后，所有的Head中都要带Uid
   */
  public UtilRet ret;

  public TcpTokenLoginRsp(UtilRet ret) {
    this(ret, ByteString.EMPTY);
  }

  public TcpTokenLoginRsp(UtilRet ret, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.ret = ret;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.ret = ret;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (ret != null) builder.append(", ret=").append(ret);
    return builder.replace(0, 2, "TcpTokenLoginRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<TcpTokenLoginRsp, Builder> {
    public UtilRet ret;

    public Builder() {
    }

    /**
     * TcpTokenLoginRsp = UtilRet
     * 从WebToken中得到的Token，Web登陆后，所有的Head中都要带Uid
     */
    public Builder ret(UtilRet ret) {
      this.ret = ret;
      return this;
    }

    @Override
    public TcpTokenLoginRsp build() {
      return new TcpTokenLoginRsp(ret, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_TcpTokenLoginRsp extends ProtoAdapter<TcpTokenLoginRsp> {
    public ProtoAdapter_TcpTokenLoginRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, TcpTokenLoginRsp.class, "type.googleapis.com/haiyaa.TcpTokenLoginRsp", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(TcpTokenLoginRsp value) {
      int result = 0;
      if (!Objects.equals(value.ret, null)) {
        result += UtilRet.ADAPTER.encodedSizeWithTag(1, value.ret);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, TcpTokenLoginRsp value) throws IOException {
      if (!Objects.equals(value.ret, null)) UtilRet.ADAPTER.encodeWithTag(writer, 1, value.ret);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public TcpTokenLoginRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.ret(UtilRet.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public TcpTokenLoginRsp redact(TcpTokenLoginRsp value) {
      Builder builder = value.newBuilder();
      if (builder.ret != null) builder.ret = UtilRet.ADAPTER.redact(builder.ret);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
