// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.UpgradeInfoS in login.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Objects;
import okio.ByteString;

public final class UpgradeInfoS extends Message<UpgradeInfoS, UpgradeInfoS.Builder> {
  public static final ProtoAdapter<UpgradeInfoS> ADAPTER = new ProtoAdapter_UpgradeInfoS();

  private static final long serialVersionUID = 0L;

  /**
   * 所有的版本升级信息
   */
  public List<UpgradeInfo> upinfos;

  /**
   * 安卓最新版本
   */
  public UpgradeInfo latestAnd;

  /**
   * IOS最新版本
   */
  public UpgradeInfo latestIos;

  public UpgradeInfoS(List<UpgradeInfo> upinfos, UpgradeInfo latestAnd, UpgradeInfo latestIos) {
    this(upinfos, latestAnd, latestIos, ByteString.EMPTY);
  }

  public UpgradeInfoS(List<UpgradeInfo> upinfos, UpgradeInfo latestAnd, UpgradeInfo latestIos,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.upinfos = Internal.immutableCopyOf("upinfos", upinfos);
    this.latestAnd = latestAnd;
    this.latestIos = latestIos;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.upinfos = Internal.copyOf(upinfos);
    builder.latestAnd = latestAnd;
    builder.latestIos = latestIos;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!upinfos.isEmpty()) builder.append(", upinfos=").append(upinfos);
    if (latestAnd != null) builder.append(", latestAnd=").append(latestAnd);
    if (latestIos != null) builder.append(", latestIos=").append(latestIos);
    return builder.replace(0, 2, "UpgradeInfoS{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UpgradeInfoS, Builder> {
    public List<UpgradeInfo> upinfos;

    public UpgradeInfo latestAnd;

    public UpgradeInfo latestIos;

    public Builder() {
      upinfos = Internal.newMutableList();
    }

    /**
     * 所有的版本升级信息
     */
    public Builder upinfos(List<UpgradeInfo> upinfos) {
      Internal.checkElementsNotNull(upinfos);
      this.upinfos = upinfos;
      return this;
    }

    /**
     * 安卓最新版本
     */
    public Builder latestAnd(UpgradeInfo latestAnd) {
      this.latestAnd = latestAnd;
      return this;
    }

    /**
     * IOS最新版本
     */
    public Builder latestIos(UpgradeInfo latestIos) {
      this.latestIos = latestIos;
      return this;
    }

    @Override
    public UpgradeInfoS build() {
      return new UpgradeInfoS(upinfos, latestAnd, latestIos, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UpgradeInfoS extends ProtoAdapter<UpgradeInfoS> {
    public ProtoAdapter_UpgradeInfoS() {
      super(FieldEncoding.LENGTH_DELIMITED, UpgradeInfoS.class, "type.googleapis.com/haiyaa.UpgradeInfoS", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(UpgradeInfoS value) {
      int result = 0;
      result += UpgradeInfo.ADAPTER.asRepeated().encodedSizeWithTag(1, value.upinfos);
      if (!Objects.equals(value.latestAnd, null)) {
        result += UpgradeInfo.ADAPTER.encodedSizeWithTag(2, value.latestAnd);
      }
      if (!Objects.equals(value.latestIos, null)) {
        result += UpgradeInfo.ADAPTER.encodedSizeWithTag(3, value.latestIos);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, UpgradeInfoS value) throws IOException {
      UpgradeInfo.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.upinfos);
      if (!Objects.equals(value.latestAnd, null)) UpgradeInfo.ADAPTER.encodeWithTag(writer, 2, value.latestAnd);
      if (!Objects.equals(value.latestIos, null)) UpgradeInfo.ADAPTER.encodeWithTag(writer, 3, value.latestIos);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UpgradeInfoS decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.upinfos.add(UpgradeInfo.ADAPTER.decode(reader)); break;
          case 2: builder.latestAnd(UpgradeInfo.ADAPTER.decode(reader)); break;
          case 3: builder.latestIos(UpgradeInfo.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public UpgradeInfoS redact(UpgradeInfoS value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.upinfos, UpgradeInfo.ADAPTER);
      if (builder.latestAnd != null) builder.latestAnd = UpgradeInfo.ADAPTER.redact(builder.latestAnd);
      if (builder.latestIos != null) builder.latestIos = UpgradeInfo.ADAPTER.redact(builder.latestIos);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
