// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.UserBitSetting in enums.proto
package com.hao.proto;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * 用户设置参数
 */
public enum UserBitSetting implements WireEnum {
  /**
   * 男/女
   */
  IS_ZERO(0),

  /**
   * 男/女
   */
  IS_GIRL(1),

  /**
   * 会员
   */
  IS_VIP(2),

  /**
   * 是否是开发者
   */
  IS_DEVELOPER(4),

  /**
   * 是否邮件激活
   */
  IS_EMAILACTIVE(8),

  /**
   * 开启好友验证
   */
  IS_NEED_CHECK(16),

  /**
   * 允许发送名片
   */
  IS_SEND_CARD(32),

  /**
   * 允许推荐
   */
  IS_RECOMMEND(64),

  /**
   * 系统封禁
   */
  IS_BANNED(128);

  public static final ProtoAdapter<UserBitSetting> ADAPTER = new ProtoAdapter_UserBitSetting();

  private final int value;

  UserBitSetting(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static UserBitSetting fromValue(int value) {
    switch (value) {
      case 0: return IS_ZERO;
      case 1: return IS_GIRL;
      case 2: return IS_VIP;
      case 4: return IS_DEVELOPER;
      case 8: return IS_EMAILACTIVE;
      case 16: return IS_NEED_CHECK;
      case 32: return IS_SEND_CARD;
      case 64: return IS_RECOMMEND;
      case 128: return IS_BANNED;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_UserBitSetting extends EnumAdapter<UserBitSetting> {
    ProtoAdapter_UserBitSetting() {
      super(UserBitSetting.class, Syntax.PROTO_3, UserBitSetting.IS_ZERO);
    }

    @Override
    protected UserBitSetting fromValue(int value) {
      return UserBitSetting.fromValue(value);
    }
  }
}
