// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.UserAcceS in public.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class UserAcceS extends Message<UserAcceS, UserAcceS.Builder> {
  public static final ProtoAdapter<UserAcceS> ADAPTER = new ProtoAdapter_UserAcceS();

  private static final long serialVersionUID = 0L;

  public List<UserAcce> acces;

  public UserAcceS(List<UserAcce> acces) {
    this(acces, ByteString.EMPTY);
  }

  public UserAcceS(List<UserAcce> acces, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.acces = Internal.immutableCopyOf("acces", acces);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.acces = Internal.copyOf(acces);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!acces.isEmpty()) builder.append(", acces=").append(acces);
    return builder.replace(0, 2, "UserAcceS{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UserAcceS, Builder> {
    public List<UserAcce> acces;

    public Builder() {
      acces = Internal.newMutableList();
    }

    public Builder acces(List<UserAcce> acces) {
      Internal.checkElementsNotNull(acces);
      this.acces = acces;
      return this;
    }

    @Override
    public UserAcceS build() {
      return new UserAcceS(acces, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UserAcceS extends ProtoAdapter<UserAcceS> {
    public ProtoAdapter_UserAcceS() {
      super(FieldEncoding.LENGTH_DELIMITED, UserAcceS.class, "type.googleapis.com/haiyaa.UserAcceS", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(UserAcceS value) {
      int result = 0;
      result += UserAcce.ADAPTER.asRepeated().encodedSizeWithTag(1, value.acces);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, UserAcceS value) throws IOException {
      UserAcce.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.acces);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UserAcceS decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.acces.add(UserAcce.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public UserAcceS redact(UserAcceS value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.acces, UserAcce.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
