// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.UserMsgQuery in message.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class UserMsgQuery extends Message<UserMsgQuery, UserMsgQuery.Builder> {
  public static final ProtoAdapter<UserMsgQuery> ADAPTER = new ProtoAdapter_UserMsgQuery();

  private static final long serialVersionUID = 0L;

  public long userId;

  /**
   * 来自用户, 不填表示所有
   */
  public long fromUid;

  /**
   * 查询类型
   */
  public int type;

  /**
   * 查询参数，必要时填写，如 UserInfoPart
   */
  public int parm;

  /**
   * 查询参数，必要时填, 如果查询返回是列表类，这里表示分页信息
   */
  public int skip;

  /**
   * 查询参数，必要时填写
   */
  public int limit;

  public UserMsgQuery(long userId, long fromUid, int type, int parm, int skip, int limit) {
    this(userId, fromUid, type, parm, skip, limit, ByteString.EMPTY);
  }

  public UserMsgQuery(long userId, long fromUid, int type, int parm, int skip, int limit,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.userId = userId;
    this.fromUid = fromUid;
    this.type = type;
    this.parm = parm;
    this.skip = skip;
    this.limit = limit;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.userId = userId;
    builder.fromUid = fromUid;
    builder.type = type;
    builder.parm = parm;
    builder.skip = skip;
    builder.limit = limit;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", userId=").append(userId);
    builder.append(", fromUid=").append(fromUid);
    builder.append(", type=").append(type);
    builder.append(", parm=").append(parm);
    builder.append(", skip=").append(skip);
    builder.append(", limit=").append(limit);
    return builder.replace(0, 2, "UserMsgQuery{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UserMsgQuery, Builder> {
    public long userId;

    public long fromUid;

    public int type;

    public int parm;

    public int skip;

    public int limit;

    public Builder() {
      userId = 0L;
      fromUid = 0L;
      type = 0;
      parm = 0;
      skip = 0;
      limit = 0;
    }

    public Builder userId(long userId) {
      this.userId = userId;
      return this;
    }

    /**
     * 来自用户, 不填表示所有
     */
    public Builder fromUid(long fromUid) {
      this.fromUid = fromUid;
      return this;
    }

    /**
     * 查询类型
     */
    public Builder type(int type) {
      this.type = type;
      return this;
    }

    /**
     * 查询参数，必要时填写，如 UserInfoPart
     */
    public Builder parm(int parm) {
      this.parm = parm;
      return this;
    }

    /**
     * 查询参数，必要时填, 如果查询返回是列表类，这里表示分页信息
     */
    public Builder skip(int skip) {
      this.skip = skip;
      return this;
    }

    /**
     * 查询参数，必要时填写
     */
    public Builder limit(int limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public UserMsgQuery build() {
      return new UserMsgQuery(userId, fromUid, type, parm, skip, limit, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UserMsgQuery extends ProtoAdapter<UserMsgQuery> {
    public ProtoAdapter_UserMsgQuery() {
      super(FieldEncoding.LENGTH_DELIMITED, UserMsgQuery.class, "type.googleapis.com/haiyaa.UserMsgQuery", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(UserMsgQuery value) {
      int result = 0;
      if (!Objects.equals(value.userId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.userId);
      }
      if (!Objects.equals(value.fromUid, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(2, value.fromUid);
      }
      if (!Objects.equals(value.type, 0)) {
        result += ProtoAdapter.UINT32.encodedSizeWithTag(3, value.type);
      }
      if (!Objects.equals(value.parm, 0)) {
        result += ProtoAdapter.UINT32.encodedSizeWithTag(4, value.parm);
      }
      if (!Objects.equals(value.skip, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(5, value.skip);
      }
      if (!Objects.equals(value.limit, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(6, value.limit);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, UserMsgQuery value) throws IOException {
      if (!Objects.equals(value.userId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.userId);
      if (!Objects.equals(value.fromUid, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.fromUid);
      if (!Objects.equals(value.type, 0)) ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.type);
      if (!Objects.equals(value.parm, 0)) ProtoAdapter.UINT32.encodeWithTag(writer, 4, value.parm);
      if (!Objects.equals(value.skip, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 5, value.skip);
      if (!Objects.equals(value.limit, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 6, value.limit);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UserMsgQuery decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.userId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.fromUid(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.type(ProtoAdapter.UINT32.decode(reader)); break;
          case 4: builder.parm(ProtoAdapter.UINT32.decode(reader)); break;
          case 5: builder.skip(ProtoAdapter.INT32.decode(reader)); break;
          case 6: builder.limit(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public UserMsgQuery redact(UserMsgQuery value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
