// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.UserPwd in login.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 请求密码2密码
 */
public final class UserPwd extends Message<UserPwd, UserPwd.Builder> {
  public static final ProtoAdapter<UserPwd> ADAPTER = new ProtoAdapter_UserPwd();

  private static final long serialVersionUID = 0L;

  /**
   * 账户,这里是手机号或邮箱，邮箱也可以发送验证码
   */
  public String account;

  /**
   * 账户类型，这里是手机号或邮箱，邮箱也可以发送验证码
   */
  public int accType;

  /**
   * 校验码，是短信验证码，或老密码
   */
  public String verify;

  /**
   * 新密码
   */
  public String newPwd;

  public UserPwd(String account, int accType, String verify, String newPwd) {
    this(account, accType, verify, newPwd, ByteString.EMPTY);
  }

  public UserPwd(String account, int accType, String verify, String newPwd,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (account == null) {
      throw new IllegalArgumentException("account == null");
    }
    this.account = account;
    this.accType = accType;
    if (verify == null) {
      throw new IllegalArgumentException("verify == null");
    }
    this.verify = verify;
    if (newPwd == null) {
      throw new IllegalArgumentException("newPwd == null");
    }
    this.newPwd = newPwd;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.account = account;
    builder.accType = accType;
    builder.verify = verify;
    builder.newPwd = newPwd;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (account != null) builder.append(", account=").append(Internal.sanitize(account));
    builder.append(", accType=").append(accType);
    if (verify != null) builder.append(", verify=").append(Internal.sanitize(verify));
    if (newPwd != null) builder.append(", newPwd=").append(Internal.sanitize(newPwd));
    return builder.replace(0, 2, "UserPwd{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UserPwd, Builder> {
    public String account;

    public int accType;

    public String verify;

    public String newPwd;

    public Builder() {
      account = "";
      accType = 0;
      verify = "";
      newPwd = "";
    }

    /**
     * 账户,这里是手机号或邮箱，邮箱也可以发送验证码
     */
    public Builder account(String account) {
      this.account = account;
      return this;
    }

    /**
     * 账户类型，这里是手机号或邮箱，邮箱也可以发送验证码
     */
    public Builder accType(int accType) {
      this.accType = accType;
      return this;
    }

    /**
     * 校验码，是短信验证码，或老密码
     */
    public Builder verify(String verify) {
      this.verify = verify;
      return this;
    }

    /**
     * 新密码
     */
    public Builder newPwd(String newPwd) {
      this.newPwd = newPwd;
      return this;
    }

    @Override
    public UserPwd build() {
      return new UserPwd(account, accType, verify, newPwd, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UserPwd extends ProtoAdapter<UserPwd> {
    public ProtoAdapter_UserPwd() {
      super(FieldEncoding.LENGTH_DELIMITED, UserPwd.class, "type.googleapis.com/haiyaa.UserPwd", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(UserPwd value) {
      int result = 0;
      if (!Objects.equals(value.account, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.account);
      }
      if (!Objects.equals(value.accType, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.accType);
      }
      if (!Objects.equals(value.verify, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.verify);
      }
      if (!Objects.equals(value.newPwd, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(4, value.newPwd);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, UserPwd value) throws IOException {
      if (!Objects.equals(value.account, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.account);
      if (!Objects.equals(value.accType, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.accType);
      if (!Objects.equals(value.verify, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.verify);
      if (!Objects.equals(value.newPwd, "")) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.newPwd);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UserPwd decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.account(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.accType(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.verify(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.newPwd(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public UserPwd redact(UserPwd value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
