// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.UserStatusInS in user.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class UserStatusInS extends Message<UserStatusInS, UserStatusInS.Builder> {
  public static final ProtoAdapter<UserStatusInS> ADAPTER = new ProtoAdapter_UserStatusInS();

  private static final long serialVersionUID = 0L;

  public List<UserStatusIn> stss;

  public UserStatusInS(List<UserStatusIn> stss) {
    this(stss, ByteString.EMPTY);
  }

  public UserStatusInS(List<UserStatusIn> stss, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.stss = Internal.immutableCopyOf("stss", stss);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.stss = Internal.copyOf(stss);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!stss.isEmpty()) builder.append(", stss=").append(stss);
    return builder.replace(0, 2, "UserStatusInS{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UserStatusInS, Builder> {
    public List<UserStatusIn> stss;

    public Builder() {
      stss = Internal.newMutableList();
    }

    public Builder stss(List<UserStatusIn> stss) {
      Internal.checkElementsNotNull(stss);
      this.stss = stss;
      return this;
    }

    @Override
    public UserStatusInS build() {
      return new UserStatusInS(stss, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UserStatusInS extends ProtoAdapter<UserStatusInS> {
    public ProtoAdapter_UserStatusInS() {
      super(FieldEncoding.LENGTH_DELIMITED, UserStatusInS.class, "type.googleapis.com/haiyaa.UserStatusInS", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(UserStatusInS value) {
      int result = 0;
      result += UserStatusIn.ADAPTER.asRepeated().encodedSizeWithTag(1, value.stss);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, UserStatusInS value) throws IOException {
      UserStatusIn.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.stss);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UserStatusInS decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.stss.add(UserStatusIn.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public UserStatusInS redact(UserStatusInS value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.stss, UserStatusIn.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
