// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.UserRelationS in user.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * 不同区域，展示信息内容不一样，用于关系列表中
 */
public final class UserRelationS extends Message<UserRelationS, UserRelationS.Builder> {
  public static final ProtoAdapter<UserRelationS> ADAPTER = new ProtoAdapter_UserRelationS();

  private static final long serialVersionUID = 0L;

  public List<UserRelation> relations;

  public UserRelationS(List<UserRelation> relations) {
    this(relations, ByteString.EMPTY);
  }

  public UserRelationS(List<UserRelation> relations, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.relations = Internal.immutableCopyOf("relations", relations);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.relations = Internal.copyOf(relations);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!relations.isEmpty()) builder.append(", relations=").append(relations);
    return builder.replace(0, 2, "UserRelationS{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UserRelationS, Builder> {
    public List<UserRelation> relations;

    public Builder() {
      relations = Internal.newMutableList();
    }

    public Builder relations(List<UserRelation> relations) {
      Internal.checkElementsNotNull(relations);
      this.relations = relations;
      return this;
    }

    @Override
    public UserRelationS build() {
      return new UserRelationS(relations, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UserRelationS extends ProtoAdapter<UserRelationS> {
    public ProtoAdapter_UserRelationS() {
      super(FieldEncoding.LENGTH_DELIMITED, UserRelationS.class, "type.googleapis.com/haiyaa.UserRelationS", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(UserRelationS value) {
      int result = 0;
      result += UserRelation.ADAPTER.asRepeated().encodedSizeWithTag(1, value.relations);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, UserRelationS value) throws IOException {
      UserRelation.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.relations);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UserRelationS decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.relations.add(UserRelation.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public UserRelationS redact(UserRelationS value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.relations, UserRelation.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
