// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.UserMission in user.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Objects;
import okio.ByteString;

/**
 * //用户等级信息
 */
public final class UserMission extends Message<UserMission, UserMission.Builder> {
  public static final ProtoAdapter<UserMission> ADAPTER = new ProtoAdapter_UserMission();

  private static final long serialVersionUID = 0L;

  /**
   * 用户id
   */
  public long userId;

  /**
   * 佣金等级Id
   */
  public int missionId;

  /**
   * 佣金比例[45-75]
   */
  public int mission;

  /**
   * 今日在麦时长，单位分钟
   */
  public int curMicro;

  /**
   * 过去7天的麦上时间，单位分钟
   */
  public List<Integer> preMicros;

  public UserMission(long userId, int missionId, int mission, int curMicro,
      List<Integer> preMicros) {
    this(userId, missionId, mission, curMicro, preMicros, ByteString.EMPTY);
  }

  public UserMission(long userId, int missionId, int mission, int curMicro, List<Integer> preMicros,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.userId = userId;
    this.missionId = missionId;
    this.mission = mission;
    this.curMicro = curMicro;
    this.preMicros = Internal.immutableCopyOf("preMicros", preMicros);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.userId = userId;
    builder.missionId = missionId;
    builder.mission = mission;
    builder.curMicro = curMicro;
    builder.preMicros = Internal.copyOf(preMicros);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", userId=").append(userId);
    builder.append(", missionId=").append(missionId);
    builder.append(", mission=").append(mission);
    builder.append(", curMicro=").append(curMicro);
    if (!preMicros.isEmpty()) builder.append(", preMicros=").append(preMicros);
    return builder.replace(0, 2, "UserMission{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UserMission, Builder> {
    public long userId;

    public int missionId;

    public int mission;

    public int curMicro;

    public List<Integer> preMicros;

    public Builder() {
      userId = 0L;
      missionId = 0;
      mission = 0;
      curMicro = 0;
      preMicros = Internal.newMutableList();
    }

    /**
     * 用户id
     */
    public Builder userId(long userId) {
      this.userId = userId;
      return this;
    }

    /**
     * 佣金等级Id
     */
    public Builder missionId(int missionId) {
      this.missionId = missionId;
      return this;
    }

    /**
     * 佣金比例[45-75]
     */
    public Builder mission(int mission) {
      this.mission = mission;
      return this;
    }

    /**
     * 今日在麦时长，单位分钟
     */
    public Builder curMicro(int curMicro) {
      this.curMicro = curMicro;
      return this;
    }

    /**
     * 过去7天的麦上时间，单位分钟
     */
    public Builder preMicros(List<Integer> preMicros) {
      Internal.checkElementsNotNull(preMicros);
      this.preMicros = preMicros;
      return this;
    }

    @Override
    public UserMission build() {
      return new UserMission(userId, missionId, mission, curMicro, preMicros, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UserMission extends ProtoAdapter<UserMission> {
    public ProtoAdapter_UserMission() {
      super(FieldEncoding.LENGTH_DELIMITED, UserMission.class, "type.googleapis.com/haiyaa.UserMission", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(UserMission value) {
      int result = 0;
      if (!Objects.equals(value.userId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.userId);
      }
      if (!Objects.equals(value.missionId, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.missionId);
      }
      if (!Objects.equals(value.mission, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(3, value.mission);
      }
      if (!Objects.equals(value.curMicro, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(4, value.curMicro);
      }
      result += ProtoAdapter.INT32.asPacked().encodedSizeWithTag(5, value.preMicros);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, UserMission value) throws IOException {
      if (!Objects.equals(value.userId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.userId);
      if (!Objects.equals(value.missionId, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.missionId);
      if (!Objects.equals(value.mission, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.mission);
      if (!Objects.equals(value.curMicro, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.curMicro);
      ProtoAdapter.INT32.asPacked().encodeWithTag(writer, 5, value.preMicros);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UserMission decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.userId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.missionId(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.mission(ProtoAdapter.INT32.decode(reader)); break;
          case 4: builder.curMicro(ProtoAdapter.INT32.decode(reader)); break;
          case 5: builder.preMicros.add(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public UserMission redact(UserMission value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
