// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.UserNeedBit in enums.proto
package com.hao.proto;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum UserNeedBit implements WireEnum {
  UNB_Zero(0),

  /**
   * 	普通展示类
   */
  UNB_SHOW(1),

  /**
   * 	用户个性设定类
   */
  UNB_SETTING(2),

  /**
   * 	账户及第三方信息类
   */
  UNB_ACCOUNT(4),

  /**
   * 	账户社交统计类
   */
  UNB_STATIC(8);

  public static final ProtoAdapter<UserNeedBit> ADAPTER = new ProtoAdapter_UserNeedBit();

  private final int value;

  UserNeedBit(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static UserNeedBit fromValue(int value) {
    switch (value) {
      case 0: return UNB_Zero;
      case 1: return UNB_SHOW;
      case 2: return UNB_SETTING;
      case 4: return UNB_ACCOUNT;
      case 8: return UNB_STATIC;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_UserNeedBit extends EnumAdapter<UserNeedBit> {
    ProtoAdapter_UserNeedBit() {
      super(UserNeedBit.class, Syntax.PROTO_3, UserNeedBit.UNB_Zero);
    }

    @Override
    protected UserNeedBit fromValue(int value) {
      return UserNeedBit.fromValue(value);
    }
  }
}
