// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.UserProhibit in user.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 用户封禁
 */
public final class UserProhibit extends Message<UserProhibit, UserProhibit.Builder> {
  public static final ProtoAdapter<UserProhibit> ADAPTER = new ProtoAdapter_UserProhibit();

  private static final long serialVersionUID = 0L;

  /**
   * 封禁Id
   */
  public long userId;

  /**
   * 封禁原因
   */
  public String reason;

  /**
   * 封禁截止时间
   */
  public long banTime;

  public UserProhibit(long userId, String reason, long banTime) {
    this(userId, reason, banTime, ByteString.EMPTY);
  }

  public UserProhibit(long userId, String reason, long banTime, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.userId = userId;
    if (reason == null) {
      throw new IllegalArgumentException("reason == null");
    }
    this.reason = reason;
    this.banTime = banTime;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.userId = userId;
    builder.reason = reason;
    builder.banTime = banTime;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", userId=").append(userId);
    if (reason != null) builder.append(", reason=").append(Internal.sanitize(reason));
    builder.append(", banTime=").append(banTime);
    return builder.replace(0, 2, "UserProhibit{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UserProhibit, Builder> {
    public long userId;

    public String reason;

    public long banTime;

    public Builder() {
      userId = 0L;
      reason = "";
      banTime = 0L;
    }

    /**
     * 封禁Id
     */
    public Builder userId(long userId) {
      this.userId = userId;
      return this;
    }

    /**
     * 封禁原因
     */
    public Builder reason(String reason) {
      this.reason = reason;
      return this;
    }

    /**
     * 封禁截止时间
     */
    public Builder banTime(long banTime) {
      this.banTime = banTime;
      return this;
    }

    @Override
    public UserProhibit build() {
      return new UserProhibit(userId, reason, banTime, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UserProhibit extends ProtoAdapter<UserProhibit> {
    public ProtoAdapter_UserProhibit() {
      super(FieldEncoding.LENGTH_DELIMITED, UserProhibit.class, "type.googleapis.com/haiyaa.UserProhibit", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(UserProhibit value) {
      int result = 0;
      if (!Objects.equals(value.userId, 0L)) {
        result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.userId);
      }
      if (!Objects.equals(value.reason, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.reason);
      }
      if (!Objects.equals(value.banTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(3, value.banTime);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, UserProhibit value) throws IOException {
      if (!Objects.equals(value.userId, 0L)) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.userId);
      if (!Objects.equals(value.reason, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.reason);
      if (!Objects.equals(value.banTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 3, value.banTime);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UserProhibit decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.userId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.reason(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.banTime(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public UserProhibit redact(UserProhibit value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
