// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.UserPage in haiyaa.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class UserPage extends Message<UserPage, UserPage.Builder> {
  public static final ProtoAdapter<UserPage> ADAPTER = new ProtoAdapter_UserPage();

  private static final long serialVersionUID = 0L;

  /**
   * 基础信息，资金，等级，
   */
  public UserBase user;

  /**
   * 和我的关系 1 已关注 2 未关注 3 已互关
   */
  public int relation;

  public UserState ustate;

  public WelthInfo uwelth;

  /**
   * 总计礼物数
   */
  public int totalGift;

  /**
   * 已解锁多少个
   */
  public int unlockGift;

  /**
   * 礼物墙
   */
  public GiftRecordS giftWall;

  public UserPage(UserBase user, int relation, UserState ustate, WelthInfo uwelth, int totalGift,
      int unlockGift, GiftRecordS giftWall) {
    this(user, relation, ustate, uwelth, totalGift, unlockGift, giftWall, ByteString.EMPTY);
  }

  public UserPage(UserBase user, int relation, UserState ustate, WelthInfo uwelth, int totalGift,
      int unlockGift, GiftRecordS giftWall, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.user = user;
    this.relation = relation;
    this.ustate = ustate;
    this.uwelth = uwelth;
    this.totalGift = totalGift;
    this.unlockGift = unlockGift;
    this.giftWall = giftWall;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.user = user;
    builder.relation = relation;
    builder.ustate = ustate;
    builder.uwelth = uwelth;
    builder.totalGift = totalGift;
    builder.unlockGift = unlockGift;
    builder.giftWall = giftWall;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (user != null) builder.append(", user=").append(user);
    builder.append(", relation=").append(relation);
    if (ustate != null) builder.append(", ustate=").append(ustate);
    if (uwelth != null) builder.append(", uwelth=").append(uwelth);
    builder.append(", totalGift=").append(totalGift);
    builder.append(", unlockGift=").append(unlockGift);
    if (giftWall != null) builder.append(", giftWall=").append(giftWall);
    return builder.replace(0, 2, "UserPage{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UserPage, Builder> {
    public UserBase user;

    public int relation;

    public UserState ustate;

    public WelthInfo uwelth;

    public int totalGift;

    public int unlockGift;

    public GiftRecordS giftWall;

    public Builder() {
      relation = 0;
      totalGift = 0;
      unlockGift = 0;
    }

    /**
     * 基础信息，资金，等级，
     */
    public Builder user(UserBase user) {
      this.user = user;
      return this;
    }

    /**
     * 和我的关系 1 已关注 2 未关注 3 已互关
     */
    public Builder relation(int relation) {
      this.relation = relation;
      return this;
    }

    public Builder ustate(UserState ustate) {
      this.ustate = ustate;
      return this;
    }

    public Builder uwelth(WelthInfo uwelth) {
      this.uwelth = uwelth;
      return this;
    }

    /**
     * 总计礼物数
     */
    public Builder totalGift(int totalGift) {
      this.totalGift = totalGift;
      return this;
    }

    /**
     * 已解锁多少个
     */
    public Builder unlockGift(int unlockGift) {
      this.unlockGift = unlockGift;
      return this;
    }

    /**
     * 礼物墙
     */
    public Builder giftWall(GiftRecordS giftWall) {
      this.giftWall = giftWall;
      return this;
    }

    @Override
    public UserPage build() {
      return new UserPage(user, relation, ustate, uwelth, totalGift, unlockGift, giftWall, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UserPage extends ProtoAdapter<UserPage> {
    public ProtoAdapter_UserPage() {
      super(FieldEncoding.LENGTH_DELIMITED, UserPage.class, "type.googleapis.com/haiyaa.UserPage", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(UserPage value) {
      int result = 0;
      if (!Objects.equals(value.user, null)) {
        result += UserBase.ADAPTER.encodedSizeWithTag(1, value.user);
      }
      if (!Objects.equals(value.relation, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.relation);
      }
      if (!Objects.equals(value.ustate, null)) {
        result += UserState.ADAPTER.encodedSizeWithTag(3, value.ustate);
      }
      if (!Objects.equals(value.uwelth, null)) {
        result += WelthInfo.ADAPTER.encodedSizeWithTag(4, value.uwelth);
      }
      if (!Objects.equals(value.totalGift, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(6, value.totalGift);
      }
      if (!Objects.equals(value.unlockGift, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(7, value.unlockGift);
      }
      if (!Objects.equals(value.giftWall, null)) {
        result += GiftRecordS.ADAPTER.encodedSizeWithTag(8, value.giftWall);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, UserPage value) throws IOException {
      if (!Objects.equals(value.user, null)) UserBase.ADAPTER.encodeWithTag(writer, 1, value.user);
      if (!Objects.equals(value.relation, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.relation);
      if (!Objects.equals(value.ustate, null)) UserState.ADAPTER.encodeWithTag(writer, 3, value.ustate);
      if (!Objects.equals(value.uwelth, null)) WelthInfo.ADAPTER.encodeWithTag(writer, 4, value.uwelth);
      if (!Objects.equals(value.totalGift, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 6, value.totalGift);
      if (!Objects.equals(value.unlockGift, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 7, value.unlockGift);
      if (!Objects.equals(value.giftWall, null)) GiftRecordS.ADAPTER.encodeWithTag(writer, 8, value.giftWall);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UserPage decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.user(UserBase.ADAPTER.decode(reader)); break;
          case 2: builder.relation(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.ustate(UserState.ADAPTER.decode(reader)); break;
          case 4: builder.uwelth(WelthInfo.ADAPTER.decode(reader)); break;
          case 6: builder.totalGift(ProtoAdapter.INT32.decode(reader)); break;
          case 7: builder.unlockGift(ProtoAdapter.INT32.decode(reader)); break;
          case 8: builder.giftWall(GiftRecordS.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public UserPage redact(UserPage value) {
      Builder builder = value.newBuilder();
      if (builder.user != null) builder.user = UserBase.ADAPTER.redact(builder.user);
      if (builder.ustate != null) builder.ustate = UserState.ADAPTER.redact(builder.ustate);
      if (builder.uwelth != null) builder.uwelth = WelthInfo.ADAPTER.redact(builder.uwelth);
      if (builder.giftWall != null) builder.giftWall = GiftRecordS.ADAPTER.redact(builder.giftWall);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
