// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.UserStateS in user.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class UserStateS extends Message<UserStateS, UserStateS.Builder> {
  public static final ProtoAdapter<UserStateS> ADAPTER = new ProtoAdapter_UserStateS();

  private static final long serialVersionUID = 0L;

  /**
   * 用户状态
   */
  public List<UserState> status;

  public UserStateS(List<UserState> status) {
    this(status, ByteString.EMPTY);
  }

  public UserStateS(List<UserState> status, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.status = Internal.immutableCopyOf("status", status);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.status = Internal.copyOf(status);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!status.isEmpty()) builder.append(", status=").append(status);
    return builder.replace(0, 2, "UserStateS{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UserStateS, Builder> {
    public List<UserState> status;

    public Builder() {
      status = Internal.newMutableList();
    }

    /**
     * 用户状态
     */
    public Builder status(List<UserState> status) {
      Internal.checkElementsNotNull(status);
      this.status = status;
      return this;
    }

    @Override
    public UserStateS build() {
      return new UserStateS(status, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UserStateS extends ProtoAdapter<UserStateS> {
    public ProtoAdapter_UserStateS() {
      super(FieldEncoding.LENGTH_DELIMITED, UserStateS.class, "type.googleapis.com/haiyaa.UserStateS", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(UserStateS value) {
      int result = 0;
      result += UserState.ADAPTER.asRepeated().encodedSizeWithTag(1, value.status);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, UserStateS value) throws IOException {
      UserState.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.status);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UserStateS decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.status.add(UserState.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public UserStateS redact(UserStateS value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.status, UserState.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
