// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.UtilRet in public.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class UtilRet extends Message<UtilRet, UtilRet.Builder> {
  public static final ProtoAdapter<UtilRet> ADAPTER = new ProtoAdapter_UtilRet();

  private static final long serialVersionUID = 0L;

  /**
   * 返回码
   */
  public int retCode;

  /**
   * 后台操作时间; // 错误码
   */
  public long retTime;

  /**
   * 返回文案
   */
  public String retTxt;

  public UtilRet(int retCode, long retTime, String retTxt) {
    this(retCode, retTime, retTxt, ByteString.EMPTY);
  }

  public UtilRet(int retCode, long retTime, String retTxt, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.retCode = retCode;
    this.retTime = retTime;
    if (retTxt == null) {
      throw new IllegalArgumentException("retTxt == null");
    }
    this.retTxt = retTxt;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.retCode = retCode;
    builder.retTime = retTime;
    builder.retTxt = retTxt;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", retCode=").append(retCode);
    builder.append(", retTime=").append(retTime);
    if (retTxt != null) builder.append(", retTxt=").append(Internal.sanitize(retTxt));
    return builder.replace(0, 2, "UtilRet{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UtilRet, Builder> {
    public int retCode;

    public long retTime;

    public String retTxt;

    public Builder() {
      retCode = 0;
      retTime = 0L;
      retTxt = "";
    }

    /**
     * 返回码
     */
    public Builder retCode(int retCode) {
      this.retCode = retCode;
      return this;
    }

    /**
     * 后台操作时间; // 错误码
     */
    public Builder retTime(long retTime) {
      this.retTime = retTime;
      return this;
    }

    /**
     * 返回文案
     */
    public Builder retTxt(String retTxt) {
      this.retTxt = retTxt;
      return this;
    }

    @Override
    public UtilRet build() {
      return new UtilRet(retCode, retTime, retTxt, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UtilRet extends ProtoAdapter<UtilRet> {
    public ProtoAdapter_UtilRet() {
      super(FieldEncoding.LENGTH_DELIMITED, UtilRet.class, "type.googleapis.com/haiyaa.UtilRet", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(UtilRet value) {
      int result = 0;
      if (!Objects.equals(value.retCode, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(1, value.retCode);
      }
      if (!Objects.equals(value.retTime, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(2, value.retTime);
      }
      if (!Objects.equals(value.retTxt, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.retTxt);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, UtilRet value) throws IOException {
      if (!Objects.equals(value.retCode, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.retCode);
      if (!Objects.equals(value.retTime, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 2, value.retTime);
      if (!Objects.equals(value.retTxt, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.retTxt);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UtilRet decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.retCode(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.retTime(ProtoAdapter.INT64.decode(reader)); break;
          case 3: builder.retTxt(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public UtilRet redact(UtilRet value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
