// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.VerifyInfo in public.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 认证信息
 */
public final class VerifyInfo extends Message<VerifyInfo, VerifyInfo.Builder> {
  public static final ProtoAdapter<VerifyInfo> ADAPTER = new ProtoAdapter_VerifyInfo();

  private static final long serialVersionUID = 0L;

  public int verifyId;

  public String verifyName;

  public String verifyIcon;

  public VerifyInfo(int verifyId, String verifyName, String verifyIcon) {
    this(verifyId, verifyName, verifyIcon, ByteString.EMPTY);
  }

  public VerifyInfo(int verifyId, String verifyName, String verifyIcon, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.verifyId = verifyId;
    if (verifyName == null) {
      throw new IllegalArgumentException("verifyName == null");
    }
    this.verifyName = verifyName;
    if (verifyIcon == null) {
      throw new IllegalArgumentException("verifyIcon == null");
    }
    this.verifyIcon = verifyIcon;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.verifyId = verifyId;
    builder.verifyName = verifyName;
    builder.verifyIcon = verifyIcon;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", verifyId=").append(verifyId);
    if (verifyName != null) builder.append(", verifyName=").append(Internal.sanitize(verifyName));
    if (verifyIcon != null) builder.append(", verifyIcon=").append(Internal.sanitize(verifyIcon));
    return builder.replace(0, 2, "VerifyInfo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<VerifyInfo, Builder> {
    public int verifyId;

    public String verifyName;

    public String verifyIcon;

    public Builder() {
      verifyId = 0;
      verifyName = "";
      verifyIcon = "";
    }

    public Builder verifyId(int verifyId) {
      this.verifyId = verifyId;
      return this;
    }

    public Builder verifyName(String verifyName) {
      this.verifyName = verifyName;
      return this;
    }

    public Builder verifyIcon(String verifyIcon) {
      this.verifyIcon = verifyIcon;
      return this;
    }

    @Override
    public VerifyInfo build() {
      return new VerifyInfo(verifyId, verifyName, verifyIcon, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_VerifyInfo extends ProtoAdapter<VerifyInfo> {
    public ProtoAdapter_VerifyInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, VerifyInfo.class, "type.googleapis.com/haiyaa.VerifyInfo", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(VerifyInfo value) {
      int result = 0;
      if (!Objects.equals(value.verifyId, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(1, value.verifyId);
      }
      if (!Objects.equals(value.verifyName, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.verifyName);
      }
      if (!Objects.equals(value.verifyIcon, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.verifyIcon);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, VerifyInfo value) throws IOException {
      if (!Objects.equals(value.verifyId, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.verifyId);
      if (!Objects.equals(value.verifyName, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.verifyName);
      if (!Objects.equals(value.verifyIcon, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.verifyIcon);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public VerifyInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.verifyId(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.verifyName(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.verifyIcon(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public VerifyInfo redact(VerifyInfo value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
