// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.VideoInfo in public.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class VideoInfo extends Message<VideoInfo, VideoInfo.Builder> {
  public static final ProtoAdapter<VideoInfo> ADAPTER = new ProtoAdapter_VideoInfo();

  private static final long serialVersionUID = 0L;

  public String name;

  /**
   * 用户备注的视频信息
   */
  public String note;

  /**
   * 视频文件时长;
   */
  public long secs;

  /**
   * 文件大小;
   */
  public long size;

  /**
   * 视频链接（或者说是视频原链接）
   */
  public String url;

  /**
   * 缩略图url;
   */
  public String thumbnail;

  public long width;

  public long height;

  /**
   * 我们存储过的视频链接（我们下载后转存到自己视频仓库后的新链接）
   */
  public String weUrl;

  public VideoInfo(String name, String note, long secs, long size, String url, String thumbnail,
      long width, long height, String weUrl) {
    this(name, note, secs, size, url, thumbnail, width, height, weUrl, ByteString.EMPTY);
  }

  public VideoInfo(String name, String note, long secs, long size, String url, String thumbnail,
      long width, long height, String weUrl, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (name == null) {
      throw new IllegalArgumentException("name == null");
    }
    this.name = name;
    if (note == null) {
      throw new IllegalArgumentException("note == null");
    }
    this.note = note;
    this.secs = secs;
    this.size = size;
    if (url == null) {
      throw new IllegalArgumentException("url == null");
    }
    this.url = url;
    if (thumbnail == null) {
      throw new IllegalArgumentException("thumbnail == null");
    }
    this.thumbnail = thumbnail;
    this.width = width;
    this.height = height;
    if (weUrl == null) {
      throw new IllegalArgumentException("weUrl == null");
    }
    this.weUrl = weUrl;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.name = name;
    builder.note = note;
    builder.secs = secs;
    builder.size = size;
    builder.url = url;
    builder.thumbnail = thumbnail;
    builder.width = width;
    builder.height = height;
    builder.weUrl = weUrl;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (name != null) builder.append(", name=").append(Internal.sanitize(name));
    if (note != null) builder.append(", note=").append(Internal.sanitize(note));
    builder.append(", secs=").append(secs);
    builder.append(", size=").append(size);
    if (url != null) builder.append(", url=").append(Internal.sanitize(url));
    if (thumbnail != null) builder.append(", thumbnail=").append(Internal.sanitize(thumbnail));
    builder.append(", width=").append(width);
    builder.append(", height=").append(height);
    if (weUrl != null) builder.append(", weUrl=").append(Internal.sanitize(weUrl));
    return builder.replace(0, 2, "VideoInfo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<VideoInfo, Builder> {
    public String name;

    public String note;

    public long secs;

    public long size;

    public String url;

    public String thumbnail;

    public long width;

    public long height;

    public String weUrl;

    public Builder() {
      name = "";
      note = "";
      secs = 0L;
      size = 0L;
      url = "";
      thumbnail = "";
      width = 0L;
      height = 0L;
      weUrl = "";
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /**
     * 用户备注的视频信息
     */
    public Builder note(String note) {
      this.note = note;
      return this;
    }

    /**
     * 视频文件时长;
     */
    public Builder secs(long secs) {
      this.secs = secs;
      return this;
    }

    /**
     * 文件大小;
     */
    public Builder size(long size) {
      this.size = size;
      return this;
    }

    /**
     * 视频链接（或者说是视频原链接）
     */
    public Builder url(String url) {
      this.url = url;
      return this;
    }

    /**
     * 缩略图url;
     */
    public Builder thumbnail(String thumbnail) {
      this.thumbnail = thumbnail;
      return this;
    }

    public Builder width(long width) {
      this.width = width;
      return this;
    }

    public Builder height(long height) {
      this.height = height;
      return this;
    }

    /**
     * 我们存储过的视频链接（我们下载后转存到自己视频仓库后的新链接）
     */
    public Builder weUrl(String weUrl) {
      this.weUrl = weUrl;
      return this;
    }

    @Override
    public VideoInfo build() {
      return new VideoInfo(name, note, secs, size, url, thumbnail, width, height, weUrl, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_VideoInfo extends ProtoAdapter<VideoInfo> {
    public ProtoAdapter_VideoInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, VideoInfo.class, "type.googleapis.com/haiyaa.VideoInfo", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(VideoInfo value) {
      int result = 0;
      if (!Objects.equals(value.name, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.name);
      }
      if (!Objects.equals(value.note, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.note);
      }
      if (!Objects.equals(value.secs, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(3, value.secs);
      }
      if (!Objects.equals(value.size, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(4, value.size);
      }
      if (!Objects.equals(value.url, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(5, value.url);
      }
      if (!Objects.equals(value.thumbnail, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(6, value.thumbnail);
      }
      if (!Objects.equals(value.width, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(7, value.width);
      }
      if (!Objects.equals(value.height, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(8, value.height);
      }
      if (!Objects.equals(value.weUrl, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(9, value.weUrl);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, VideoInfo value) throws IOException {
      if (!Objects.equals(value.name, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name);
      if (!Objects.equals(value.note, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.note);
      if (!Objects.equals(value.secs, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 3, value.secs);
      if (!Objects.equals(value.size, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 4, value.size);
      if (!Objects.equals(value.url, "")) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.url);
      if (!Objects.equals(value.thumbnail, "")) ProtoAdapter.STRING.encodeWithTag(writer, 6, value.thumbnail);
      if (!Objects.equals(value.width, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 7, value.width);
      if (!Objects.equals(value.height, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 8, value.height);
      if (!Objects.equals(value.weUrl, "")) ProtoAdapter.STRING.encodeWithTag(writer, 9, value.weUrl);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public VideoInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.name(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.note(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.secs(ProtoAdapter.INT64.decode(reader)); break;
          case 4: builder.size(ProtoAdapter.INT64.decode(reader)); break;
          case 5: builder.url(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.thumbnail(ProtoAdapter.STRING.decode(reader)); break;
          case 7: builder.width(ProtoAdapter.INT64.decode(reader)); break;
          case 8: builder.height(ProtoAdapter.INT64.decode(reader)); break;
          case 9: builder.weUrl(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public VideoInfo redact(VideoInfo value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
