// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.WebTokenLoginRsp in haiyaa.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class WebTokenLoginRsp extends Message<WebTokenLoginRsp, WebTokenLoginRsp.Builder> {
  public static final ProtoAdapter<WebTokenLoginRsp> ADAPTER = new ProtoAdapter_WebTokenLoginRsp();

  private static final long serialVersionUID = 0L;

  public int State;

  public LoginInfo login;

  public WebTokenLoginRsp(int State, LoginInfo login) {
    this(State, login, ByteString.EMPTY);
  }

  public WebTokenLoginRsp(int State, LoginInfo login, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.State = State;
    this.login = login;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.State = State;
    builder.login = login;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", State=").append(State);
    if (login != null) builder.append(", login=").append(login);
    return builder.replace(0, 2, "WebTokenLoginRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<WebTokenLoginRsp, Builder> {
    public int State;

    public LoginInfo login;

    public Builder() {
      State = 0;
    }

    public Builder State(int State) {
      this.State = State;
      return this;
    }

    public Builder login(LoginInfo login) {
      this.login = login;
      return this;
    }

    @Override
    public WebTokenLoginRsp build() {
      return new WebTokenLoginRsp(State, login, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_WebTokenLoginRsp extends ProtoAdapter<WebTokenLoginRsp> {
    public ProtoAdapter_WebTokenLoginRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, WebTokenLoginRsp.class, "type.googleapis.com/haiyaa.WebTokenLoginRsp", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(WebTokenLoginRsp value) {
      int result = 0;
      if (!Objects.equals(value.State, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(1, value.State);
      }
      if (!Objects.equals(value.login, null)) {
        result += LoginInfo.ADAPTER.encodedSizeWithTag(2, value.login);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, WebTokenLoginRsp value) throws IOException {
      if (!Objects.equals(value.State, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.State);
      if (!Objects.equals(value.login, null)) LoginInfo.ADAPTER.encodeWithTag(writer, 2, value.login);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public WebTokenLoginRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.State(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.login(LoginInfo.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public WebTokenLoginRsp redact(WebTokenLoginRsp value) {
      Builder builder = value.newBuilder();
      if (builder.login != null) builder.login = LoginInfo.ADAPTER.redact(builder.login);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
