// Code generated by Wire protocol buffer compiler, do not edit.
// Source: haiyaa.WelthInfo in user.proto
package com.hao.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * 主态财富类信息
 */
public final class WelthInfo extends Message<WelthInfo, WelthInfo.Builder> {
  public static final ProtoAdapter<WelthInfo> ADAPTER = new ProtoAdapter_WelthInfo();

  private static final long serialVersionUID = 0L;

  /**
   * 礼物数量
   */
  public int giftNum;

  /**
   * 爱心数量
   */
  public int loveNum;

  /**
   * 钻石数量
   */
  public int coinNum;

  /**
   * 银币数量
   */
  public int silverNum;

  /**
   * 黑钻数量
   */
  public double bCoinNum;

  /**
   * 财富数量
   */
  public int welthNum;

  /**
   * 魅力数量
   */
  public int charmNum;

  /**
   * 财富等级
   */
  public int levelid;

  /**
   * int32     ticketNum 	= 11;	//奖券数量
   * int32     pointNum 		= 12;	//积分数量
   * 来访数量
   */
  public int viewNum;

  /**
   * int32     missionId    = 16;   //提现等级
   * int32     walletId     = 17;   //钱包称号
   * 是否开通提现，0 未开通，开通时间
   */
  public long openDraw;

  /**
   * 波场账号
   */
  public String tronAddr;

  /**
   * 钱包账号绑定时间
   */
  public long tronBind;

  /**
   * 提现跳转
   */
  public String drawJump;

  /**
   * 提现积分（可提现的黑钻数量）
   */
  public int drawPoint;

  public WelthInfo(int giftNum, int loveNum, int coinNum, int silverNum, double bCoinNum,
      int welthNum, int charmNum, int levelid, int viewNum, long openDraw, String tronAddr,
      long tronBind, String drawJump, int drawPoint) {
    this(giftNum, loveNum, coinNum, silverNum, bCoinNum, welthNum, charmNum, levelid, viewNum, openDraw, tronAddr, tronBind, drawJump, drawPoint, ByteString.EMPTY);
  }

  public WelthInfo(int giftNum, int loveNum, int coinNum, int silverNum, double bCoinNum,
      int welthNum, int charmNum, int levelid, int viewNum, long openDraw, String tronAddr,
      long tronBind, String drawJump, int drawPoint, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.giftNum = giftNum;
    this.loveNum = loveNum;
    this.coinNum = coinNum;
    this.silverNum = silverNum;
    this.bCoinNum = bCoinNum;
    this.welthNum = welthNum;
    this.charmNum = charmNum;
    this.levelid = levelid;
    this.viewNum = viewNum;
    this.openDraw = openDraw;
    if (tronAddr == null) {
      throw new IllegalArgumentException("tronAddr == null");
    }
    this.tronAddr = tronAddr;
    this.tronBind = tronBind;
    if (drawJump == null) {
      throw new IllegalArgumentException("drawJump == null");
    }
    this.drawJump = drawJump;
    this.drawPoint = drawPoint;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.giftNum = giftNum;
    builder.loveNum = loveNum;
    builder.coinNum = coinNum;
    builder.silverNum = silverNum;
    builder.bCoinNum = bCoinNum;
    builder.welthNum = welthNum;
    builder.charmNum = charmNum;
    builder.levelid = levelid;
    builder.viewNum = viewNum;
    builder.openDraw = openDraw;
    builder.tronAddr = tronAddr;
    builder.tronBind = tronBind;
    builder.drawJump = drawJump;
    builder.drawPoint = drawPoint;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", giftNum=").append(giftNum);
    builder.append(", loveNum=").append(loveNum);
    builder.append(", coinNum=").append(coinNum);
    builder.append(", silverNum=").append(silverNum);
    builder.append(", bCoinNum=").append(bCoinNum);
    builder.append(", welthNum=").append(welthNum);
    builder.append(", charmNum=").append(charmNum);
    builder.append(", levelid=").append(levelid);
    builder.append(", viewNum=").append(viewNum);
    builder.append(", openDraw=").append(openDraw);
    if (tronAddr != null) builder.append(", tronAddr=").append(Internal.sanitize(tronAddr));
    builder.append(", tronBind=").append(tronBind);
    if (drawJump != null) builder.append(", drawJump=").append(Internal.sanitize(drawJump));
    builder.append(", drawPoint=").append(drawPoint);
    return builder.replace(0, 2, "WelthInfo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<WelthInfo, Builder> {
    public int giftNum;

    public int loveNum;

    public int coinNum;

    public int silverNum;

    public double bCoinNum;

    public int welthNum;

    public int charmNum;

    public int levelid;

    public int viewNum;

    public long openDraw;

    public String tronAddr;

    public long tronBind;

    public String drawJump;

    public int drawPoint;

    public Builder() {
      giftNum = 0;
      loveNum = 0;
      coinNum = 0;
      silverNum = 0;
      bCoinNum = 0.0;
      welthNum = 0;
      charmNum = 0;
      levelid = 0;
      viewNum = 0;
      openDraw = 0L;
      tronAddr = "";
      tronBind = 0L;
      drawJump = "";
      drawPoint = 0;
    }

    /**
     * 礼物数量
     */
    public Builder giftNum(int giftNum) {
      this.giftNum = giftNum;
      return this;
    }

    /**
     * 爱心数量
     */
    public Builder loveNum(int loveNum) {
      this.loveNum = loveNum;
      return this;
    }

    /**
     * 钻石数量
     */
    public Builder coinNum(int coinNum) {
      this.coinNum = coinNum;
      return this;
    }

    /**
     * 银币数量
     */
    public Builder silverNum(int silverNum) {
      this.silverNum = silverNum;
      return this;
    }

    /**
     * 黑钻数量
     */
    public Builder bCoinNum(double bCoinNum) {
      this.bCoinNum = bCoinNum;
      return this;
    }

    /**
     * 财富数量
     */
    public Builder welthNum(int welthNum) {
      this.welthNum = welthNum;
      return this;
    }

    /**
     * 魅力数量
     */
    public Builder charmNum(int charmNum) {
      this.charmNum = charmNum;
      return this;
    }

    /**
     * 财富等级
     */
    public Builder levelid(int levelid) {
      this.levelid = levelid;
      return this;
    }

    /**
     * int32     ticketNum 	= 11;	//奖券数量
     * int32     pointNum 		= 12;	//积分数量
     * 来访数量
     */
    public Builder viewNum(int viewNum) {
      this.viewNum = viewNum;
      return this;
    }

    /**
     * int32     missionId    = 16;   //提现等级
     * int32     walletId     = 17;   //钱包称号
     * 是否开通提现，0 未开通，开通时间
     */
    public Builder openDraw(long openDraw) {
      this.openDraw = openDraw;
      return this;
    }

    /**
     * 波场账号
     */
    public Builder tronAddr(String tronAddr) {
      this.tronAddr = tronAddr;
      return this;
    }

    /**
     * 钱包账号绑定时间
     */
    public Builder tronBind(long tronBind) {
      this.tronBind = tronBind;
      return this;
    }

    /**
     * 提现跳转
     */
    public Builder drawJump(String drawJump) {
      this.drawJump = drawJump;
      return this;
    }

    /**
     * 提现积分（可提现的黑钻数量）
     */
    public Builder drawPoint(int drawPoint) {
      this.drawPoint = drawPoint;
      return this;
    }

    @Override
    public WelthInfo build() {
      return new WelthInfo(giftNum, loveNum, coinNum, silverNum, bCoinNum, welthNum, charmNum, levelid, viewNum, openDraw, tronAddr, tronBind, drawJump, drawPoint, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_WelthInfo extends ProtoAdapter<WelthInfo> {
    public ProtoAdapter_WelthInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, WelthInfo.class, "type.googleapis.com/haiyaa.WelthInfo", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(WelthInfo value) {
      int result = 0;
      if (!Objects.equals(value.giftNum, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(1, value.giftNum);
      }
      if (!Objects.equals(value.loveNum, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.loveNum);
      }
      if (!Objects.equals(value.coinNum, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(3, value.coinNum);
      }
      if (!Objects.equals(value.silverNum, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(4, value.silverNum);
      }
      if (!Objects.equals(value.bCoinNum, 0.0)) {
        result += ProtoAdapter.DOUBLE.encodedSizeWithTag(5, value.bCoinNum);
      }
      if (!Objects.equals(value.welthNum, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(6, value.welthNum);
      }
      if (!Objects.equals(value.charmNum, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(7, value.charmNum);
      }
      if (!Objects.equals(value.levelid, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(8, value.levelid);
      }
      if (!Objects.equals(value.viewNum, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(13, value.viewNum);
      }
      if (!Objects.equals(value.openDraw, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(21, value.openDraw);
      }
      if (!Objects.equals(value.tronAddr, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(22, value.tronAddr);
      }
      if (!Objects.equals(value.tronBind, 0L)) {
        result += ProtoAdapter.INT64.encodedSizeWithTag(23, value.tronBind);
      }
      if (!Objects.equals(value.drawJump, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(24, value.drawJump);
      }
      if (!Objects.equals(value.drawPoint, 0)) {
        result += ProtoAdapter.INT32.encodedSizeWithTag(25, value.drawPoint);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, WelthInfo value) throws IOException {
      if (!Objects.equals(value.giftNum, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.giftNum);
      if (!Objects.equals(value.loveNum, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.loveNum);
      if (!Objects.equals(value.coinNum, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.coinNum);
      if (!Objects.equals(value.silverNum, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.silverNum);
      if (!Objects.equals(value.bCoinNum, 0.0)) ProtoAdapter.DOUBLE.encodeWithTag(writer, 5, value.bCoinNum);
      if (!Objects.equals(value.welthNum, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 6, value.welthNum);
      if (!Objects.equals(value.charmNum, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 7, value.charmNum);
      if (!Objects.equals(value.levelid, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 8, value.levelid);
      if (!Objects.equals(value.viewNum, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 13, value.viewNum);
      if (!Objects.equals(value.openDraw, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 21, value.openDraw);
      if (!Objects.equals(value.tronAddr, "")) ProtoAdapter.STRING.encodeWithTag(writer, 22, value.tronAddr);
      if (!Objects.equals(value.tronBind, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 23, value.tronBind);
      if (!Objects.equals(value.drawJump, "")) ProtoAdapter.STRING.encodeWithTag(writer, 24, value.drawJump);
      if (!Objects.equals(value.drawPoint, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 25, value.drawPoint);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public WelthInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.giftNum(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.loveNum(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.coinNum(ProtoAdapter.INT32.decode(reader)); break;
          case 4: builder.silverNum(ProtoAdapter.INT32.decode(reader)); break;
          case 5: builder.bCoinNum(ProtoAdapter.DOUBLE.decode(reader)); break;
          case 6: builder.welthNum(ProtoAdapter.INT32.decode(reader)); break;
          case 7: builder.charmNum(ProtoAdapter.INT32.decode(reader)); break;
          case 8: builder.levelid(ProtoAdapter.INT32.decode(reader)); break;
          case 13: builder.viewNum(ProtoAdapter.INT32.decode(reader)); break;
          case 21: builder.openDraw(ProtoAdapter.INT64.decode(reader)); break;
          case 22: builder.tronAddr(ProtoAdapter.STRING.decode(reader)); break;
          case 23: builder.tronBind(ProtoAdapter.INT64.decode(reader)); break;
          case 24: builder.drawJump(ProtoAdapter.STRING.decode(reader)); break;
          case 25: builder.drawPoint(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public WelthInfo redact(WelthInfo value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
