#/usr/bin/bash
#!/bin/bash
echo $IsWindows
# if $IsWindows; then
if false; then
# if [[ "$OSTYPE" == "win32" || "$OSTYPE" == "cygwin" || "$OSTYPE" == "msys" ]]; then
    # ../tools/protoc3.2.exe --proto_path=../ --go_out=plugins=grpc:../../usercmd/ ../*.proto
    echo 'windows proto...'
    ../tools/protoc3.2.exe --go_out=plugins=grpc:D:\\winshare\\src\\owlsvr --proto_path=D:\\winshare\\src\\owlsvr\\proto D:\\winshare\\src\\owlsvr\\proto\\*.proto
    echo 'finished'
else
    echo 'linux proto...'
    /root/bin/protoc --go_out=plugins=grpc:/mnt/winshare/src/owlsvr/ --proto_path=/mnt/winshare/src/owlsvr/proto/ /mnt/winshare/src/owlsvr/proto/*.proto
    echo 'finished'

    echo -e "// Code generated by protoc-gen-go lilihao.\n// DO NOT EDIT!" > /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2name.go
    echo -e "package model \nimport \"strconv\"\nvar (\n   Cmd2CmdNameMap = map[uint32]string{\n" >> /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2name.go
    more /mnt/winshare/src/owlsvr/svr/public/proto/haiyaa/pbcmd.pb.go |grep ": \"" >> /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2name.go
    echo -e "\n    }\n)\n\nfunc Cmd2Ctx(unCmd uint32) string {\n\tif _, ok := Cmd2CmdNameMap[unCmd]; ok {\n\t\treturn Cmd2CmdNameMap[unCmd]\n\t} else {\n\t\treturn strconv.Itoa(int(unCmd))\n\t}\n}" >> /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2name.go

    echo -e "// Code generated by protoc-gen-go lilihao.\n// DO NOT EDIT!" > /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2pb.go
    echo -e "package model \nimport (\n\t\"github.com/golang/protobuf/proto\" \n\t\"github.com/owlsvr/svr/public/proto/haiyaa\"\n)\n">> /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2pb.go
    echo -e "var (\n\tCmd2ProtoMap = map[uint32]proto.Message{\n" >> /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2pb.go
    more /mnt/winshare/src/owlsvr/svr/public/proto/haiyaa/pbcmd.pb.go | grep -E "Cmd =|SvrInCmd ="| grep -v "Cmd = 0" |grep "haiyaa." >> ./pbtmp
    awk -F '[// ]+' '{print "(uint32)""("$4")"":"$5","}'  ./pbtmp >> /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2pb.go
    echo -e "\n    }\n)\n\nfunc Cmd2Proto(unCmd uint32) (pbMsg proto.Message) {\n\tif _, ok := Cmd2ProtoMap[unCmd]; ok {\n\t\treturn Cmd2ProtoMap[unCmd]\n\t} else {\n\t\treturn &haiyaa.OneUserToMulti{}\n\t}\n}" >> /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2pb.go
    echo -e "var (\n\tCmdRsp2ProtoMap = map[uint32]proto.Message{\n" >> /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2pb.go
    awk -F '[// ]+' '{print "(uint32)""("$4")"":"$6","}'  ./pbtmp >> /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2pb.go
    echo -e "\n    }\n)\n\nfunc CmdRsp2Proto(unCmd uint32) (pbMsg proto.Message) {\n\tif _, ok := CmdRsp2ProtoMap[unCmd]; ok {\n\t\treturn CmdRsp2ProtoMap[unCmd]\n\t} else {\n\t\treturn &haiyaa.OneUserToMulti{}\n\t}\n}" >> /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2pb.go
    rm -rf ./pbtmp

    # echo -e "// Code generated by protoc-gen-go lilihao.\n// DO NOT EDIT!" > /mnt/winshare/src/owlsvr/svr/public/model/model_err2name.go
    # echo -e "package model \nimport \"strconv\"\nvar (\n   ErrCodeMap = map[uint32]string{\n" >> /mnt/winshare/src/owlsvr/svr/public/model/model_err2name.go
    # more /mnt/winshare/src/owlsvr/svr/public/proto/haiyaa/errcode.pb.go | grep -v "//" >> ./errtmp
    # awk -F '[// ]+' '{print "(uint32)""("$4")"":\" "$5" \","}' ./errtmp >> /mnt/winshare/src/owlsvr/svr/public/model/model_err2name.go
    # echo -e "\n    }\n)\n\nfunc Err2Ctx(unErr uint32) string {\n\tif _, ok := ErrCodeMap[unErr]; ok {\n\t\treturn ErrCodeMap[unErr]\n\t} else {\n\t\treturn strconv.Itoa(int(unErr))\n\t}\n}" >> /mnt/winshare/src/owlsvr/svr/public/model/model_err2name.go
    # rm -rf ./errtmp

    # echo -e "// Code generated by protoc-gen-go lilihao.\n// DO NOT EDIT!" > /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2journey.go
    # echo -e "package model \nvar (\n   Cmd2JourneyMap = map[uint32]string{\n" >> /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2journey.go
    # more /mnt/winshare/src/owlsvr/svr/public/proto/haiyaa/pbcmd.pb.go | grep -E "Cmd =|SvrInCmd ="| grep -v "Cmd = 0" |grep "haiyaa." | grep "UJ," > ./jrtmp
    # awk -F '[// ]+' '{print "(uint32)""("$4")"":\" "$1" \","}'  ./jrtmp >> /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2journey.go
    # echo -e "\n    }\n)\n\nfunc IsValidJourney(unCmd uint32) bool {\n\tif _, ok := Cmd2JourneyMap[unCmd]; ok {\n\t\treturn true\n\t} else {\n\t\treturn false\n\t}\n}" >> /mnt/winshare/src/owlsvr/svr/public/model/model_cmd2journey.go
    # rm -rf ./jrtmp
fi


